INSERT INTO public.products (id, name, price) VALUES (0, 'CgXlBUntmtBosXyIqo ', 398.58);
INSERT INTO public.products (id, name, price) VALUES (1, 'ksAqUlCc ', 903.63);
INSERT INTO public.products (id, name, price) VALUES (2, 'bUvnsvtDmiERmtwEWxWy', 132);
INSERT INTO public.products (id, name, price) VALUES (3, 'ZCgifHLsbX', 455.36);
INSERT INTO public.products (id, name, price) VALUES (4, 'uASRoELUVVw', 871.82);
INSERT INTO public.products (id, name, price) VALUES (5, 'UHfQhvvOCza', 593.13);
INSERT INTO public.products (id, name, price) VALUES (6, 'qFcGAs', 269.61);
INSERT INTO public.products (id, name, price) VALUES (7, 'pxUh ', 799.76);
INSERT INTO public.products (id, name, price) VALUES (8, 'DnMkGTcwS', 261.7);
INSERT INTO public.products (id, name, price) VALUES (9, 'BDYtuSTthFL', 953.34);
INSERT INTO public.products (id, name, price) VALUES (10, 'Eub Z', 350.97);
INSERT INTO public.products (id, name, price) VALUES (11, 'DSVUQLlAzWtPY', 190.2);
INSERT INTO public.products (id, name, price) VALUES (12, 'CfthdEzO', 45.2);
INSERT INTO public.products (id, name, price) VALUES (13, 'XfvyNsMGJjzfJt hjh', 188.11);
INSERT INTO public.products (id, name, price) VALUES (14, 'WMieDyNObZkgvthzy', 855.17);
INSERT INTO public.products (id, name, price) VALUES (15, 'jikFjrfUPYxcZJinnE', 858.62);
INSERT INTO public.products (id, name, price) VALUES (16, 'EmiAAOOOwYNbkJzI', 222.55);
INSERT INTO public.products (id, name, price) VALUES (17, 'TOrbLVyGlVAZeoe', 591.67);
INSERT INTO public.products (id, name, price) VALUES (18, 'mrlFYejiRiYIHpD', 82.49);
INSERT INTO public.products (id, name, price) VALUES (19, 'fjP FPPgWs fdQM', 85.92);
INSERT INTO public.products (id, name, price) VALUES (20, 'ADJkqa JdxpXJVjnUWr', 706.55);
INSERT INTO public.products (id, name, price) VALUES (21, 'xHuiWSbzwMR ', 223.79);
INSERT INTO public.products (id, name, price) VALUES (22, 'UQHjoTXIHsoCWdgbruxg', 618.1);
INSERT INTO public.products (id, name, price) VALUES (23, 'WEaDU', 229.88);
INSERT INTO public.products (id, name, price) VALUES (24, 'puYeZv', 605.2);
INSERT INTO public.products (id, name, price) VALUES (25, 'fOFIhyNKkMAdJT', 847.42);
INSERT INTO public.products (id, name, price) VALUES (26, 'fnjHWakRsMKGp', 737.82);
INSERT INTO public.products (id, name, price) VALUES (27, 'jsWkJPWrBbbtG', 562.07);
INSERT INTO public.products (id, name, price) VALUES (28, 'OepWxopfxtVCmklnqAR', 482.87);
INSERT INTO public.products (id, name, price) VALUES (29, 'mLsVgM', 913.01);
INSERT INTO public.products (id, name, price) VALUES (30, 'AtegAigX', 721.39);
INSERT INTO public.products (id, name, price) VALUES (31, 'TqnnGN', 766.62);
INSERT INTO public.products (id, name, price) VALUES (32, 'q aWLTAnqIEAKBFWx', 607.56);
INSERT INTO public.products (id, name, price) VALUES (33, 'GoeOZDbw mbmOSHuFJ', 340.39);
INSERT INTO public.products (id, name, price) VALUES (34, 'ZaWMwMvYR', 153.57);
INSERT INTO public.products (id, name, price) VALUES (35, 'PxMlXztLPLR', 586.45);
INSERT INTO public.products (id, name, price) VALUES (36, 'rCYvfqvRO', 216.77);
INSERT INTO public.products (id, name, price) VALUES (37, 'HuzXZNm', 586.81);
INSERT INTO public.products (id, name, price) VALUES (38, 'XZlPn', 89.01);
INSERT INTO public.products (id, name, price) VALUES (39, 'GoCcfLANGiQP', 929.04);
INSERT INTO public.products (id, name, price) VALUES (40, 'LUWIZBJNcuozFdkUl', 956.22);
INSERT INTO public.products (id, name, price) VALUES (41, 'PZTVzEDvGSaZkjVci', 77.63);
INSERT INTO public.products (id, name, price) VALUES (42, 'ATzWEbxhGtxfmf', 20.13);
INSERT INTO public.products (id, name, price) VALUES (43, 'TtaqFWeWe', 544.29);
INSERT INTO public.products (id, name, price) VALUES (44, 'HNlmQvWYRYVxUSq', 444.31);
INSERT INTO public.products (id, name, price) VALUES (45, 'VmsCW', 621.18);
INSERT INTO public.products (id, name, price) VALUES (46, 'vJRDwgaqFQ i', 864.61);
INSERT INTO public.products (id, name, price) VALUES (47, 'YLrrVnBoneEmqZnJmOVH', 835.27);
INSERT INTO public.products (id, name, price) VALUES (48, 'MQs KncLUhNeKJRNJgRq', 776.33);
INSERT INTO public.products (id, name, price) VALUES (49, 'LnEmXee ecyy', 310.8);
INSERT INTO public.products (id, name, price) VALUES (50, 'lqSJphthUdj', 858.08);
INSERT INTO public.products (id, name, price) VALUES (51, 'JoaXdv kjjuXNlQvDSS', 368.69);
INSERT INTO public.products (id, name, price) VALUES (52, 'VTOZmWExf', 918.33);
INSERT INTO public.products (id, name, price) VALUES (53, 'ILbDMCwuoGx u', 330.12);
INSERT INTO public.products (id, name, price) VALUES (54, 'qBwnWawMcNxWiX', 253.4);
INSERT INTO public.products (id, name, price) VALUES (55, 'gPKasYFujpeDhe  y', 422.41);
INSERT INTO public.products (id, name, price) VALUES (56, 'VYppEcrIlRVXXFapreqL', 1000.26);
INSERT INTO public.products (id, name, price) VALUES (57, 'lZJagDDQOW', 207.07);
INSERT INTO public.products (id, name, price) VALUES (58, 'T XWjDPjpTq', 7.11);
INSERT INTO public.products (id, name, price) VALUES (59, 'fuIVLhpPey', 954.39);
INSERT INTO public.products (id, name, price) VALUES (60, 'laBWnwwXbTl', 647.94);
INSERT INTO public.products (id, name, price) VALUES (61, 'wiRCUPceVlLZSbE', 158.6);
INSERT INTO public.products (id, name, price) VALUES (62, 'WUvDadTDHOba', 59.48);
INSERT INTO public.products (id, name, price) VALUES (63, 'ozyTzBPtCYPpba l', 598.27);
INSERT INTO public.products (id, name, price) VALUES (64, 'nxByCD', 779.71);
INSERT INTO public.products (id, name, price) VALUES (65, 'AeZasfvimajYpkqWfqHa', 461.81);
INSERT INTO public.products (id, name, price) VALUES (66, 'HnjSwq btbaPaMAcZs', 824.17);
INSERT INTO public.products (id, name, price) VALUES (67, 'UvnLgPEEUjMJGxcoJz', 510.22);
INSERT INTO public.products (id, name, price) VALUES (68, 'wfycjYH akVTTnR', 792.75);
INSERT INTO public.products (id, name, price) VALUES (69, 'laRXKAMfmgOScqTAmyW', 139.84);
INSERT INTO public.products (id, name, price) VALUES (70, 'heJAxjsoiplSATvF', 90.47);
INSERT INTO public.products (id, name, price) VALUES (71, 'KFDYZHWhQfNTL f', 755.48);
INSERT INTO public.products (id, name, price) VALUES (72, 'vZxCux', 80.07);
INSERT INTO public.products (id, name, price) VALUES (73, 't JLrKTdX', 392.41);
INSERT INTO public.products (id, name, price) VALUES (74, 'IGnCEJLOinCBRgYBU', 762.93);
INSERT INTO public.products (id, name, price) VALUES (75, 'KQKtOgEYNySzw', 19.52);
INSERT INTO public.products (id, name, price) VALUES (76, 'EhybwutrPlkWToEOmjLc', 289.63);
INSERT INTO public.products (id, name, price) VALUES (77, 'uIsapwbVaCleXqAJID', 205.01);
INSERT INTO public.products (id, name, price) VALUES (78, 'BTTic', 572.36);
INSERT INTO public.products (id, name, price) VALUES (79, 'nLqxvO', 185.14);
INSERT INTO public.products (id, name, price) VALUES (80, 'wyNlJtksXJ', 856.97);
INSERT INTO public.products (id, name, price) VALUES (81, 'prZpxsfSHrZZYKuUsk', 164.39);
INSERT INTO public.products (id, name, price) VALUES (82, 'YlpmuYKkigwmTR', 347.7);
INSERT INTO public.products (id, name, price) VALUES (83, 'MhoEYmjLWZM', 185.71);
INSERT INTO public.products (id, name, price) VALUES (84, 'ZTXQxxBOHIqprStyx', 510.42);
INSERT INTO public.products (id, name, price) VALUES (85, 'VFSLvjqH', 78.03);
INSERT INTO public.products (id, name, price) VALUES (86, 'GQLTOwovlWkP', 92.55);
INSERT INTO public.products (id, name, price) VALUES (87, 'NETxZ', 125.76);
INSERT INTO public.products (id, name, price) VALUES (88, 'EdENULBJmYHYS', 519.71);
INSERT INTO public.products (id, name, price) VALUES (89, 'nwVaGfGP xqVJCW', 684.48);
INSERT INTO public.products (id, name, price) VALUES (90, 'pMzAoko', 530.42);
INSERT INTO public.products (id, name, price) VALUES (91, 'DNxgeHQfPInQF jUhMPK', 608.28);
INSERT INTO public.products (id, name, price) VALUES (92, 'IaPTaX', 193.97);
INSERT INTO public.products (id, name, price) VALUES (93, 'cNjXgjBC', 589.1);
INSERT INTO public.products (id, name, price) VALUES (94, 'ZgdlLwFybzi', 955.24);
INSERT INTO public.products (id, name, price) VALUES (95, ' oCRfkfgjBWzdBAGu', 638.77);
INSERT INTO public.products (id, name, price) VALUES (96, 'ydczXS', 939.13);
INSERT INTO public.products (id, name, price) VALUES (97, 'evg TbzTUII', 43.37);
INSERT INTO public.products (id, name, price) VALUES (98, 'ASQcsNrRXyZEMw', 489.28);
INSERT INTO public.products (id, name, price) VALUES (99, 'OB gx', 893.94);
INSERT INTO public.products (id, name, price) VALUES (100, 'wPoU AdO', 618.04);
INSERT INTO public.products (id, name, price) VALUES (101, 'UcZglfsTyKrVDrffL', 163.73);
INSERT INTO public.products (id, name, price) VALUES (102, 'dxcsQiQUeoJkq', 731.03);
INSERT INTO public.products (id, name, price) VALUES (103, 'OJYlZS', 176.48);
INSERT INTO public.products (id, name, price) VALUES (104, 'sMDIiq yWHHBYi', 951.5);
INSERT INTO public.products (id, name, price) VALUES (105, 'CHWQPAdQ', 676.3);
INSERT INTO public.products (id, name, price) VALUES (106, 'FdwqojAmvDAQjZ', 6.23);
INSERT INTO public.products (id, name, price) VALUES (107, 'pXnymehQE', 905.85);
INSERT INTO public.products (id, name, price) VALUES (108, 'BYBaursjG', 163.34);
INSERT INTO public.products (id, name, price) VALUES (109, ' YCCpdGwqmWYxrxhw', 857.07);
INSERT INTO public.products (id, name, price) VALUES (110, 'aruKbSZXTTzfQmkCVCwO', 836.39);
INSERT INTO public.products (id, name, price) VALUES (111, 'fgnOyQq', 536.72);
INSERT INTO public.products (id, name, price) VALUES (112, 'jXIwCJlgrcPtCkYiOO', 990.75);
INSERT INTO public.products (id, name, price) VALUES (113, 'DKRykITJqTsseRGpCPxa', 198.3);
INSERT INTO public.products (id, name, price) VALUES (114, 'neOhWLlXdApzUcBN', 626.56);
INSERT INTO public.products (id, name, price) VALUES (115, 'FUpR spVFLk', 881.65);
INSERT INTO public.products (id, name, price) VALUES (116, 'qmPLjioWqLnNNwW lx', 277.54);
INSERT INTO public.products (id, name, price) VALUES (117, 'DloCmdhh', 972.39);
INSERT INTO public.products (id, name, price) VALUES (118, 'CjOIoCdXVwJWf', 746.19);
INSERT INTO public.products (id, name, price) VALUES (119, 'PwAmQuGXqRABCAwRpC', 120.4);
INSERT INTO public.products (id, name, price) VALUES (120, 'ShpUTyJIEWJfzYIC', 869.65);
INSERT INTO public.products (id, name, price) VALUES (121, 'IzBeMHHjweJHXq', 339.55);
INSERT INTO public.products (id, name, price) VALUES (122, 'LkqxYkaXl', 975.77);
INSERT INTO public.products (id, name, price) VALUES (123, 'ToPEGXrlDl', 691.67);
INSERT INTO public.products (id, name, price) VALUES (124, 'kxpmSkreZLmDng', 322.74);
INSERT INTO public.products (id, name, price) VALUES (125, 'cLMIZGkogkElzd', 219.9);
INSERT INTO public.products (id, name, price) VALUES (126, 'nKJnVldwpCdLLBWdoxX', 384.21);
INSERT INTO public.products (id, name, price) VALUES (127, 'GOJPYmBoNGZwMqG', 89.02);
INSERT INTO public.products (id, name, price) VALUES (128, 'XMntRLOzb', 990.33);
INSERT INTO public.products (id, name, price) VALUES (129, 'vGJawkqqF', 240.35);
INSERT INTO public.products (id, name, price) VALUES (130, 'MUOVBbPoqFUOH', 963.23);
INSERT INTO public.products (id, name, price) VALUES (131, 'VGbskgHjJTQyGUVLkQ', 60.93);
INSERT INTO public.products (id, name, price) VALUES (132, ' PiTbRcaSWKNM', 423.42);
INSERT INTO public.products (id, name, price) VALUES (133, 'XDAZQgqSeKCEyATRRUL', 80.22);
INSERT INTO public.products (id, name, price) VALUES (134, 'zpbhd IL', 688.23);
INSERT INTO public.products (id, name, price) VALUES (135, 'CdjcSRVTMtgmRxCdlLSl', 730.93);
INSERT INTO public.products (id, name, price) VALUES (136, 'Ll wIYfYBt', 186.3);
INSERT INTO public.products (id, name, price) VALUES (137, 'hLxTlWHhFoiSszc', 419.43);
INSERT INTO public.products (id, name, price) VALUES (138, 'XVbqSvSET', 730.13);
INSERT INTO public.products (id, name, price) VALUES (139, 'RKcnLnARktJHJU', 280.67);
INSERT INTO public.products (id, name, price) VALUES (140, 'VqnoV', 932.29);
INSERT INTO public.products (id, name, price) VALUES (141, 'eQoHevJQSoQQBvx', 595.82);
INSERT INTO public.products (id, name, price) VALUES (142, 'hjdbvkFQdoAFR', 525.43);
INSERT INTO public.products (id, name, price) VALUES (143, 'uIZolVJEEOyJOvnVw', 864.87);
INSERT INTO public.products (id, name, price) VALUES (144, 'pnbSmgBWwAuYek', 817.1);
INSERT INTO public.products (id, name, price) VALUES (145, 'VnvdJeKBiohLycYazc', 976.22);
INSERT INTO public.products (id, name, price) VALUES (146, 'hKhIPTy', 765.36);
INSERT INTO public.products (id, name, price) VALUES (147, 'NEqdB', 891.13);
INSERT INTO public.products (id, name, price) VALUES (148, 'oOQRkZhwrZiVBm', 467);
INSERT INTO public.products (id, name, price) VALUES (149, 'UWxUPZTFgKZIqVm', 249.99);
INSERT INTO public.products (id, name, price) VALUES (150, 'HCaxUpSdkVG mF', 711.49);
INSERT INTO public.products (id, name, price) VALUES (151, 'vUMliMlzLcAwz', 400.13);
INSERT INTO public.products (id, name, price) VALUES (152, 'CDjMqth', 174.41);
INSERT INTO public.products (id, name, price) VALUES (153, 'ksionGSI', 324.53);
INSERT INTO public.products (id, name, price) VALUES (154, 'qgmYaeKUV', 18.19);
INSERT INTO public.products (id, name, price) VALUES (155, 'oCbrcsRriiazJGHSnk', 451.26);
INSERT INTO public.products (id, name, price) VALUES (156, 'rozKDOUolndypgbo', 46.53);
INSERT INTO public.products (id, name, price) VALUES (157, 'ilYgMDxQGrFhNWpo', 655.23);
INSERT INTO public.products (id, name, price) VALUES (158, 'kSBQWYqbqq', 798.46);
INSERT INTO public.products (id, name, price) VALUES (159, 'AHbeXvUhG', 934.15);
INSERT INTO public.products (id, name, price) VALUES (160, 'kbLRbgfchNTnrmrctuX', 782.47);
INSERT INTO public.products (id, name, price) VALUES (161, 'KdujeS', 332.54);
INSERT INTO public.products (id, name, price) VALUES (162, 'GZfuIEIr', 913.47);
INSERT INTO public.products (id, name, price) VALUES (163, 'WzDqylt', 881.93);
INSERT INTO public.products (id, name, price) VALUES (164, 'IeUrLvtBJsdQypjqLe', 969.27);
INSERT INTO public.products (id, name, price) VALUES (165, 'ESydvcs', 325.53);
INSERT INTO public.products (id, name, price) VALUES (166, 'jgzefSpRW', 792.86);
INSERT INTO public.products (id, name, price) VALUES (167, 'x LGrhjszYXl', 369.11);
INSERT INTO public.products (id, name, price) VALUES (168, 'FdpbMxpJpunghzo', 712.36);
INSERT INTO public.products (id, name, price) VALUES (169, 'vVIhAaScoQpMZI FI', 26.36);
INSERT INTO public.products (id, name, price) VALUES (170, 'GPmargXs', 164.88);
INSERT INTO public.products (id, name, price) VALUES (171, 'KlVzfGjkwduy', 562.07);
INSERT INTO public.products (id, name, price) VALUES (172, 'nYqDKtSmSEVpUOhlxEyl', 745.25);
INSERT INTO public.products (id, name, price) VALUES (173, 'TmzeTk', 324.18);
INSERT INTO public.products (id, name, price) VALUES (174, 'QDcNaQEs EVVvIxsX Cy', 805.93);
INSERT INTO public.products (id, name, price) VALUES (175, 'zaVVdmvNtZIx', 234.26);
INSERT INTO public.products (id, name, price) VALUES (176, 'RQLtaAtboR', 411.5);
INSERT INTO public.products (id, name, price) VALUES (177, 'gTTFuIEFljNfGPUo', 336.12);
INSERT INTO public.products (id, name, price) VALUES (178, 'zPdlVygKZgUL', 147.36);
INSERT INTO public.products (id, name, price) VALUES (179, 'mVgOuRCE', 35.58);
INSERT INTO public.products (id, name, price) VALUES (180, 'KTeQt', 383.84);
INSERT INTO public.products (id, name, price) VALUES (181, 'LeVyJkcjcArIitWbp', 804.37);
INSERT INTO public.products (id, name, price) VALUES (182, 'uzNcuNMAIJqDmSTmYqW', 662.55);
INSERT INTO public.products (id, name, price) VALUES (183, 'UtdrwNbmNtGTXXvMoVcL', 958.85);
INSERT INTO public.products (id, name, price) VALUES (184, ' hxSfwVWkgsSbExe lk', 843.54);
INSERT INTO public.products (id, name, price) VALUES (185, 'LkXbM', 297.54);
INSERT INTO public.products (id, name, price) VALUES (186, 'xmjGyIRmwmzlNe', 390.8);
INSERT INTO public.products (id, name, price) VALUES (187, 'kkzpGGK UreuNEHuT', 816.61);
INSERT INTO public.products (id, name, price) VALUES (188, ' FiXUpYRR', 371.93);
INSERT INTO public.products (id, name, price) VALUES (189, 'kosMkwqlIMxFGocwax ', 731.68);
INSERT INTO public.products (id, name, price) VALUES (190, 'QSyxMttQX siN', 381.09);
INSERT INTO public.products (id, name, price) VALUES (191, 'AQGlmivFulTOHH', 826.22);
INSERT INTO public.products (id, name, price) VALUES (192, 'HbfMUpGxxYW', 119.43);
INSERT INTO public.products (id, name, price) VALUES (193, 'vArTanQmFtRdsPgw', 306.31);
INSERT INTO public.products (id, name, price) VALUES (194, 'ASkyWBi', 372.31);
INSERT INTO public.products (id, name, price) VALUES (195, 'UsmnWnawCjcxdSgnXovL', 759.66);
INSERT INTO public.products (id, name, price) VALUES (196, 'Rscf JhR', 966.31);
INSERT INTO public.products (id, name, price) VALUES (197, 'qyqDszXf', 947.22);
INSERT INTO public.products (id, name, price) VALUES (198, 'rxzvMoCZvwrfXMLnINbw', 676.65);
INSERT INTO public.products (id, name, price) VALUES (199, 'jDhzjyweWOR', 607.66);
INSERT INTO public.products (id, name, price) VALUES (200, 'jpKZlbZAfahXxUrNWwHx', 505.22);
INSERT INTO public.products (id, name, price) VALUES (201, 'EmYvogwtwsNOngtR', 976.65);
INSERT INTO public.products (id, name, price) VALUES (202, 'KNvCCngwDVEq', 732.65);
INSERT INTO public.products (id, name, price) VALUES (203, 'kHiHBrQuofZsTlfYxmxS', 553.93);
INSERT INTO public.products (id, name, price) VALUES (204, 'mBE fSAfrcW', 334.63);
INSERT INTO public.products (id, name, price) VALUES (205, 'CJQGpwxZoVs', 492.16);
INSERT INTO public.products (id, name, price) VALUES (206, 'qmTQedzeDulQOlyJouGp', 839.42);
INSERT INTO public.products (id, name, price) VALUES (207, 'nqNZRhoZNZU ', 605.36);
INSERT INTO public.products (id, name, price) VALUES (208, 'GtXTbcdDDDbSCgaeB ', 49.64);
INSERT INTO public.products (id, name, price) VALUES (209, 'XgDGCaGZuqplNCWj', 784.43);
INSERT INTO public.products (id, name, price) VALUES (210, 'vPwGplTDgVAGwQAFwR', 969.73);
INSERT INTO public.products (id, name, price) VALUES (211, 'PYGHBeE', 746.5);
INSERT INTO public.products (id, name, price) VALUES (212, ' dNumMtVxOCBL', 936.68);
INSERT INTO public.products (id, name, price) VALUES (213, 'zkHGrdbswdlu', 650.1);
INSERT INTO public.products (id, name, price) VALUES (214, 'NigKLWrux', 824.87);
INSERT INTO public.products (id, name, price) VALUES (215, 'FwzRzw', 686.49);
INSERT INTO public.products (id, name, price) VALUES (216, 'UfQKdclPlhNmFe', 259.51);
INSERT INTO public.products (id, name, price) VALUES (217, 'e  IJwFXUvwTdvIPFn', 527.92);
INSERT INTO public.products (id, name, price) VALUES (218, 'LEXwGrFZJr', 372.72);
INSERT INTO public.products (id, name, price) VALUES (219, 'lduLyYokuKhNLPWy', 908.23);
INSERT INTO public.products (id, name, price) VALUES (220, 'wvYEywkt afnPbvIoklA', 707.2);
INSERT INTO public.products (id, name, price) VALUES (221, ' ikmLTHP jcnIa', 729.68);
INSERT INTO public.products (id, name, price) VALUES (222, 'PtqYewzOF', 64.47);
INSERT INTO public.products (id, name, price) VALUES (223, 'sOBryLFYpeMgvLCM Lbx', 943.31);
INSERT INTO public.products (id, name, price) VALUES (224, 'dhjJAssBybVVpnrGzV', 680.03);
INSERT INTO public.products (id, name, price) VALUES (225, 'vUfyHeJr', 290.56);
INSERT INTO public.products (id, name, price) VALUES (226, 'IeewnCaFxqBzfXQTqaqU', 620.87);
INSERT INTO public.products (id, name, price) VALUES (227, 'SrGDctbs', 790.75);
INSERT INTO public.products (id, name, price) VALUES (228, 'QFpknymKE', 9.73);
INSERT INTO public.products (id, name, price) VALUES (229, 'omBThwbc', 602.03);
INSERT INTO public.products (id, name, price) VALUES (230, 'jkqFkCgnrjSsCAi', 499.63);
INSERT INTO public.products (id, name, price) VALUES (231, 'CPhMiY oUMxLrUrSsnEV', 242.77);
INSERT INTO public.products (id, name, price) VALUES (232, 'rANcsJIkLnTpNgcwOTAG', 353.1);
INSERT INTO public.products (id, name, price) VALUES (233, 'IcGlSBIZUOaSyr', 876.2);
INSERT INTO public.products (id, name, price) VALUES (234, 'ToSArOpVcULEXQfQdV', 397.49);
INSERT INTO public.products (id, name, price) VALUES (235, 'cS I PCdkPa', 955.33);
INSERT INTO public.products (id, name, price) VALUES (236, 'qrqTmZcFYiairk', 154.1);
INSERT INTO public.products (id, name, price) VALUES (237, 'hmNFbgDVQHs nA', 317.72);
INSERT INTO public.products (id, name, price) VALUES (238, 'JZBFvXGfwdTuQOMV', 608.25);
INSERT INTO public.products (id, name, price) VALUES (239, 'kv kR N', 799.15);
INSERT INTO public.products (id, name, price) VALUES (240, 'zzJGeilFSE', 809.34);
INSERT INTO public.products (id, name, price) VALUES (241, 'oGMrL', 292.67);
INSERT INTO public.products (id, name, price) VALUES (242, 'UrsHdKgmywHkfn', 569.15);
INSERT INTO public.products (id, name, price) VALUES (243, 'pTQFdcsFKPs', 545.96);
INSERT INTO public.products (id, name, price) VALUES (244, 'oYCwFvresPGUoMBzpl X', 372.55);
INSERT INTO public.products (id, name, price) VALUES (245, 'OznOkwzw', 903.22);
INSERT INTO public.products (id, name, price) VALUES (246, 'XDaPBXN SBlA', 405.12);
INSERT INTO public.products (id, name, price) VALUES (247, 'AWaHZwKhuOgafOLLffLT', 337.49);
INSERT INTO public.products (id, name, price) VALUES (248, 'AfOSofreyKFEGKXgjx', 746.61);
INSERT INTO public.products (id, name, price) VALUES (249, 'QujZjPNlSWh', 453.68);
INSERT INTO public.products (id, name, price) VALUES (250, 'oaBJzqrShDVAQTy', 924.97);
INSERT INTO public.products (id, name, price) VALUES (251, 'zROhNjpsVg', 26.72);
INSERT INTO public.products (id, name, price) VALUES (252, 'CnuCXJ', 38.62);
INSERT INTO public.products (id, name, price) VALUES (253, 'iiZtaKxy', 808.31);
INSERT INTO public.products (id, name, price) VALUES (254, 'qdR XjbEXU', 53.5);
INSERT INTO public.products (id, name, price) VALUES (255, 'lmwIGTGgYIaNBGGpebPF', 795.28);
INSERT INTO public.products (id, name, price) VALUES (256, 'jjFftxnfruj', 574.46);
INSERT INTO public.products (id, name, price) VALUES (257, 'VnmJReQHVfoFjilkfdD', 426.87);
INSERT INTO public.products (id, name, price) VALUES (258, 'j at rzZuoxhzlCMRRF', 717.18);
INSERT INTO public.products (id, name, price) VALUES (259, ' AHQTFqKPaAKWWc', 825.76);
INSERT INTO public.products (id, name, price) VALUES (260, 'lJmHNlpTfvHGokBJWY', 548.95);
INSERT INTO public.products (id, name, price) VALUES (261, 'IQfaP', 692.67);
INSERT INTO public.products (id, name, price) VALUES (262, 'EUSMIrmR', 511.91);
INSERT INTO public.products (id, name, price) VALUES (263, 'UaSyZw', 611.25);
INSERT INTO public.products (id, name, price) VALUES (264, 'ZajtAg', 889.42);
INSERT INTO public.products (id, name, price) VALUES (265, 'AfeHRZMfrMKLnOL', 317.25);
INSERT INTO public.products (id, name, price) VALUES (266, 'fJfbYfIQzm', 595.49);
INSERT INTO public.products (id, name, price) VALUES (267, 'MK yKZsdRHMg', 821.32);
INSERT INTO public.products (id, name, price) VALUES (268, 'luJECMsPrOB', 745.78);
INSERT INTO public.products (id, name, price) VALUES (269, 'OhejcAhmCufzyDOYMDD', 239.98);
INSERT INTO public.products (id, name, price) VALUES (270, 'cuussEfPdrEmiCIVGs', 452.58);
INSERT INTO public.products (id, name, price) VALUES (271, 'JzMsmbhHIiT', 32.2);
INSERT INTO public.products (id, name, price) VALUES (272, 'iqkMcSWEHNfmlAkb', 509.24);
INSERT INTO public.products (id, name, price) VALUES (273, ' aIuXf CGJjX', 158.14);
INSERT INTO public.products (id, name, price) VALUES (274, 'zZdAaP', 613.22);
INSERT INTO public.products (id, name, price) VALUES (275, 'kfKVI p', 320.5);
INSERT INTO public.products (id, name, price) VALUES (276, 'GkWZRaDzM', 754.66);
INSERT INTO public.products (id, name, price) VALUES (277, 'RQggVssmfYZixtglEb', 561.5);
INSERT INTO public.products (id, name, price) VALUES (278, 'mfXuEewU HlxURVkwdIG', 938.22);
INSERT INTO public.products (id, name, price) VALUES (279, 'IrOmvEuGBFrqpK EOdye', 66.61);
INSERT INTO public.products (id, name, price) VALUES (280, 'oQQepY', 248.49);
INSERT INTO public.products (id, name, price) VALUES (281, 'vUVgOAiEjJHGK', 646.93);
INSERT INTO public.products (id, name, price) VALUES (282, 'NIQHqPn', 763.19);
INSERT INTO public.products (id, name, price) VALUES (283, 'HWkgFtoRlPPSvBSJSYol', 437.17);
INSERT INTO public.products (id, name, price) VALUES (284, 'XeOXXmFeajhrY Q', 723.74);
INSERT INTO public.products (id, name, price) VALUES (285, 'zkgKsJN', 559.82);
INSERT INTO public.products (id, name, price) VALUES (286, 'iUokOA', 420.51);
INSERT INTO public.products (id, name, price) VALUES (287, 'm uHqThZdQGxWowsVHK', 603.09);
INSERT INTO public.products (id, name, price) VALUES (288, 'KZZteiuqYRsIfHIZN', 524.24);
INSERT INTO public.products (id, name, price) VALUES (289, 'VaQzbRLslS', 818.01);
INSERT INTO public.products (id, name, price) VALUES (290, 'LqsWCWzSWIf', 255.56);
INSERT INTO public.products (id, name, price) VALUES (291, 'SculdCCUVHyCC', 179.41);
INSERT INTO public.products (id, name, price) VALUES (292, 'rXEVzGmdZQBFMo', 308.49);
INSERT INTO public.products (id, name, price) VALUES (293, 'SIhvqYlReAHQwXqGCf', 274.99);
INSERT INTO public.products (id, name, price) VALUES (294, 'eJaGKReBFnGKNBCZLKeY', 250.67);
INSERT INTO public.products (id, name, price) VALUES (295, 'NizClr', 365.94);
INSERT INTO public.products (id, name, price) VALUES (296, 'xLgJefjBRfgebBivcpy', 624.06);
INSERT INTO public.products (id, name, price) VALUES (297, 'ZEzaJFPZUi  ArMTffd', 623.3);
INSERT INTO public.products (id, name, price) VALUES (298, 'oulUHjIDFhPGs', 966.7);
INSERT INTO public.products (id, name, price) VALUES (299, 'PTSVTnvyOhosZetLHHgh', 541.31);
INSERT INTO public.products (id, name, price) VALUES (300, 'Az fsOJak', 407.92);
INSERT INTO public.products (id, name, price) VALUES (301, 'LhncGTZLsDJJrI', 608.35);
INSERT INTO public.products (id, name, price) VALUES (302, 'nGePcxdK kr', 455.92);
INSERT INTO public.products (id, name, price) VALUES (303, 'kbLtyrqoPAOQTJpIo', 769.31);
INSERT INTO public.products (id, name, price) VALUES (304, 'JtdjsfDMt', 941.77);
INSERT INTO public.products (id, name, price) VALUES (305, 'yauEYPXsiyYQDb', 908.37);
INSERT INTO public.products (id, name, price) VALUES (306, 'nHabXlTvc tnjRVslpe', 282.21);
INSERT INTO public.products (id, name, price) VALUES (307, ' EWayfkqzVHjn', 143.41);
INSERT INTO public.products (id, name, price) VALUES (308, 'TIZBdjzrAMXgYAk', 623.04);
INSERT INTO public.products (id, name, price) VALUES (309, 'MgFsl dEXTEwyVDw', 175.77);
INSERT INTO public.products (id, name, price) VALUES (310, 'k PJVbvZ', 896.62);
INSERT INTO public.products (id, name, price) VALUES (311, 'mmbSIvUpFjNvFVwVj', 43.56);
INSERT INTO public.products (id, name, price) VALUES (312, 'DELZfJAvzVfZt', 809.75);
INSERT INTO public.products (id, name, price) VALUES (313, 'XPNLPKKdVQzfVgFuGijI', 980.29);
INSERT INTO public.products (id, name, price) VALUES (314, 'YYeXZZOdQqHAzjl', 463.85);
INSERT INTO public.products (id, name, price) VALUES (315, 'OQiZqROmRmi', 399.85);
INSERT INTO public.products (id, name, price) VALUES (316, 'HajgymcZCbQFucpnd', 871.06);
INSERT INTO public.products (id, name, price) VALUES (317, 'yopIzIeAr', 504.84);
INSERT INTO public.products (id, name, price) VALUES (318, 'LzcLjVjeicXubYws', 915.61);
INSERT INTO public.products (id, name, price) VALUES (319, 'TVhpYGj', 145.69);
INSERT INTO public.products (id, name, price) VALUES (320, 'lyKinITLkF', 852.03);
INSERT INTO public.products (id, name, price) VALUES (321, 'exOkIdQsnQNJjOBO', 341);
INSERT INTO public.products (id, name, price) VALUES (322, 'tiQkxDCOIfZ', 860.45);
INSERT INTO public.products (id, name, price) VALUES (323, 'tyynVwCUzmL', 344.46);
INSERT INTO public.products (id, name, price) VALUES (324, 'zXoNQTGAyJ', 961.75);
INSERT INTO public.products (id, name, price) VALUES (325, 'vOBldlBriB', 393.13);
INSERT INTO public.products (id, name, price) VALUES (326, 'MyzryxbClJv', 611.05);
INSERT INTO public.products (id, name, price) VALUES (327, 'gQdkQnoOn', 8.85);
INSERT INTO public.products (id, name, price) VALUES (328, 'SqRaLbfEDtNjKW', 406.04);
INSERT INTO public.products (id, name, price) VALUES (329, 'GLxeyDpai', 734.38);
INSERT INTO public.products (id, name, price) VALUES (330, 'HXOFLV', 751.27);
INSERT INTO public.products (id, name, price) VALUES (331, 'pwlBfdHSgmdTuxHjPjzD', 895.56);
INSERT INTO public.products (id, name, price) VALUES (332, 'FKFmCEaIMNFlRl', 246.31);
INSERT INTO public.products (id, name, price) VALUES (333, 'XLo QdxYlLJbxnU', 106.88);
INSERT INTO public.products (id, name, price) VALUES (334, 'sd TlC UilEDFMOSg', 39.43);
INSERT INTO public.products (id, name, price) VALUES (335, 'uXSnGsGjHSafPpC U', 88.6);
INSERT INTO public.products (id, name, price) VALUES (336, 'sumHZYlRHfEHBckDCsJ', 303.74);
INSERT INTO public.products (id, name, price) VALUES (337, 'RaMHsN', 532.91);
INSERT INTO public.products (id, name, price) VALUES (338, 'LRrFfKYhLd', 745.35);
INSERT INTO public.products (id, name, price) VALUES (339, 'uMrxto', 942.82);
INSERT INTO public.products (id, name, price) VALUES (340, 'xWeEzk', 994.61);
INSERT INTO public.products (id, name, price) VALUES (341, 'mX jHy zWYDCC', 407.45);
INSERT INTO public.products (id, name, price) VALUES (342, 'GoEwoW', 853.39);
INSERT INTO public.products (id, name, price) VALUES (343, 'fq zMO', 142.72);
INSERT INTO public.products (id, name, price) VALUES (344, 'RRUOhpvn', 761.53);
INSERT INTO public.products (id, name, price) VALUES (345, 'wHcZxLXMJf', 61.05);
INSERT INTO public.products (id, name, price) VALUES (346, 'HjenDjYtCD', 781.67);
INSERT INTO public.products (id, name, price) VALUES (347, 'BDvzXQcYPYWi', 736.46);
INSERT INTO public.products (id, name, price) VALUES (348, 'RrCB vLn', 769.87);
INSERT INTO public.products (id, name, price) VALUES (349, 'uNdpZmBY', 845.66);
INSERT INTO public.products (id, name, price) VALUES (350, 'MctwcCOKTl', 633.81);
INSERT INTO public.products (id, name, price) VALUES (351, 'cwXrXHfRiofnekqkN', 777.42);
INSERT INTO public.products (id, name, price) VALUES (352, 'fLsKZgXwk', 562.53);
INSERT INTO public.products (id, name, price) VALUES (353, 'ieiEBGVUPuoUTtpHxYCo', 220.68);
INSERT INTO public.products (id, name, price) VALUES (354, 'DXMoOAe', 279.94);
INSERT INTO public.products (id, name, price) VALUES (355, 'BrFhkHOMOyOoBbyfO', 424.3);
INSERT INTO public.products (id, name, price) VALUES (356, 'IMihrkoisirzmdSWf', 73.12);
INSERT INTO public.products (id, name, price) VALUES (357, 'pCGkMXdvxOoF', 115.35);
INSERT INTO public.products (id, name, price) VALUES (358, 'XzKBDog', 11.36);
INSERT INTO public.products (id, name, price) VALUES (359, 'xrtS UuveMseKJIVQ', 34.74);
INSERT INTO public.products (id, name, price) VALUES (360, 'vniTFMcEIeWX', 231.41);
INSERT INTO public.products (id, name, price) VALUES (361, 'JIDUJaHzCiO', 964.96);
INSERT INTO public.products (id, name, price) VALUES (362, 'GpThQm', 427.17);
INSERT INTO public.products (id, name, price) VALUES (363, 'nvjXDNjDMlCWk', 489.3);
INSERT INTO public.products (id, name, price) VALUES (364, 'GQKezSodrtAISym', 89.87);
INSERT INTO public.products (id, name, price) VALUES (365, 'YSTzSbwFdsiHZU', 592.72);
INSERT INTO public.products (id, name, price) VALUES (366, 'WBOOIQSjGyDFOr', 422.19);
INSERT INTO public.products (id, name, price) VALUES (367, 'uTEiUmdOASj', 963.34);
INSERT INTO public.products (id, name, price) VALUES (368, 'GevsFAjYDzSeC', 770.78);
INSERT INTO public.products (id, name, price) VALUES (369, 'e ZlpVkuYkahSTBSOZ', 740.2);
INSERT INTO public.products (id, name, price) VALUES (370, 'RmpUkOHe', 271.14);
INSERT INTO public.products (id, name, price) VALUES (371, 'IEXLFItnyTBl', 104.93);
INSERT INTO public.products (id, name, price) VALUES (372, 'RTHamno', 730.01);
INSERT INTO public.products (id, name, price) VALUES (373, 'KvMxXlcSDW', 422.24);
INSERT INTO public.products (id, name, price) VALUES (374, 'NBlkWBOaHALVDWI', 258.21);
INSERT INTO public.products (id, name, price) VALUES (375, 'bKuyNR', 816.46);
INSERT INTO public.products (id, name, price) VALUES (376, 'uAcaoCbRY', 878.67);
INSERT INTO public.products (id, name, price) VALUES (377, 'PBLiy', 349.67);
INSERT INTO public.products (id, name, price) VALUES (378, 'XGiYZMbxvI WWzoBlao', 170.51);
INSERT INTO public.products (id, name, price) VALUES (379, 'xqHqeW zsWzU', 288.38);
INSERT INTO public.products (id, name, price) VALUES (380, 'HEaKgoElHBVsR', 394.87);
INSERT INTO public.products (id, name, price) VALUES (381, 'repnBqfVbg', 423.01);
INSERT INTO public.products (id, name, price) VALUES (382, 'jFvAlgKYIQTkKfvXqj', 613.31);
INSERT INTO public.products (id, name, price) VALUES (383, 'RGSBYgCNCZGtoglaQ', 759.41);
INSERT INTO public.products (id, name, price) VALUES (384, 'qwwIJfdvEFmK', 655.68);
INSERT INTO public.products (id, name, price) VALUES (385, 'MHOapFacyZz', 702.53);
INSERT INTO public.products (id, name, price) VALUES (386, 'MAfTYJhiyAF e', 11.56);
INSERT INTO public.products (id, name, price) VALUES (387, 'qzlBroXqR', 511.42);
INSERT INTO public.products (id, name, price) VALUES (388, 'wOcQpaMahQFQbGmeBeD', 907.07);
INSERT INTO public.products (id, name, price) VALUES (389, 'nLrOpCg', 543.07);
INSERT INTO public.products (id, name, price) VALUES (390, 'PWYChEWtiUQTUqJsGxpx', 817.17);
INSERT INTO public.products (id, name, price) VALUES (391, 'SpvYJKbiJKSa qvh', 177.33);
INSERT INTO public.products (id, name, price) VALUES (392, 'glZsuhp', 117.45);
INSERT INTO public.products (id, name, price) VALUES (393, ' rEzY VKKPX qthlJ', 781.72);
INSERT INTO public.products (id, name, price) VALUES (394, 'WCLuTVbNbnItmcoswJmH', 121.08);
INSERT INTO public.products (id, name, price) VALUES (395, 'TRzATV', 133.02);
INSERT INTO public.products (id, name, price) VALUES (396, 'XBBnSLNFowuqv', 280.61);
INSERT INTO public.products (id, name, price) VALUES (397, 'GAMPJrbofWUsSTLj', 989.47);
INSERT INTO public.products (id, name, price) VALUES (398, 'QUtabxdTXxbcWkWW', 843.55);
INSERT INTO public.products (id, name, price) VALUES (399, 'ikusckGuZt', 914.29);
INSERT INTO public.products (id, name, price) VALUES (400, 'mmVrTMj', 755.25);
INSERT INTO public.products (id, name, price) VALUES (401, 'RopaG', 31.77);
INSERT INTO public.products (id, name, price) VALUES (402, 'tbEEav', 116.28);
INSERT INTO public.products (id, name, price) VALUES (403, 'MFywxmCPROXFaDskYlm', 264.22);
INSERT INTO public.products (id, name, price) VALUES (404, 'vVuJdtPzlqURQgIsgcfv', 400.24);
INSERT INTO public.products (id, name, price) VALUES (405, 'qADHF', 845.67);
INSERT INTO public.products (id, name, price) VALUES (406, 'hVMSHIoxKyKEnZ', 118.28);
INSERT INTO public.products (id, name, price) VALUES (407, 'AcsGg', 651.48);
INSERT INTO public.products (id, name, price) VALUES (408, 'zUfjmFXO', 601.77);
INSERT INTO public.products (id, name, price) VALUES (409, 'souW raQVCCZGJ', 703.32);
INSERT INTO public.products (id, name, price) VALUES (410, 'unznKlc xJzIfdpqAWI', 151.24);
INSERT INTO public.products (id, name, price) VALUES (411, 'dkPREQGxfg', 981.63);
INSERT INTO public.products (id, name, price) VALUES (412, 'Oyxup', 529.32);
INSERT INTO public.products (id, name, price) VALUES (413, 'IzvfhBLm', 812.83);
INSERT INTO public.products (id, name, price) VALUES (414, 'TLaUYApuphqtjoQhsOk', 11.46);
INSERT INTO public.products (id, name, price) VALUES (415, 'uAOtsUi', 575.25);
INSERT INTO public.products (id, name, price) VALUES (416, 'LrYHcGAuVTHjqPITaC g', 627.05);
INSERT INTO public.products (id, name, price) VALUES (417, 'ZCJQe', 608.93);
INSERT INTO public.products (id, name, price) VALUES (418, 'lrldDzka', 712.62);
INSERT INTO public.products (id, name, price) VALUES (419, 'EDHOkW', 307.37);
INSERT INTO public.products (id, name, price) VALUES (420, 'TTwWIICfaUAczXtjppzD', 762.22);
INSERT INTO public.products (id, name, price) VALUES (421, 'paJkE mr', 117.6);
INSERT INTO public.products (id, name, price) VALUES (422, 'AVGNVTMdbPIBYC ', 297.03);
INSERT INTO public.products (id, name, price) VALUES (423, 'kbwktmLXEhKAVqbbgBOx', 395.35);
INSERT INTO public.products (id, name, price) VALUES (424, 'FPQetILG b', 541.28);
INSERT INTO public.products (id, name, price) VALUES (425, 'bFTaiXxBD', 753.05);
INSERT INTO public.products (id, name, price) VALUES (426, 'dhiqMZdJOK', 573.6);
INSERT INTO public.products (id, name, price) VALUES (427, 'CpslsSndneHzNoy', 499.26);
INSERT INTO public.products (id, name, price) VALUES (428, 'zrNjchzXNazt', 747.65);
INSERT INTO public.products (id, name, price) VALUES (429, 'LJGpltDobSsDuPDD', 645.88);
INSERT INTO public.products (id, name, price) VALUES (430, 'NYQRJADqjvjusA', 826.62);
INSERT INTO public.products (id, name, price) VALUES (431, 'UqwgslYaeFiwQgDWQBZ', 544.43);
INSERT INTO public.products (id, name, price) VALUES (432, 'EPUmAkrvguJHKenT', 821.19);
INSERT INTO public.products (id, name, price) VALUES (433, 'hAiOIbnqG', 618.31);
INSERT INTO public.products (id, name, price) VALUES (434, 'ZxbBFLasWAe', 204.38);
INSERT INTO public.products (id, name, price) VALUES (435, 'KN QvNfxslCLOGy', 643.99);
INSERT INTO public.products (id, name, price) VALUES (436, 'ccKdNBxoSVYAOKvDxfTU', 917.34);
INSERT INTO public.products (id, name, price) VALUES (437, 'rYJKKzICdmWnBByOy', 141.54);
INSERT INTO public.products (id, name, price) VALUES (438, 'OFuIIbmLtCphvQvmgtZ ', 890.21);
INSERT INTO public.products (id, name, price) VALUES (439, 'WFvKukOgqzhdaDtp', 963.79);
INSERT INTO public.products (id, name, price) VALUES (440, 'tZsjdJMnhdC', 936.17);
INSERT INTO public.products (id, name, price) VALUES (441, 'rybVrFbKgcHBIzC LV ', 537.69);
INSERT INTO public.products (id, name, price) VALUES (442, ' fawhaAchIJExP', 371.51);
INSERT INTO public.products (id, name, price) VALUES (443, 'qkcaeeqXKqi', 139.76);
INSERT INTO public.products (id, name, price) VALUES (444, 'FqpuOrrm jeraTlEY', 735.72);
INSERT INTO public.products (id, name, price) VALUES (445, 'IICfBvxdznpVX', 961.9);
INSERT INTO public.products (id, name, price) VALUES (446, 'bWJB jmsYanJewckRTM', 316.94);
INSERT INTO public.products (id, name, price) VALUES (447, 'AApcAGGtESarbqMkklP', 562.75);
INSERT INTO public.products (id, name, price) VALUES (448, 'kqmnVuz zR', 146.67);
INSERT INTO public.products (id, name, price) VALUES (449, 'DeeisfdUxAa', 794.21);
INSERT INTO public.products (id, name, price) VALUES (450, 'UZCaekeGtSENHH', 289.51);
INSERT INTO public.products (id, name, price) VALUES (451, 'krhXL Nw', 413.35);
INSERT INTO public.products (id, name, price) VALUES (452, 'PZpHRnpfwCpqUvWr', 110.17);
INSERT INTO public.products (id, name, price) VALUES (453, 'GhJLHhmvNCEpqGcuLYgw', 346.48);
INSERT INTO public.products (id, name, price) VALUES (454, 'IAxwOfaNQqIA', 681.49);
INSERT INTO public.products (id, name, price) VALUES (455, 'gnwBYiWLWdEj', 769.24);
INSERT INTO public.products (id, name, price) VALUES (456, 'IBjoA', 724.51);
INSERT INTO public.products (id, name, price) VALUES (457, 'FXYMtxBSxDEVF e', 790.84);
INSERT INTO public.products (id, name, price) VALUES (458, 'mDMBy', 734.29);
INSERT INTO public.products (id, name, price) VALUES (459, 'SwOEnHsx', 237.95);
INSERT INTO public.products (id, name, price) VALUES (460, 'Nlmf ndNmttnjbuztlA', 101.41);
INSERT INTO public.products (id, name, price) VALUES (461, 'YXCcKAFigXIO LbRCp', 481.29);
INSERT INTO public.products (id, name, price) VALUES (462, 'mzfwzUr hfNTXH Us', 611.38);
INSERT INTO public.products (id, name, price) VALUES (463, 'JfivZuitqekKZ', 432.13);
INSERT INTO public.products (id, name, price) VALUES (464, 'ZhTeVgRt', 916.68);
INSERT INTO public.products (id, name, price) VALUES (465, 'QFNoRbOt', 579.61);
INSERT INTO public.products (id, name, price) VALUES (466, 'zLxzwMbo ANPqRfN', 845.25);
INSERT INTO public.products (id, name, price) VALUES (467, 'BXyhlsuAyyhuNO', 638.19);
INSERT INTO public.products (id, name, price) VALUES (468, 'vRfoacGwuCR', 429.46);
INSERT INTO public.products (id, name, price) VALUES (469, 'VbfCxl', 461.27);
INSERT INTO public.products (id, name, price) VALUES (470, 'zTePjEmUbzPQPdduKuwN', 938.21);
INSERT INTO public.products (id, name, price) VALUES (471, 'Rsfj ONrwASehJaxwKd', 486.34);
INSERT INTO public.products (id, name, price) VALUES (472, 'FzGnKohZk', 767.3);
INSERT INTO public.products (id, name, price) VALUES (473, 'WoEBXaOQ', 814.35);
INSERT INTO public.products (id, name, price) VALUES (474, 'xWZPBLQX', 74.08);
INSERT INTO public.products (id, name, price) VALUES (475, 'ItPjcJojKNVH', 148.73);
INSERT INTO public.products (id, name, price) VALUES (476, 'vNslpRLFK', 415.63);
INSERT INTO public.products (id, name, price) VALUES (477, 'BwKDFxlzCIr ', 562.57);
INSERT INTO public.products (id, name, price) VALUES (478, 'pHIyQImyXdpjToZuu', 381.95);
INSERT INTO public.products (id, name, price) VALUES (479, 'EdjMCe', 498.21);
INSERT INTO public.products (id, name, price) VALUES (480, 'cJSBJyzzTmJuvuXLLYY', 722.54);
INSERT INTO public.products (id, name, price) VALUES (481, 'dCCjqx', 907.16);
INSERT INTO public.products (id, name, price) VALUES (482, 'MGbYISGiNHhH', 39.19);
INSERT INTO public.products (id, name, price) VALUES (483, 'nIgVpdALJDYvakCGkG', 292.89);
INSERT INTO public.products (id, name, price) VALUES (484, 'ERyZdxCP', 893.95);
INSERT INTO public.products (id, name, price) VALUES (485, 'vjuOXjSZ', 680.03);
INSERT INTO public.products (id, name, price) VALUES (486, 'qGaiszCjiIoTIYjWKWi ', 889.21);
INSERT INTO public.products (id, name, price) VALUES (487, 'ShxiztJuUoCvWQ', 552.52);
INSERT INTO public.products (id, name, price) VALUES (488, 'AclPKuUVwfAQdejMhTj', 86.6);
INSERT INTO public.products (id, name, price) VALUES (489, 'ouWrWsRAEqFt', 431.87);
INSERT INTO public.products (id, name, price) VALUES (490, 'RCICNgoZgrGeJUtUrQ', 336.49);
INSERT INTO public.products (id, name, price) VALUES (491, 'SwhcssYgJyIkmRuKVr', 314.42);
INSERT INTO public.products (id, name, price) VALUES (492, 'eIFDusWjLFHWyxnTZncl', 373.35);
INSERT INTO public.products (id, name, price) VALUES (493, 'stkCxBUAdDFYzege uW', 502.92);
INSERT INTO public.products (id, name, price) VALUES (494, 'ZtInTGdDQXbDgHulm', 16.43);
INSERT INTO public.products (id, name, price) VALUES (495, 'urQzvxLPZXpaAbdaJH', 338.28);
INSERT INTO public.products (id, name, price) VALUES (496, 'jCddzGoC', 283.37);
INSERT INTO public.products (id, name, price) VALUES (497, 'xgJVTLgfqCHe', 355.62);
INSERT INTO public.products (id, name, price) VALUES (498, 'djZLDlxYRtbCDp', 749.24);
INSERT INTO public.products (id, name, price) VALUES (499, 'sMpxLfITWWui', 839.11);
INSERT INTO public.products (id, name, price) VALUES (500, 'DldsH t', 550.81);
INSERT INTO public.products (id, name, price) VALUES (501, 'bzCDbpLVJBipKtL', 61.36);
INSERT INTO public.products (id, name, price) VALUES (502, 'lD SSAppvnnFdLvm', 114.27);
INSERT INTO public.products (id, name, price) VALUES (503, 'fhztBkrNFRKxED', 71.11);
INSERT INTO public.products (id, name, price) VALUES (504, 'hJCmdqY', 25.78);
INSERT INTO public.products (id, name, price) VALUES (505, 'trGNTrWnBo', 113.07);
INSERT INTO public.products (id, name, price) VALUES (506, 'bVByS', 974.88);
INSERT INTO public.products (id, name, price) VALUES (507, 'ZIrQoTxRwmyxO', 529.77);
INSERT INTO public.products (id, name, price) VALUES (508, 'lAUxAXusXu', 560.11);
INSERT INTO public.products (id, name, price) VALUES (509, 'kuCnmgmQM fRCEe', 761.73);
INSERT INTO public.products (id, name, price) VALUES (510, 'XdcqSAPzDWP', 209.92);
INSERT INTO public.products (id, name, price) VALUES (511, 'GsXga', 887.67);
INSERT INTO public.products (id, name, price) VALUES (512, 'tJeWy TEwuPTkA', 328.07);
INSERT INTO public.products (id, name, price) VALUES (513, 'SGAqbbtZSvhzfqTVSPR', 437.62);
INSERT INTO public.products (id, name, price) VALUES (514, 'IXdoqrOfqlZPtjxc', 830.96);
INSERT INTO public.products (id, name, price) VALUES (515, 'hAlcPA Ce cGbRRyug', 65.53);
INSERT INTO public.products (id, name, price) VALUES (516, 'HhbDRFBqOtIhXeN', 616.69);
INSERT INTO public.products (id, name, price) VALUES (517, 'KSlSGwDbIq', 214.3);
INSERT INTO public.products (id, name, price) VALUES (518, 'dhoyDKPZLQCmFZyCxllm', 945.05);
INSERT INTO public.products (id, name, price) VALUES (519, 'uQlgQXbIjqykDA', 824.24);
INSERT INTO public.products (id, name, price) VALUES (520, 'f tcTC XaEpJCIW', 220.32);
INSERT INTO public.products (id, name, price) VALUES (521, 'qBArdnqfg', 498.2);
INSERT INTO public.products (id, name, price) VALUES (522, 'aSncoaxV', 985.18);
INSERT INTO public.products (id, name, price) VALUES (523, 'xQuppTYV', 497.2);
INSERT INTO public.products (id, name, price) VALUES (524, 'bASSjZRpm', 330.42);
INSERT INTO public.products (id, name, price) VALUES (525, 'gKFZsDZGRmjqBHG', 216.96);
INSERT INTO public.products (id, name, price) VALUES (526, 'qGGWMShldeRB', 916.5);
INSERT INTO public.products (id, name, price) VALUES (527, 'HqWVC', 321.5);
INSERT INTO public.products (id, name, price) VALUES (528, 'ZvkwSqmTUOypGSMUbHLi', 118.54);
INSERT INTO public.products (id, name, price) VALUES (529, 'JTXuoZRomGK zkKl', 144.47);
INSERT INTO public.products (id, name, price) VALUES (530, 'fVFcXQCNPEWXIvkf Tjd', 915.54);
INSERT INTO public.products (id, name, price) VALUES (531, 'plfwwFOkfIdTv', 210.18);
INSERT INTO public.products (id, name, price) VALUES (532, 'BtsOWRa yr', 310.72);
INSERT INTO public.products (id, name, price) VALUES (533, 'HSsI CZ', 758.02);
INSERT INTO public.products (id, name, price) VALUES (534, 'dINhIXZwvAjMwI', 511.31);
INSERT INTO public.products (id, name, price) VALUES (535, 'plA muipth', 487.43);
INSERT INTO public.products (id, name, price) VALUES (536, 'cSLLDwCyQfH', 425.93);
INSERT INTO public.products (id, name, price) VALUES (537, 'raPnSKJWesfnuYTvoxA', 590.43);
INSERT INTO public.products (id, name, price) VALUES (538, 'CjCBZG XZgPhFNg', 146.69);
INSERT INTO public.products (id, name, price) VALUES (539, 'CJIxgYxVrRiFD', 122.15);
INSERT INTO public.products (id, name, price) VALUES (540, 'LEXhIKyxXJr k', 560.46);
INSERT INTO public.products (id, name, price) VALUES (541, 'rfLyngsEyUiE', 555.05);
INSERT INTO public.products (id, name, price) VALUES (542, 'OkKjpYHjjjyilphO a', 997.1);
INSERT INTO public.products (id, name, price) VALUES (543, 'RSBUWWVY FBzlrzh j', 113.91);
INSERT INTO public.products (id, name, price) VALUES (544, 'IcYqcvyEHQIW', 595.23);
INSERT INTO public.products (id, name, price) VALUES (545, ' UAHRqWSVIeMrCbgBTm', 774.71);
INSERT INTO public.products (id, name, price) VALUES (546, 'VtSSTDGKFPj', 788.09);
INSERT INTO public.products (id, name, price) VALUES (547, 'rTNNAptxqrlxxX', 873.89);
INSERT INTO public.products (id, name, price) VALUES (548, 'uOsiWkKnMVuzUmxfT', 349.08);
INSERT INTO public.products (id, name, price) VALUES (549, 'HVygAXhktTzRyLPYJcLs', 911.78);
INSERT INTO public.products (id, name, price) VALUES (550, 'siEbbLSfJKiJjLeDwz', 921.46);
INSERT INTO public.products (id, name, price) VALUES (551, 'pAsWhdyFi', 180.13);
INSERT INTO public.products (id, name, price) VALUES (552, 'pCpenGYcTuv Ionn', 105.15);
INSERT INTO public.products (id, name, price) VALUES (553, 'GTPsYBtnYkZnUkl', 955.75);
INSERT INTO public.products (id, name, price) VALUES (554, 'nOcpXDnYzSVpLPzaed', 162.53);
INSERT INTO public.products (id, name, price) VALUES (555, 'xRlkRFVpdiE NJGSYh ', 697.08);
INSERT INTO public.products (id, name, price) VALUES (556, 'HmcYyYKWvDeIGQFAFtD', 723.61);
INSERT INTO public.products (id, name, price) VALUES (557, 'hGddeGDqftbTGkyszH', 932.55);
INSERT INTO public.products (id, name, price) VALUES (558, 'PdHvozQzfxZ', 487.35);
INSERT INTO public.products (id, name, price) VALUES (559, 'dzCklfZK', 85.83);
INSERT INTO public.products (id, name, price) VALUES (560, 'mMTSzmpiF', 106.75);
INSERT INTO public.products (id, name, price) VALUES (561, 'pSuCtEwImogc', 21.8);
INSERT INTO public.products (id, name, price) VALUES (562, 'rDqkmbIxaw', 734.52);
INSERT INTO public.products (id, name, price) VALUES (563, 'bavhdkULQASZKxJJyAO', 428.45);
INSERT INTO public.products (id, name, price) VALUES (564, 'ZTDNeYpzTk zLz', 117.32);
INSERT INTO public.products (id, name, price) VALUES (565, 'EfvQrSfroPpsqrDoCjLc', 525.57);
INSERT INTO public.products (id, name, price) VALUES (566, 'eukII', 322.69);
INSERT INTO public.products (id, name, price) VALUES (567, 'gCRUIqWqNavrX', 752.94);
INSERT INTO public.products (id, name, price) VALUES (568, 'CltPTCxozkEux', 682.54);
INSERT INTO public.products (id, name, price) VALUES (569, ' kgMpl', 870.39);
INSERT INTO public.products (id, name, price) VALUES (570, 'sXFDdyPmKZdtfQvkmBl', 458.29);
INSERT INTO public.products (id, name, price) VALUES (571, 'BSCNYNZoBSkYFYkrbLR', 409.43);
INSERT INTO public.products (id, name, price) VALUES (572, 'MKgYHHjoP', 6.48);
INSERT INTO public.products (id, name, price) VALUES (573, 'sjySdv', 627.04);
INSERT INTO public.products (id, name, price) VALUES (574, 'fbOss', 131.24);
INSERT INTO public.products (id, name, price) VALUES (575, 'MNQFZbPHwlai', 690.68);
INSERT INTO public.products (id, name, price) VALUES (576, 'QLEMfvKzzqJLurHv', 738.15);
INSERT INTO public.products (id, name, price) VALUES (577, 'neOPlw', 769.26);
INSERT INTO public.products (id, name, price) VALUES (578, 'GhkVmP', 631.18);
INSERT INTO public.products (id, name, price) VALUES (579, 'skgovJKCur', 739.1);
INSERT INTO public.products (id, name, price) VALUES (580, 'tEQMpUopFgMyLCOXbaOs', 203.89);
INSERT INTO public.products (id, name, price) VALUES (581, 'a XdHwUylXqJWy', 781.38);
INSERT INTO public.products (id, name, price) VALUES (582, 'PnGxKtQ', 47.94);
INSERT INTO public.products (id, name, price) VALUES (583, 'BAGvj', 839.5);
INSERT INTO public.products (id, name, price) VALUES (584, 'zPCwSlIwGl LK', 804.88);
INSERT INTO public.products (id, name, price) VALUES (585, 'hdtUZ', 767.73);
INSERT INTO public.products (id, name, price) VALUES (586, 'RwIWengLfFL', 892.66);
INSERT INTO public.products (id, name, price) VALUES (587, 'PXgIoImeajtYywAn zvM', 587.08);
INSERT INTO public.products (id, name, price) VALUES (588, 'GTrGWhPzlBYl', 945.98);
INSERT INTO public.products (id, name, price) VALUES (589, 'tIRLhjSfFUzPkFbLhhd', 496.92);
INSERT INTO public.products (id, name, price) VALUES (590, 'PUfZSaxzBDtPvrI wgyq', 460.65);
INSERT INTO public.products (id, name, price) VALUES (591, 'OTspqFVJyokqMzoQMpC', 785.26);
INSERT INTO public.products (id, name, price) VALUES (592, 'YuEFL Gcbdr', 511.2);
INSERT INTO public.products (id, name, price) VALUES (593, 'kqtlAWXKKwgJdIBYNnQb', 330.8);
INSERT INTO public.products (id, name, price) VALUES (594, 'noKwNUYVrbdOelWTl', 867.37);
INSERT INTO public.products (id, name, price) VALUES (595, 'uVSYtypQLoJte', 941.59);
INSERT INTO public.products (id, name, price) VALUES (596, 'yuJdKPMszMXwlfsJCmMs', 961.13);
INSERT INTO public.products (id, name, price) VALUES (597, 'XtgygbjSLfyjUqAaqK', 28.2);
INSERT INTO public.products (id, name, price) VALUES (598, 'YVvcRFe', 933.13);
INSERT INTO public.products (id, name, price) VALUES (599, 'wgrFYOcFxbNNR', 635.08);
INSERT INTO public.products (id, name, price) VALUES (600, 'enZPhkqKKmlkcza', 34.89);
INSERT INTO public.products (id, name, price) VALUES (601, 'ZAyzyVMxMFWuWwZtCW', 949.06);
INSERT INTO public.products (id, name, price) VALUES (602, 'BJJKhhmRQgZxSZqDTJ', 614.99);
INSERT INTO public.products (id, name, price) VALUES (603, 'FaHKi', 215.26);
INSERT INTO public.products (id, name, price) VALUES (604, 'FxtXXpEICjuDhvyRTNF', 874.4);
INSERT INTO public.products (id, name, price) VALUES (605, 'EPRvpGGfyh', 190.41);
INSERT INTO public.products (id, name, price) VALUES (606, 'ESYaQtjI', 750.27);
INSERT INTO public.products (id, name, price) VALUES (607, 'pXM JZYuiGcPYU', 50.9);
INSERT INTO public.products (id, name, price) VALUES (608, 'CDYtCQGqy iDHAuLeIp', 694.54);
INSERT INTO public.products (id, name, price) VALUES (609, 'NLmMHwCObSGkgMzhBo', 782.57);
INSERT INTO public.products (id, name, price) VALUES (610, 'CeAduIczqlPFl', 403.23);
INSERT INTO public.products (id, name, price) VALUES (611, 'nOnhHIFYrdBgXHlEge', 724.66);
INSERT INTO public.products (id, name, price) VALUES (612, 'AeogTQh', 847.07);
INSERT INTO public.products (id, name, price) VALUES (613, 'U AVZ', 463.13);
INSERT INTO public.products (id, name, price) VALUES (614, 'uiDUWJJuaAiI', 30.33);
INSERT INTO public.products (id, name, price) VALUES (615, 'JgUzCM', 772.28);
INSERT INTO public.products (id, name, price) VALUES (616, 'SWEZcsM', 573.81);
INSERT INTO public.products (id, name, price) VALUES (617, 'rZXFlVkgTjAlOhtq', 71.43);
INSERT INTO public.products (id, name, price) VALUES (618, 'meryUf sBa LQghQHyzD', 833.43);
INSERT INTO public.products (id, name, price) VALUES (619, 'mwpfzMUwJgPEMkZCiy', 307.26);
INSERT INTO public.products (id, name, price) VALUES (620, 'MiIpFf', 264.05);
INSERT INTO public.products (id, name, price) VALUES (621, 'qHgOYxvwOCeMEHAW', 398.4);
INSERT INTO public.products (id, name, price) VALUES (622, 'COKDFYDu', 695.9);
INSERT INTO public.products (id, name, price) VALUES (623, 'XzHbMiLjSqoBHHxygL', 65.41);
INSERT INTO public.products (id, name, price) VALUES (624, 'fhPXZvQu rYiU Xw', 782.18);
INSERT INTO public.products (id, name, price) VALUES (625, 'OslUbEhjO', 836.08);
INSERT INTO public.products (id, name, price) VALUES (626, 'vvTjP g', 987.76);
INSERT INTO public.products (id, name, price) VALUES (627, 'cR VMfWsM', 986.25);
INSERT INTO public.products (id, name, price) VALUES (628, 'xMLdNbCNmY', 413.21);
INSERT INTO public.products (id, name, price) VALUES (629, 'EmaZs', 404.54);
INSERT INTO public.products (id, name, price) VALUES (630, 'PKYaR', 437.24);
INSERT INTO public.products (id, name, price) VALUES (631, 'iMtjnjarEZjc', 788.93);
INSERT INTO public.products (id, name, price) VALUES (632, 'hSGEiOZymaaF', 500.76);
INSERT INTO public.products (id, name, price) VALUES (633, 'UZGhfbjOWRCR ', 9);
INSERT INTO public.products (id, name, price) VALUES (634, 'PYRPtadmKLYtnA', 589.13);
INSERT INTO public.products (id, name, price) VALUES (635, 'IqzQtgu', 953.91);
INSERT INTO public.products (id, name, price) VALUES (636, 'TcGOowaPVu', 643.58);
INSERT INTO public.products (id, name, price) VALUES (637, 'LqCviMdtuTwN', 144.37);
INSERT INTO public.products (id, name, price) VALUES (638, 'jqvvroeUsY m', 896.55);
INSERT INTO public.products (id, name, price) VALUES (639, 'oWWep', 614.15);
INSERT INTO public.products (id, name, price) VALUES (640, 'MIM NdSASbK', 754.26);
INSERT INTO public.products (id, name, price) VALUES (641, 'bglu reDaQUIhq', 570.04);
INSERT INTO public.products (id, name, price) VALUES (642, 'iHswjokfyvfyIW', 929.61);
INSERT INTO public.products (id, name, price) VALUES (643, 'KYlpL', 730.48);
INSERT INTO public.products (id, name, price) VALUES (644, 'rBXNxD', 348.78);
INSERT INTO public.products (id, name, price) VALUES (645, 'EEATZrcRKhVgpfjIe', 805.45);
INSERT INTO public.products (id, name, price) VALUES (646, 'Xp xsaLslHlhm', 493.03);
INSERT INTO public.products (id, name, price) VALUES (647, 'AZbHex', 196.28);
INSERT INTO public.products (id, name, price) VALUES (648, 'dKaSaLZSH', 746.39);
INSERT INTO public.products (id, name, price) VALUES (649, 'dhGIvMO', 995.14);
INSERT INTO public.products (id, name, price) VALUES (650, 'OmAygVTaXveAhZBQgyH', 915.96);
INSERT INTO public.products (id, name, price) VALUES (651, 'SSdKu', 419.2);
INSERT INTO public.products (id, name, price) VALUES (652, 'RHHGl', 971.44);
INSERT INTO public.products (id, name, price) VALUES (653, 'rtrhcFIsBD', 769.51);
INSERT INTO public.products (id, name, price) VALUES (654, 'MaqypdSTGkDXneqW', 162.4);
INSERT INTO public.products (id, name, price) VALUES (655, 'tiCutIxlzbClCEfHr', 783.49);
INSERT INTO public.products (id, name, price) VALUES (656, 'NxlPjAcVOhsRwLCiL', 727.22);
INSERT INTO public.products (id, name, price) VALUES (657, 'YwlkkHgbzYpUDDrutzX', 73.39);
INSERT INTO public.products (id, name, price) VALUES (658, 'GZqQVrzarNNSLdqJMSo', 847.33);
INSERT INTO public.products (id, name, price) VALUES (659, 'ClVymAljseDZDY', 80.28);
INSERT INTO public.products (id, name, price) VALUES (660, 'iXOlWpeWwGxITNloEq', 808.79);
INSERT INTO public.products (id, name, price) VALUES (661, 'VaebgxTimFdhphacRP', 991.89);
INSERT INTO public.products (id, name, price) VALUES (662, 'drDrGDeYkWmEkmcpkJ', 298.7);
INSERT INTO public.products (id, name, price) VALUES (663, 'chmYjG', 340.98);
INSERT INTO public.products (id, name, price) VALUES (664, 'nJjwevrrMZIYTJOgsCP', 758.56);
INSERT INTO public.products (id, name, price) VALUES (665, 'PQpKnwzQBwQAQpiAGHm', 121.64);
INSERT INTO public.products (id, name, price) VALUES (666, 'cIXxtC', 125.49);
INSERT INTO public.products (id, name, price) VALUES (667, 'PWDZGxLxmTDxZpwYoySL', 625.49);
INSERT INTO public.products (id, name, price) VALUES (668, 'pWXBFblxYkBpbTfvEjy', 714.98);
INSERT INTO public.products (id, name, price) VALUES (669, 'vklFmMN', 860.58);
INSERT INTO public.products (id, name, price) VALUES (670, 'xuurE  Ybig', 189.61);
INSERT INTO public.products (id, name, price) VALUES (671, 'iBNIlD', 738.17);
INSERT INTO public.products (id, name, price) VALUES (672, 'ynbQS', 921.02);
INSERT INTO public.products (id, name, price) VALUES (673, 'WfuhIKezjOPM', 544.89);
INSERT INTO public.products (id, name, price) VALUES (674, 'ykiFjwRbAEOFJ', 520.69);
INSERT INTO public.products (id, name, price) VALUES (675, 'ialGcNQGQVvl', 466.01);
INSERT INTO public.products (id, name, price) VALUES (676, 'RwAsY', 513.77);
INSERT INTO public.products (id, name, price) VALUES (677, 'AGheGXdzPipdS', 734.37);
INSERT INTO public.products (id, name, price) VALUES (678, 'IDW  WIXOjlMRM NZa', 751.77);
INSERT INTO public.products (id, name, price) VALUES (679, 'evPoiIZc', 425.25);
INSERT INTO public.products (id, name, price) VALUES (680, 'BEEeruZhTq Tjf', 337.36);
INSERT INTO public.products (id, name, price) VALUES (681, 'uTKXJzUJZekQs', 190.82);
INSERT INTO public.products (id, name, price) VALUES (682, 'xgJPrrHAMzr', 284.86);
INSERT INTO public.products (id, name, price) VALUES (683, 'ElxgmBAokZOFesvLEa', 578.76);
INSERT INTO public.products (id, name, price) VALUES (684, 'JJHReAACAcJRCAGyMu', 536.96);
INSERT INTO public.products (id, name, price) VALUES (685, 'wDlDMYAvGQWKDcLgvD', 892.32);
INSERT INTO public.products (id, name, price) VALUES (686, 'JEWQfluUjNdPPA', 37.31);
INSERT INTO public.products (id, name, price) VALUES (687, 'XkmBGrMGmdY', 431.65);
INSERT INTO public.products (id, name, price) VALUES (688, 'UiYhdRsmMZARAZDQeT', 763.28);
INSERT INTO public.products (id, name, price) VALUES (689, 'SPqrpdOxOH', 552.4);
INSERT INTO public.products (id, name, price) VALUES (690, 'WPHTRxVDnI', 424.6);
INSERT INTO public.products (id, name, price) VALUES (691, 'LNjaBcloNbbLtn', 580.9);
INSERT INTO public.products (id, name, price) VALUES (692, 'egKJsMqIj M', 822.45);
INSERT INTO public.products (id, name, price) VALUES (693, 'lPgZP', 317.58);
INSERT INTO public.products (id, name, price) VALUES (694, 'ryuJNmFnCZEfhw', 989.15);
INSERT INTO public.products (id, name, price) VALUES (695, 'CkEm OdTU', 320.9);
INSERT INTO public.products (id, name, price) VALUES (696, 'eQQFhBWmqAaxMmOYlM', 185.56);
INSERT INTO public.products (id, name, price) VALUES (697, 'rZSIajp', 884.88);
INSERT INTO public.products (id, name, price) VALUES (698, 'ePEPIOHDIuVyI', 238.64);
INSERT INTO public.products (id, name, price) VALUES (699, 'aKPrFptBdRPZm', 634.54);
INSERT INTO public.products (id, name, price) VALUES (700, 'sSOyGVTSYKYSRLcy', 55.85);
INSERT INTO public.products (id, name, price) VALUES (701, 'ILgzUIWcUbUprpwBJi', 987.03);
INSERT INTO public.products (id, name, price) VALUES (702, 'XgPpJSpjOpW Rnz', 711.94);
INSERT INTO public.products (id, name, price) VALUES (703, 'MZrfPEXwk', 434.59);
INSERT INTO public.products (id, name, price) VALUES (704, 'EJdzLBhdooHYrAha dfD', 586.92);
INSERT INTO public.products (id, name, price) VALUES (705, 'wGdcLJDaHL NWiHrPT', 974.31);
INSERT INTO public.products (id, name, price) VALUES (706, 'fYTUNAAjsy', 257.52);
INSERT INTO public.products (id, name, price) VALUES (707, 'mRmKdYt  MPhVpWBjv', 524.22);
INSERT INTO public.products (id, name, price) VALUES (708, 'YHQBRSLFTwTtUcqHAEp', 881.91);
INSERT INTO public.products (id, name, price) VALUES (709, 'mmXUxwkmUydsdWqSdr', 18.58);
INSERT INTO public.products (id, name, price) VALUES (710, 'AQIAijQAoak', 29.92);
INSERT INTO public.products (id, name, price) VALUES (711, 'FdRvsWhWDCOSjCmhITf', 42.26);
INSERT INTO public.products (id, name, price) VALUES (712, 'JBIQXKzTs', 315.95);
INSERT INTO public.products (id, name, price) VALUES (713, 'genReevSWXFCjovbOjwh', 282.25);
INSERT INTO public.products (id, name, price) VALUES (714, 'nunHEaoLomkmRPBTP', 708.9);
INSERT INTO public.products (id, name, price) VALUES (715, 'SikeeTz', 239.47);
INSERT INTO public.products (id, name, price) VALUES (716, 'G QbmAlmlrXhGBSFu', 980.19);
INSERT INTO public.products (id, name, price) VALUES (717, 'jwyLuTBX', 531.53);
INSERT INTO public.products (id, name, price) VALUES (718, 'kNGGGhsn', 826.57);
INSERT INTO public.products (id, name, price) VALUES (719, 'WoWVUAt', 448.03);
INSERT INTO public.products (id, name, price) VALUES (720, 'pHsriwwu', 488.9);
INSERT INTO public.products (id, name, price) VALUES (721, 'bwTxamCtKADKXtdGFGEd', 45.9);
INSERT INTO public.products (id, name, price) VALUES (722, 'QYqZWXzJavpmXI', 478.07);
INSERT INTO public.products (id, name, price) VALUES (723, 'due dK', 879.99);
INSERT INTO public.products (id, name, price) VALUES (724, 'EYEPQpGyttbJUWdICPZ', 679.55);
INSERT INTO public.products (id, name, price) VALUES (725, 'vyhzlTAJrkuQf', 290.04);
INSERT INTO public.products (id, name, price) VALUES (726, 'nDsBRptjsOMFGCF', 848.09);
INSERT INTO public.products (id, name, price) VALUES (727, 'MxlrFuhXKbjF', 31.3);
INSERT INTO public.products (id, name, price) VALUES (728, 'iUASaDPMxAyFg', 146.55);
INSERT INTO public.products (id, name, price) VALUES (729, 'KocUbxJFkzfaWsv', 735.75);
INSERT INTO public.products (id, name, price) VALUES (730, 'eMeqN', 899.14);
INSERT INTO public.products (id, name, price) VALUES (731, 'snTFjqbgFnVOSnXJ', 657.93);
INSERT INTO public.products (id, name, price) VALUES (732, 'TVhn JOq', 110.89);
INSERT INTO public.products (id, name, price) VALUES (733, 'brr pyOec', 977.99);
INSERT INTO public.products (id, name, price) VALUES (734, 'yXFWYNkU', 66.44);
INSERT INTO public.products (id, name, price) VALUES (735, 'lyFXYvtLnkvakYCjVWkG', 752.53);
INSERT INTO public.products (id, name, price) VALUES (736, 'UrsbemBWAuwdArPDxB', 787.24);
INSERT INTO public.products (id, name, price) VALUES (737, 'pSVRFBDShOQJdmO', 635.35);
INSERT INTO public.products (id, name, price) VALUES (738, 'qbGeODj', 695.25);
INSERT INTO public.products (id, name, price) VALUES (739, 'zIDVzK tzOvc', 192.81);
INSERT INTO public.products (id, name, price) VALUES (740, 'MsUreO tvHrQDZf', 790.07);
INSERT INTO public.products (id, name, price) VALUES (741, 'JLhTQvcfTMXikqVn', 482.6);
INSERT INTO public.products (id, name, price) VALUES (742, 'tVZWI', 781.77);
INSERT INTO public.products (id, name, price) VALUES (743, 'dAozBaEWTvF', 108.39);
INSERT INTO public.products (id, name, price) VALUES (744, ' ZAsAzOqzXbDRyP ZIz', 465.36);
INSERT INTO public.products (id, name, price) VALUES (745, 'AXfidWVQWyGUDNBE', 962.64);
INSERT INTO public.products (id, name, price) VALUES (746, 'yCLwlM', 167.39);
INSERT INTO public.products (id, name, price) VALUES (747, 'uFsMbbUyTcwAhNz', 107.4);
INSERT INTO public.products (id, name, price) VALUES (748, 'ydXYtggBAdsGnzLl', 570.41);
INSERT INTO public.products (id, name, price) VALUES (749, 'pfoSZpztlDnqWtdh', 982.88);
INSERT INTO public.products (id, name, price) VALUES (750, 'lRrNZoqVDerLXwGJdkN', 806.23);
INSERT INTO public.products (id, name, price) VALUES (751, 'QWVyPNROEFdzg', 818.35);
INSERT INTO public.products (id, name, price) VALUES (752, 'KdbEaJkZVGSWvxzva', 140.26);
INSERT INTO public.products (id, name, price) VALUES (753, 'jmFLKKAZhbL', 697.19);
INSERT INTO public.products (id, name, price) VALUES (754, 'PCYskXtifsVXneRFS', 85.03);
INSERT INTO public.products (id, name, price) VALUES (755, 'wUNlQeOLnvmsUp lNw', 784.98);
INSERT INTO public.products (id, name, price) VALUES (756, 'LjTer', 462.04);
INSERT INTO public.products (id, name, price) VALUES (757, 'PBhrABmvH', 165.65);
INSERT INTO public.products (id, name, price) VALUES (758, 'SQgdiHJBzVnkk', 193.57);
INSERT INTO public.products (id, name, price) VALUES (759, 'QvADcJINDZfbcIzZf', 262.69);
INSERT INTO public.products (id, name, price) VALUES (760, 'fFuxLqDLUcZFAJ', 299.11);
INSERT INTO public.products (id, name, price) VALUES (761, 'PUTZJPppSMA', 82.55);
INSERT INTO public.products (id, name, price) VALUES (762, 'BBIrdbqSWIibxHDsXSfV', 826.07);
INSERT INTO public.products (id, name, price) VALUES (763, 'PVufAiYOxYh Si', 428.77);
INSERT INTO public.products (id, name, price) VALUES (764, 'bAeiKpGPw', 978.29);
INSERT INTO public.products (id, name, price) VALUES (765, 'HaSTuctjw', 521.91);
INSERT INTO public.products (id, name, price) VALUES (766, 'zKHrtcSwCXMNFhnrN', 986.43);
INSERT INTO public.products (id, name, price) VALUES (767, 'XlZ KZTVsgtcOzLqq', 728.98);
INSERT INTO public.products (id, name, price) VALUES (768, 'dhdeZivYkISwyN w', 292.7);
INSERT INTO public.products (id, name, price) VALUES (769, 'pneLNrVDg', 285.44);
INSERT INTO public.products (id, name, price) VALUES (770, 'BlVvBhCXKI', 771.28);
INSERT INTO public.products (id, name, price) VALUES (771, 'upezjjW', 240.95);
INSERT INTO public.products (id, name, price) VALUES (772, 'GEPEAtjEFV', 779.55);
INSERT INTO public.products (id, name, price) VALUES (773, 'yLtSfnhziDgk', 309.56);
INSERT INTO public.products (id, name, price) VALUES (774, 'XbRjxH', 263.95);
INSERT INTO public.products (id, name, price) VALUES (775, 'AqGnbHPPgNwck', 111.13);
INSERT INTO public.products (id, name, price) VALUES (776, 'QmVOdu okTP', 823.82);
INSERT INTO public.products (id, name, price) VALUES (777, ' lKXJSsKHMQlPgiA', 547.57);
INSERT INTO public.products (id, name, price) VALUES (778, 'fvqIqeRuJmZ', 691.13);
INSERT INTO public.products (id, name, price) VALUES (779, 'IiqBgTKZ', 618.79);
INSERT INTO public.products (id, name, price) VALUES (780, '  zGNLp JR', 963.47);
INSERT INTO public.products (id, name, price) VALUES (781, 'wBCDhLffpqhIg', 700.51);
INSERT INTO public.products (id, name, price) VALUES (782, 'ejQbjZQJveWQGscU', 40.39);
INSERT INTO public.products (id, name, price) VALUES (783, 'XwqxL', 965.15);
INSERT INTO public.products (id, name, price) VALUES (784, 'DopAsNXvFrFdfBFWK', 853.52);
INSERT INTO public.products (id, name, price) VALUES (785, 'wfPqZQrvP', 508.09);
INSERT INTO public.products (id, name, price) VALUES (786, 'HuxJfSEgPjcbTpLeA', 145.94);
INSERT INTO public.products (id, name, price) VALUES (787, 'yAjnvUQAPN Yd', 865.92);
INSERT INTO public.products (id, name, price) VALUES (788, 'BrfPBUcWG cyGr', 152.02);
INSERT INTO public.products (id, name, price) VALUES (789, 'jtlKOQTsMRiJ', 52.07);
INSERT INTO public.products (id, name, price) VALUES (790, 'wVBja GXBejunFXS', 917.71);
INSERT INTO public.products (id, name, price) VALUES (791, 'VzSnLYFWEtjEsjwTwJf', 997.78);
INSERT INTO public.products (id, name, price) VALUES (792, 'epDcmdFNLMHCyphvw', 150.72);
INSERT INTO public.products (id, name, price) VALUES (793, 'drOWVKT Ga', 57.94);
INSERT INTO public.products (id, name, price) VALUES (794, 'EQdZIuGgvwzeZVHEj', 413.4);
INSERT INTO public.products (id, name, price) VALUES (795, 'OmAqFMlMA', 292.08);
INSERT INTO public.products (id, name, price) VALUES (796, 'TrFBegiwHm', 951.6);
INSERT INTO public.products (id, name, price) VALUES (797, 'ztPnJBZi', 893.58);
INSERT INTO public.products (id, name, price) VALUES (798, 'qkHyaSGCLrWZ', 932.47);
INSERT INTO public.products (id, name, price) VALUES (799, 'JaBcsrrnaIIlRyNtFZ', 276.95);
INSERT INTO public.products (id, name, price) VALUES (800, 'udWIzgPQEZowcRz', 887.47);
INSERT INTO public.products (id, name, price) VALUES (801, 'KcqA cyReXBwakCyIt ', 94.7);
INSERT INTO public.products (id, name, price) VALUES (802, 'DuGAXSOqsM', 449.91);
INSERT INTO public.products (id, name, price) VALUES (803, 'vtFIDpW', 770.71);
INSERT INTO public.products (id, name, price) VALUES (804, 'JkphCYjJYkQrvGQOQ', 111.61);
INSERT INTO public.products (id, name, price) VALUES (805, 'yklbH', 566.9);
INSERT INTO public.products (id, name, price) VALUES (806, 'ljshNEtiXsAxnP hrSY', 366.89);
INSERT INTO public.products (id, name, price) VALUES (807, 'noVoiqGRyJu', 968.79);
INSERT INTO public.products (id, name, price) VALUES (808, 'uNAJEQSti', 549.04);
INSERT INTO public.products (id, name, price) VALUES (809, 'VjETao', 150.97);
INSERT INTO public.products (id, name, price) VALUES (810, 'ihXkwVY', 668.46);
INSERT INTO public.products (id, name, price) VALUES (811, 'MfxhUx', 51.63);
INSERT INTO public.products (id, name, price) VALUES (812, 'tOwGb eHsulKb', 122.44);
INSERT INTO public.products (id, name, price) VALUES (813, 'ODdVt', 257.63);
INSERT INTO public.products (id, name, price) VALUES (814, 'OyQckS', 899.61);
INSERT INTO public.products (id, name, price) VALUES (815, 'BXSxSeWU', 381.87);
INSERT INTO public.products (id, name, price) VALUES (816, 'yBnKBIovvQrVDv', 510.34);
INSERT INTO public.products (id, name, price) VALUES (817, 'gUWhoISdqQl', 791.26);
INSERT INTO public.products (id, name, price) VALUES (818, 'VR FJwTZKU', 758.46);
INSERT INTO public.products (id, name, price) VALUES (819, 'CQrXSSvDKycwHyWlf', 755.51);
INSERT INTO public.products (id, name, price) VALUES (820, 'XTRnYxDDYlkDDdI', 810.3);
INSERT INTO public.products (id, name, price) VALUES (821, 'hHEXR', 286);
INSERT INTO public.products (id, name, price) VALUES (822, 'Ojiqsa', 824.25);
INSERT INTO public.products (id, name, price) VALUES (823, 'XuaRZTaTVamCragbIf', 414.64);
INSERT INTO public.products (id, name, price) VALUES (824, 'JmGQ ', 283.21);
INSERT INTO public.products (id, name, price) VALUES (825, 'azJkMzSGoHFHZVSTAob', 423.11);
INSERT INTO public.products (id, name, price) VALUES (826, 'bTZBxEYBVRy', 157.41);
INSERT INTO public.products (id, name, price) VALUES (827, 'tzuJnL', 396.85);
INSERT INTO public.products (id, name, price) VALUES (828, 'VzxXWrmxTiotGH', 930.71);
INSERT INTO public.products (id, name, price) VALUES (829, 'QysTGmHCvzu qUwFyxo', 509.65);
INSERT INTO public.products (id, name, price) VALUES (830, 'MzU tTYr', 497.46);
INSERT INTO public.products (id, name, price) VALUES (831, 'VKDzrHOWIVE', 227.47);
INSERT INTO public.products (id, name, price) VALUES (832, 'iZBoEdINhnBe TiZJUI', 925.21);
INSERT INTO public.products (id, name, price) VALUES (833, 'mfyjLdScWvWpncb', 597.5);
INSERT INTO public.products (id, name, price) VALUES (834, 'AmjZVxf atB', 177.46);
INSERT INTO public.products (id, name, price) VALUES (835, 'hlV fPXylxDBpjJyyGO', 485.42);
INSERT INTO public.products (id, name, price) VALUES (836, 'kiXIPnSVFNws', 820.05);
INSERT INTO public.products (id, name, price) VALUES (837, 'ONkhIBuNcCXeDw', 902.74);
INSERT INTO public.products (id, name, price) VALUES (838, 'etxzrOrM', 723.34);
INSERT INTO public.products (id, name, price) VALUES (839, 'meqbDjZfy', 801.96);
INSERT INTO public.products (id, name, price) VALUES (840, 'urPpJAd PpuIV', 376.96);
INSERT INTO public.products (id, name, price) VALUES (841, 'FzLkJoXvbNOwHstN', 318.76);
INSERT INTO public.products (id, name, price) VALUES (842, 'VuZjfEXd LBD', 952.79);
INSERT INTO public.products (id, name, price) VALUES (843, 'UjPaVXllxQmuKtip', 805.93);
INSERT INTO public.products (id, name, price) VALUES (844, 'BFNqIvGUS hc', 449.51);
INSERT INTO public.products (id, name, price) VALUES (845, 'LiBWcGEpwrKTH', 479.83);
INSERT INTO public.products (id, name, price) VALUES (846, 'DCynoORyETVV dprbYsG', 895.13);
INSERT INTO public.products (id, name, price) VALUES (847, 'cLfGeY', 299.77);
INSERT INTO public.products (id, name, price) VALUES (848, 'jPxYkXuBEfqAPLIeglya', 89.89);
INSERT INTO public.products (id, name, price) VALUES (849, 'hbnGw', 24.38);
INSERT INTO public.products (id, name, price) VALUES (850, 'TVln  ktjZ', 355.41);
INSERT INTO public.products (id, name, price) VALUES (851, 'yimfWLvoJLexmwRKH', 804.82);
INSERT INTO public.products (id, name, price) VALUES (852, 'uVsbIl', 58.07);
INSERT INTO public.products (id, name, price) VALUES (853, 'XRguA', 142.51);
INSERT INTO public.products (id, name, price) VALUES (854, 'DEJGDETu XnxkJ', 379.16);
INSERT INTO public.products (id, name, price) VALUES (855, 'zJNGzUuRxQpJjiPTsAI', 149.03);
INSERT INTO public.products (id, name, price) VALUES (856, 'tokKyFXC', 314.32);
INSERT INTO public.products (id, name, price) VALUES (857, 'TOYGpYTTZGoOBcAoEri', 478.7);
INSERT INTO public.products (id, name, price) VALUES (858, 'EYFLremzFNsxSiICuPV', 112.7);
INSERT INTO public.products (id, name, price) VALUES (859, 'HYpXJZKQPStOp', 107.29);
INSERT INTO public.products (id, name, price) VALUES (860, 'jfpwgDJTfhMWcuVzwWP', 856.05);
INSERT INTO public.products (id, name, price) VALUES (861, 'FCKuFOavBNkKlzAbHUQa', 116.98);
INSERT INTO public.products (id, name, price) VALUES (862, 'GhmScrATFM', 938.09);
INSERT INTO public.products (id, name, price) VALUES (863, 'mznSdgzBzvezdrXPRWF', 928.35);
INSERT INTO public.products (id, name, price) VALUES (864, 'UOQlhUpTnGELuJZ', 911.6);
INSERT INTO public.products (id, name, price) VALUES (865, 'gYX qmNBrxK', 915.26);
INSERT INTO public.products (id, name, price) VALUES (866, 'irHqvtMRxCJRhTOvsf', 625.36);
INSERT INTO public.products (id, name, price) VALUES (867, 'oWtSALihiPtprV', 617.81);
INSERT INTO public.products (id, name, price) VALUES (868, 'qeJSkgkjUwJfcLCl', 816.95);
INSERT INTO public.products (id, name, price) VALUES (869, 'GEjtvnDPogHyY', 40.56);
INSERT INTO public.products (id, name, price) VALUES (870, 'dkKVGVbXYg', 364.39);
INSERT INTO public.products (id, name, price) VALUES (871, 'eAHxjtZcFKyBfR', 55.19);
INSERT INTO public.products (id, name, price) VALUES (872, 'KmfGcdOiAa', 125.44);
INSERT INTO public.products (id, name, price) VALUES (873, 'WWYMNZyR', 133.96);
INSERT INTO public.products (id, name, price) VALUES (874, 'ahArjUPcrj', 772.99);
INSERT INTO public.products (id, name, price) VALUES (875, 'SosrAuNucdnaHH', 237.99);
INSERT INTO public.products (id, name, price) VALUES (876, 'JyGajof', 818.87);
INSERT INTO public.products (id, name, price) VALUES (877, 'uwbCdbqXIKoBgLXsHb', 981.77);
INSERT INTO public.products (id, name, price) VALUES (878, 'PzqEIOYDuubTjPTNE', 919.08);
INSERT INTO public.products (id, name, price) VALUES (879, 'csUfkRQkyGAvzRgTKWXd', 747.7);
INSERT INTO public.products (id, name, price) VALUES (880, 'URVuTUJnLdZxkh ', 485.02);
INSERT INTO public.products (id, name, price) VALUES (881, 'eiXLsypagUfsH', 94.99);
INSERT INTO public.products (id, name, price) VALUES (882, 'tGJWdKE', 15.03);
INSERT INTO public.products (id, name, price) VALUES (883, 'psoBDRpHI', 775.72);
INSERT INTO public.products (id, name, price) VALUES (884, 'ASnqGHkSL', 535.82);
INSERT INTO public.products (id, name, price) VALUES (885, 'GEImTCpoIQSKWigjTAI', 861.56);
INSERT INTO public.products (id, name, price) VALUES (886, 'oASRlRQrXwaRj', 422.83);
INSERT INTO public.products (id, name, price) VALUES (887, 'Z acmKO', 904.95);
INSERT INTO public.products (id, name, price) VALUES (888, 'QkXxGLhudgzJDuSw ZC', 902.16);
INSERT INTO public.products (id, name, price) VALUES (889, 'UfYDMdHuOB', 214.51);
INSERT INTO public.products (id, name, price) VALUES (890, 'qKnrhlhNciYWJzaUt', 38.73);
INSERT INTO public.products (id, name, price) VALUES (891, 'wNHbDN', 356.58);
INSERT INTO public.products (id, name, price) VALUES (892, 'SXFWZuUPAruRH', 285.02);
INSERT INTO public.products (id, name, price) VALUES (893, 'vPidAvtVhzGqOquHviC', 898.68);
INSERT INTO public.products (id, name, price) VALUES (894, 'ZiJhTbbL', 982.36);
INSERT INTO public.products (id, name, price) VALUES (895, 'peEPlZX', 963.16);
INSERT INTO public.products (id, name, price) VALUES (896, 'vHZz o', 915.94);
INSERT INTO public.products (id, name, price) VALUES (897, 'uMjUBbD', 723.73);
INSERT INTO public.products (id, name, price) VALUES (898, 'eGIkafSedSVJoim', 850.77);
INSERT INTO public.products (id, name, price) VALUES (899, 'VnOvZnZmDHShGyRw', 168.71);
INSERT INTO public.products (id, name, price) VALUES (900, 'PmrQuMZiUAH', 810.1);
INSERT INTO public.products (id, name, price) VALUES (901, 'onMOFonFJCJZtTYmu', 451.7);
INSERT INTO public.products (id, name, price) VALUES (902, 'gWhhlVfrFd', 251.68);
INSERT INTO public.products (id, name, price) VALUES (903, 'ubz qG', 905.98);
INSERT INTO public.products (id, name, price) VALUES (904, 'PrvL bw', 464.1);
INSERT INTO public.products (id, name, price) VALUES (905, 'DGUJBSJrI', 961.57);
INSERT INTO public.products (id, name, price) VALUES (906, 'epquLuqylbsbJ', 762.46);
INSERT INTO public.products (id, name, price) VALUES (907, 'fGueFzNO', 498.83);
INSERT INTO public.products (id, name, price) VALUES (908, 'LbjMQ', 466.48);
INSERT INTO public.products (id, name, price) VALUES (909, 'EWmKKJ', 51.69);
INSERT INTO public.products (id, name, price) VALUES (910, 'cZgnJD yeXlfdljW', 567.6);
INSERT INTO public.products (id, name, price) VALUES (911, 'XIkf qpxXNwgiSfyKP', 653.66);
INSERT INTO public.products (id, name, price) VALUES (912, 'msSQWczYvAbCfO', 722.93);
INSERT INTO public.products (id, name, price) VALUES (913, 'viGyNWWlCIyFGYBUmIe', 716.89);
INSERT INTO public.products (id, name, price) VALUES (914, 'qVxpbGz', 146.66);
INSERT INTO public.products (id, name, price) VALUES (915, 'qITLmSwJRYQwuep', 18.11);
INSERT INTO public.products (id, name, price) VALUES (916, 'vkxvrxoiRtaauvDynkG', 340.33);
INSERT INTO public.products (id, name, price) VALUES (917, 'JxwCQn', 263.03);
INSERT INTO public.products (id, name, price) VALUES (918, 'JRaxjeKZtvLfE', 892.86);
INSERT INTO public.products (id, name, price) VALUES (919, 'nDsGAAWv', 563.67);
INSERT INTO public.products (id, name, price) VALUES (920, 'xRuxJptfUfmUQ', 234.2);
INSERT INTO public.products (id, name, price) VALUES (921, 'EYmDJINhsd JCzqDQKD', 908.26);
INSERT INTO public.products (id, name, price) VALUES (922, 'lVCSoBtfebFYZozFtDlV', 837.76);
INSERT INTO public.products (id, name, price) VALUES (923, 'GmsPrNIamloQihXI', 74.97);
INSERT INTO public.products (id, name, price) VALUES (924, 'NGCDqo', 604.01);
INSERT INTO public.products (id, name, price) VALUES (925, 'dxKvWIBXOROcy', 317.72);
INSERT INTO public.products (id, name, price) VALUES (926, 'jGBVqUfpWGCBOVy', 776.98);
INSERT INTO public.products (id, name, price) VALUES (927, 'FHKFHdCJmMxDTf', 671.65);
INSERT INTO public.products (id, name, price) VALUES (928, 'CcfSRg', 347.27);
INSERT INTO public.products (id, name, price) VALUES (929, 'AtDdXxeC OWeMjzQ', 307.89);
INSERT INTO public.products (id, name, price) VALUES (930, 'kWoLZgnhGjPWFHpTg', 592.6);
INSERT INTO public.products (id, name, price) VALUES (931, 'nKwjmaOgcdjoM', 565.89);
INSERT INTO public.products (id, name, price) VALUES (932, 'IKpuZAvYUBk', 590.16);
INSERT INTO public.products (id, name, price) VALUES (933, 'ZQhF XxzfvEfmFdQNI', 6.25);
INSERT INTO public.products (id, name, price) VALUES (934, 'lGWqsVqz', 20.55);
INSERT INTO public.products (id, name, price) VALUES (935, 'zkSme', 368.46);
INSERT INTO public.products (id, name, price) VALUES (936, 'pxsnZWFtESMMgXRnvF', 992.99);
INSERT INTO public.products (id, name, price) VALUES (937, 'KMYsVmLPXUN', 839.2);
INSERT INTO public.products (id, name, price) VALUES (938, 'AlaGW', 986.67);
INSERT INTO public.products (id, name, price) VALUES (939, 'IWqpZynfXPL', 619.71);
INSERT INTO public.products (id, name, price) VALUES (940, 'ucIfmrcqDhJ', 618.52);
INSERT INTO public.products (id, name, price) VALUES (941, 'tTuHsRcjLVhG', 707.68);
INSERT INTO public.products (id, name, price) VALUES (942, 'OfRtebk rsmwvqjT', 935.01);
INSERT INTO public.products (id, name, price) VALUES (943, 'GHtbr ', 922.64);
INSERT INTO public.products (id, name, price) VALUES (944, 'ChrjWjSCZ', 532.45);
INSERT INTO public.products (id, name, price) VALUES (945, 'QIF ZXrzMWuvxbnr', 299.56);
INSERT INTO public.products (id, name, price) VALUES (946, 'HheGgajuiAuOw WEGszN', 525.57);
INSERT INTO public.products (id, name, price) VALUES (947, 'p lPks', 819.06);
INSERT INTO public.products (id, name, price) VALUES (948, 'aHTkZBprxYTCrXKNok', 792.66);
INSERT INTO public.products (id, name, price) VALUES (949, 'AxbCroDToyBHN ynXKq', 315.59);
INSERT INTO public.products (id, name, price) VALUES (950, 'NYGNWBsArYiGwAqlW', 95.36);
INSERT INTO public.products (id, name, price) VALUES (951, 'vuSKdPubGmw', 737.02);
INSERT INTO public.products (id, name, price) VALUES (952, 'ZRGOgQaCndcmfZvODc', 557.74);
INSERT INTO public.products (id, name, price) VALUES (953, 'kFPvWPFpvdOwrie', 871.27);
INSERT INTO public.products (id, name, price) VALUES (954, 'aSzNI', 707.66);
INSERT INTO public.products (id, name, price) VALUES (955, 'dZncnm', 91.52);
INSERT INTO public.products (id, name, price) VALUES (956, 'SqwbSaxSOiBIaokPAgq', 474.76);
INSERT INTO public.products (id, name, price) VALUES (957, 'qTKvIhPMeDWYcDbhSsP', 214.71);
INSERT INTO public.products (id, name, price) VALUES (958, 'vlkKVBA', 976.36);
INSERT INTO public.products (id, name, price) VALUES (959, 'ama kSjLaUTeTOT', 221.41);
INSERT INTO public.products (id, name, price) VALUES (960, 'vlzEfBpbRHX', 115.1);
INSERT INTO public.products (id, name, price) VALUES (961, 'zfwAug', 109.96);
INSERT INTO public.products (id, name, price) VALUES (962, 'GirwpFtmfTZxbTfW', 616.28);
INSERT INTO public.products (id, name, price) VALUES (963, 'sBpiKW', 93.65);
INSERT INTO public.products (id, name, price) VALUES (964, 'rnwQeWhyX', 557.63);
INSERT INTO public.products (id, name, price) VALUES (965, 'FRXlaewFSY', 336.34);
INSERT INTO public.products (id, name, price) VALUES (966, 'K TlIM', 501.82);
INSERT INTO public.products (id, name, price) VALUES (967, 'RkUzyrkyz', 528.91);
INSERT INTO public.products (id, name, price) VALUES (968, 'Nxjctvf', 51.87);
INSERT INTO public.products (id, name, price) VALUES (969, 'oDrPc', 809.44);
INSERT INTO public.products (id, name, price) VALUES (970, 'aACrQqsfUpKSbG', 554.53);
INSERT INTO public.products (id, name, price) VALUES (971, 'FfLjidQ', 979.59);
INSERT INTO public.products (id, name, price) VALUES (972, 'zFgEZDNSFIiLTR', 773.02);
INSERT INTO public.products (id, name, price) VALUES (973, 'lQEdTbxgQlt', 596.78);
INSERT INTO public.products (id, name, price) VALUES (974, 'LBkmiFMCHGPBis', 891.91);
INSERT INTO public.products (id, name, price) VALUES (975, 'iiAGCxm', 417.58);
INSERT INTO public.products (id, name, price) VALUES (976, 'LYiXhDKUkb', 135.89);
INSERT INTO public.products (id, name, price) VALUES (977, 'ChiMfdNccR', 443.57);
INSERT INTO public.products (id, name, price) VALUES (978, 'qhCHGA', 932.33);
INSERT INTO public.products (id, name, price) VALUES (979, 'AgDxAYT', 158.82);
INSERT INTO public.products (id, name, price) VALUES (980, 'pmKJFnT', 81.03);
INSERT INTO public.products (id, name, price) VALUES (981, 'UdekhcAOp', 124.48);
INSERT INTO public.products (id, name, price) VALUES (982, 'ydBEisTUm', 979.76);
INSERT INTO public.products (id, name, price) VALUES (983, 'cazmqcrYAX', 277.38);
INSERT INTO public.products (id, name, price) VALUES (984, 'kLL xJSqzqCjCUfrssQl', 762.75);
INSERT INTO public.products (id, name, price) VALUES (985, 'CSBkb TldnDQkRy TzQ', 806.83);
INSERT INTO public.products (id, name, price) VALUES (986, 'Jok hsggDGZOUuX', 80.8);
INSERT INTO public.products (id, name, price) VALUES (987, 'xoPBBhtlrGFut', 335.87);
INSERT INTO public.products (id, name, price) VALUES (988, 'ZqmHsbTHzZBvJOG', 399.03);
INSERT INTO public.products (id, name, price) VALUES (989, 'OgHJvwrFWkJugiHtLt', 841.12);
INSERT INTO public.products (id, name, price) VALUES (990, 'iSzBD  QYxlpN', 172.92);
INSERT INTO public.products (id, name, price) VALUES (991, 'uxvBOfxVcqAitLzDLIV', 14.81);
INSERT INTO public.products (id, name, price) VALUES (992, 'DHSkzRTwesYhLg', 588.61);
INSERT INTO public.products (id, name, price) VALUES (993, 'ievsAYqsjkrMrSEwyY A', 478.34);
INSERT INTO public.products (id, name, price) VALUES (994, 'OzbnUfmjr', 427.66);
INSERT INTO public.products (id, name, price) VALUES (995, 'wHKcTd', 656.53);
INSERT INTO public.products (id, name, price) VALUES (996, 'akHVvCjeXf cHkjGfEP', 401.05);
INSERT INTO public.products (id, name, price) VALUES (997, 'YwjwySqJnbvVCFkkqJm', 144.38);
INSERT INTO public.products (id, name, price) VALUES (998, 'odcWBBdH t j', 233.01);
INSERT INTO public.products (id, name, price) VALUES (999, 'QgViyOhjmRy', 396.24);
