INSERT INTO products ( name, price) VALUES ( 'CgXlBUntmtBosXyIqo ', 398.58);
INSERT INTO products ( name, price) VALUES ( 'ksAqUlCc ', 903.63);
INSERT INTO products ( name, price) VALUES ( 'bUvnsvtDmiERmtwEWxWy', 132);
INSERT INTO products ( name, price) VALUES ( 'ZCgifHLsbX', 455.36);
INSERT INTO products ( name, price) VALUES ( 'uASRoELUVVw', 871.82);
INSERT INTO products ( name, price) VALUES ( 'UHfQhvvOCza', 593.13);
INSERT INTO products ( name, price) VALUES ( 'qFcGAs', 269.61);
INSERT INTO products ( name, price) VALUES ( 'pxUh ', 799.76);
INSERT INTO products ( name, price) VALUES ( 'DnMkGTcwS', 261.7);
INSERT INTO products ( name, price) VALUES ( 'BDYtuSTthFL', 953.34);
INSERT INTO products ( name, price) VALUES ( 'Eub Z', 350.97);
INSERT INTO products ( name, price) VALUES ( 'DSVUQLlAzWtPY', 190.2);
INSERT INTO products ( name, price) VALUES ( 'CfthdEzO', 45.2);
INSERT INTO products ( name, price) VALUES ( 'XfvyNsMGJjzfJt hjh', 188.11);
INSERT INTO products ( name, price) VALUES ( 'WMieDyNObZkgvthzy', 855.17);
INSERT INTO products ( name, price) VALUES ( 'jikFjrfUPYxcZJinnE', 858.62);
INSERT INTO products ( name, price) VALUES ( 'EmiAAOOOwYNbkJzI', 222.55);
INSERT INTO products ( name, price) VALUES ( 'TOrbLVyGlVAZeoe', 591.67);
INSERT INTO products ( name, price) VALUES ( 'mrlFYejiRiYIHpD', 82.49);
INSERT INTO products ( name, price) VALUES ( 'fjP FPPgWs fdQM', 85.92);
INSERT INTO products ( name, price) VALUES ( 'ADJkqa JdxpXJVjnUWr', 706.55);
INSERT INTO products ( name, price) VALUES ( 'xHuiWSbzwMR ', 223.79);
INSERT INTO products ( name, price) VALUES ( 'UQHjoTXIHsoCWdgbruxg', 618.1);
INSERT INTO products ( name, price) VALUES ( 'WEaDU', 229.88);
INSERT INTO products ( name, price) VALUES ( 'puYeZv', 605.2);
INSERT INTO products ( name, price) VALUES ( 'fOFIhyNKkMAdJT', 847.42);
INSERT INTO products ( name, price) VALUES ( 'fnjHWakRsMKGp', 737.82);
INSERT INTO products ( name, price) VALUES ( 'jsWkJPWrBbbtG', 562.07);
INSERT INTO products ( name, price) VALUES ( 'OepWxopfxtVCmklnqAR', 482.87);
INSERT INTO products ( name, price) VALUES ( 'mLsVgM', 913.01);
INSERT INTO products ( name, price) VALUES ( 'AtegAigX', 721.39);
INSERT INTO products ( name, price) VALUES ( 'TqnnGN', 766.62);
INSERT INTO products ( name, price) VALUES ( 'q aWLTAnqIEAKBFWx', 607.56);
INSERT INTO products ( name, price) VALUES ( 'GoeOZDbw mbmOSHuFJ', 340.39);
INSERT INTO products ( name, price) VALUES ( 'ZaWMwMvYR', 153.57);
INSERT INTO products ( name, price) VALUES ( 'PxMlXztLPLR', 586.45);
INSERT INTO products ( name, price) VALUES ( 'rCYvfqvRO', 216.77);
INSERT INTO products ( name, price) VALUES ( 'HuzXZNm', 586.81);
INSERT INTO products ( name, price) VALUES ( 'XZlPn', 89.01);
INSERT INTO products ( name, price) VALUES ( 'GoCcfLANGiQP', 929.04);
INSERT INTO products ( name, price) VALUES ( 'LUWIZBJNcuozFdkUl', 956.22);
INSERT INTO products ( name, price) VALUES ( 'PZTVzEDvGSaZkjVci', 77.63);
INSERT INTO products ( name, price) VALUES ( 'ATzWEbxhGtxfmf', 20.13);
INSERT INTO products ( name, price) VALUES ( 'TtaqFWeWe', 544.29);
INSERT INTO products ( name, price) VALUES ( 'HNlmQvWYRYVxUSq', 444.31);
INSERT INTO products ( name, price) VALUES ( 'VmsCW', 621.18);
INSERT INTO products ( name, price) VALUES ( 'vJRDwgaqFQ i', 864.61);
INSERT INTO products ( name, price) VALUES ( 'YLrrVnBoneEmqZnJmOVH', 835.27);
INSERT INTO products ( name, price) VALUES ( 'MQs KncLUhNeKJRNJgRq', 776.33);
INSERT INTO products ( name, price) VALUES ( 'LnEmXee ecyy', 310.8);
INSERT INTO products ( name, price) VALUES ( 'lqSJphthUdj', 858.08);
INSERT INTO products ( name, price) VALUES ( 'JoaXdv kjjuXNlQvDSS', 368.69);
INSERT INTO products ( name, price) VALUES ( 'VTOZmWExf', 918.33);
INSERT INTO products ( name, price) VALUES ( 'ILbDMCwuoGx u', 330.12);
INSERT INTO products ( name, price) VALUES ( 'qBwnWawMcNxWiX', 253.4);
INSERT INTO products ( name, price) VALUES ( 'gPKasYFujpeDhe  y', 422.41);
INSERT INTO products ( name, price) VALUES ( 'VYppEcrIlRVXXFapreqL', 1000.26);
INSERT INTO products ( name, price) VALUES ( 'lZJagDDQOW', 207.07);
INSERT INTO products ( name, price) VALUES ( 'T XWjDPjpTq', 7.11);
INSERT INTO products ( name, price) VALUES ( 'fuIVLhpPey', 954.39);
INSERT INTO products ( name, price) VALUES ( 'laBWnwwXbTl', 647.94);
INSERT INTO products ( name, price) VALUES ( 'wiRCUPceVlLZSbE', 158.6);
INSERT INTO products ( name, price) VALUES ( 'WUvDadTDHOba', 59.48);
INSERT INTO products ( name, price) VALUES ( 'ozyTzBPtCYPpba l', 598.27);
INSERT INTO products ( name, price) VALUES ( 'nxByCD', 779.71);
INSERT INTO products ( name, price) VALUES ( 'AeZasfvimajYpkqWfqHa', 461.81);
INSERT INTO products ( name, price) VALUES ( 'HnjSwq btbaPaMAcZs', 824.17);
INSERT INTO products ( name, price) VALUES ( 'UvnLgPEEUjMJGxcoJz', 510.22);
INSERT INTO products ( name, price) VALUES ( 'wfycjYH akVTTnR', 792.75);
INSERT INTO products ( name, price) VALUES ( 'laRXKAMfmgOScqTAmyW', 139.84);
INSERT INTO products ( name, price) VALUES ( 'heJAxjsoiplSATvF', 90.47);
INSERT INTO products ( name, price) VALUES ( 'KFDYZHWhQfNTL f', 755.48);
INSERT INTO products ( name, price) VALUES ( 'vZxCux', 80.07);
INSERT INTO products ( name, price) VALUES ( 't JLrKTdX', 392.41);
INSERT INTO products ( name, price) VALUES ( 'IGnCEJLOinCBRgYBU', 762.93);
INSERT INTO products ( name, price) VALUES ( 'KQKtOgEYNySzw', 19.52);
INSERT INTO products ( name, price) VALUES ( 'EhybwutrPlkWToEOmjLc', 289.63);
INSERT INTO products ( name, price) VALUES ( 'uIsapwbVaCleXqAJID', 205.01);
INSERT INTO products ( name, price) VALUES ( 'BTTic', 572.36);
INSERT INTO products ( name, price) VALUES ( 'nLqxvO', 185.14);
INSERT INTO products ( name, price) VALUES ( 'wyNlJtksXJ', 856.97);
INSERT INTO products ( name, price) VALUES ( 'prZpxsfSHrZZYKuUsk', 164.39);
INSERT INTO products ( name, price) VALUES ( 'YlpmuYKkigwmTR', 347.7);
INSERT INTO products ( name, price) VALUES ( 'MhoEYmjLWZM', 185.71);
INSERT INTO products ( name, price) VALUES ( 'ZTXQxxBOHIqprStyx', 510.42);
INSERT INTO products ( name, price) VALUES ( 'VFSLvjqH', 78.03);
INSERT INTO products ( name, price) VALUES ( 'GQLTOwovlWkP', 92.55);
INSERT INTO products ( name, price) VALUES ( 'NETxZ', 125.76);
INSERT INTO products ( name, price) VALUES ( 'EdENULBJmYHYS', 519.71);
INSERT INTO products ( name, price) VALUES ( 'nwVaGfGP xqVJCW', 684.48);
INSERT INTO products ( name, price) VALUES ( 'pMzAoko', 530.42);
INSERT INTO products ( name, price) VALUES ( 'DNxgeHQfPInQF jUhMPK', 608.28);
INSERT INTO products ( name, price) VALUES ( 'IaPTaX', 193.97);
INSERT INTO products ( name, price) VALUES ( 'cNjXgjBC', 589.1);
INSERT INTO products ( name, price) VALUES ( 'ZgdlLwFybzi', 955.24);
INSERT INTO products ( name, price) VALUES ( ' oCRfkfgjBWzdBAGu', 638.77);
INSERT INTO products ( name, price) VALUES ( 'ydczXS', 939.13);
INSERT INTO products ( name, price) VALUES ( 'evg TbzTUII', 43.37);
INSERT INTO products ( name, price) VALUES ( 'ASQcsNrRXyZEMw', 489.28);
INSERT INTO products ( name, price) VALUES ( 'OB gx', 893.94);
INSERT INTO products ( name, price) VALUES ( 'wPoU AdO', 618.04);
INSERT INTO products ( name, price) VALUES ( 'UcZglfsTyKrVDrffL', 163.73);
INSERT INTO products ( name, price) VALUES ( 'dxcsQiQUeoJkq', 731.03);
INSERT INTO products ( name, price) VALUES ( 'OJYlZS', 176.48);
INSERT INTO products ( name, price) VALUES ( 'sMDIiq yWHHBYi', 951.5);
INSERT INTO products ( name, price) VALUES ( 'CHWQPAdQ', 676.3);
INSERT INTO products ( name, price) VALUES ( 'FdwqojAmvDAQjZ', 6.23);
INSERT INTO products ( name, price) VALUES ( 'pXnymehQE', 905.85);
INSERT INTO products ( name, price) VALUES ( 'BYBaursjG', 163.34);
INSERT INTO products ( name, price) VALUES ( ' YCCpdGwqmWYxrxhw', 857.07);
INSERT INTO products ( name, price) VALUES ( 'aruKbSZXTTzfQmkCVCwO', 836.39);
INSERT INTO products ( name, price) VALUES ( 'fgnOyQq', 536.72);
INSERT INTO products ( name, price) VALUES ( 'jXIwCJlgrcPtCkYiOO', 990.75);
INSERT INTO products ( name, price) VALUES ( 'DKRykITJqTsseRGpCPxa', 198.3);
INSERT INTO products ( name, price) VALUES ( 'neOhWLlXdApzUcBN', 626.56);
INSERT INTO products ( name, price) VALUES ( 'FUpR spVFLk', 881.65);
INSERT INTO products ( name, price) VALUES ( 'qmPLjioWqLnNNwW lx', 277.54);
INSERT INTO products ( name, price) VALUES ( 'DloCmdhh', 972.39);
INSERT INTO products ( name, price) VALUES ( 'CjOIoCdXVwJWf', 746.19);
INSERT INTO products ( name, price) VALUES ( 'PwAmQuGXqRABCAwRpC', 120.4);
INSERT INTO products ( name, price) VALUES ( 'ShpUTyJIEWJfzYIC', 869.65);
INSERT INTO products ( name, price) VALUES ( 'IzBeMHHjweJHXq', 339.55);
INSERT INTO products ( name, price) VALUES ( 'LkqxYkaXl', 975.77);
INSERT INTO products ( name, price) VALUES ( 'ToPEGXrlDl', 691.67);
INSERT INTO products ( name, price) VALUES ( 'kxpmSkreZLmDng', 322.74);
INSERT INTO products ( name, price) VALUES ( 'cLMIZGkogkElzd', 219.9);
INSERT INTO products ( name, price) VALUES ( 'nKJnVldwpCdLLBWdoxX', 384.21);
INSERT INTO products ( name, price) VALUES ( 'GOJPYmBoNGZwMqG', 89.02);
INSERT INTO products ( name, price) VALUES ( 'XMntRLOzb', 990.33);
INSERT INTO products ( name, price) VALUES ( 'vGJawkqqF', 240.35);
INSERT INTO products ( name, price) VALUES ( 'MUOVBbPoqFUOH', 963.23);
INSERT INTO products ( name, price) VALUES ( 'VGbskgHjJTQyGUVLkQ', 60.93);
INSERT INTO products ( name, price) VALUES ( ' PiTbRcaSWKNM', 423.42);
INSERT INTO products ( name, price) VALUES ( 'XDAZQgqSeKCEyATRRUL', 80.22);
INSERT INTO products ( name, price) VALUES ( 'zpbhd IL', 688.23);
INSERT INTO products ( name, price) VALUES ( 'CdjcSRVTMtgmRxCdlLSl', 730.93);
INSERT INTO products ( name, price) VALUES ( 'Ll wIYfYBt', 186.3);
INSERT INTO products ( name, price) VALUES ( 'hLxTlWHhFoiSszc', 419.43);
INSERT INTO products ( name, price) VALUES ( 'XVbqSvSET', 730.13);
INSERT INTO products ( name, price) VALUES ( 'RKcnLnARktJHJU', 280.67);
INSERT INTO products ( name, price) VALUES ( 'VqnoV', 932.29);
INSERT INTO products ( name, price) VALUES ( 'eQoHevJQSoQQBvx', 595.82);
INSERT INTO products ( name, price) VALUES ( 'hjdbvkFQdoAFR', 525.43);
INSERT INTO products ( name, price) VALUES ( 'uIZolVJEEOyJOvnVw', 864.87);
INSERT INTO products ( name, price) VALUES ( 'pnbSmgBWwAuYek', 817.1);
INSERT INTO products ( name, price) VALUES ( 'VnvdJeKBiohLycYazc', 976.22);
INSERT INTO products ( name, price) VALUES ( 'hKhIPTy', 765.36);
INSERT INTO products ( name, price) VALUES ( 'NEqdB', 891.13);
INSERT INTO products ( name, price) VALUES ( 'oOQRkZhwrZiVBm', 467);
INSERT INTO products ( name, price) VALUES ( 'UWxUPZTFgKZIqVm', 249.99);
INSERT INTO products ( name, price) VALUES ( 'HCaxUpSdkVG mF', 711.49);
INSERT INTO products ( name, price) VALUES ( 'vUMliMlzLcAwz', 400.13);
INSERT INTO products ( name, price) VALUES ( 'CDjMqth', 174.41);
INSERT INTO products ( name, price) VALUES ( 'ksionGSI', 324.53);
INSERT INTO products ( name, price) VALUES ( 'qgmYaeKUV', 18.19);
INSERT INTO products ( name, price) VALUES ( 'oCbrcsRriiazJGHSnk', 451.26);
INSERT INTO products ( name, price) VALUES ( 'rozKDOUolndypgbo', 46.53);
INSERT INTO products ( name, price) VALUES ( 'ilYgMDxQGrFhNWpo', 655.23);
INSERT INTO products ( name, price) VALUES ( 'kSBQWYqbqq', 798.46);
INSERT INTO products ( name, price) VALUES ( 'AHbeXvUhG', 934.15);
INSERT INTO products ( name, price) VALUES ( 'kbLRbgfchNTnrmrctuX', 782.47);
INSERT INTO products ( name, price) VALUES ( 'KdujeS', 332.54);
INSERT INTO products ( name, price) VALUES ( 'GZfuIEIr', 913.47);
INSERT INTO products ( name, price) VALUES ( 'WzDqylt', 881.93);
INSERT INTO products ( name, price) VALUES ( 'IeUrLvtBJsdQypjqLe', 969.27);
INSERT INTO products ( name, price) VALUES ( 'ESydvcs', 325.53);
INSERT INTO products ( name, price) VALUES ( 'jgzefSpRW', 792.86);
INSERT INTO products ( name, price) VALUES ( 'x LGrhjszYXl', 369.11);
INSERT INTO products ( name, price) VALUES ( 'FdpbMxpJpunghzo', 712.36);
INSERT INTO products ( name, price) VALUES ( 'vVIhAaScoQpMZI FI', 26.36);
INSERT INTO products ( name, price) VALUES ( 'GPmargXs', 164.88);
INSERT INTO products ( name, price) VALUES ( 'KlVzfGjkwduy', 562.07);
INSERT INTO products ( name, price) VALUES ( 'nYqDKtSmSEVpUOhlxEyl', 745.25);
INSERT INTO products ( name, price) VALUES ( 'TmzeTk', 324.18);
INSERT INTO products ( name, price) VALUES ( 'QDcNaQEs EVVvIxsX Cy', 805.93);
INSERT INTO products ( name, price) VALUES ( 'zaVVdmvNtZIx', 234.26);
INSERT INTO products ( name, price) VALUES ( 'RQLtaAtboR', 411.5);
INSERT INTO products ( name, price) VALUES ( 'gTTFuIEFljNfGPUo', 336.12);
INSERT INTO products ( name, price) VALUES ( 'zPdlVygKZgUL', 147.36);
INSERT INTO products ( name, price) VALUES ( 'mVgOuRCE', 35.58);
INSERT INTO products ( name, price) VALUES ( 'KTeQt', 383.84);
INSERT INTO products ( name, price) VALUES ( 'LeVyJkcjcArIitWbp', 804.37);
INSERT INTO products ( name, price) VALUES ( 'uzNcuNMAIJqDmSTmYqW', 662.55);
INSERT INTO products ( name, price) VALUES ( 'UtdrwNbmNtGTXXvMoVcL', 958.85);
INSERT INTO products ( name, price) VALUES ( ' hxSfwVWkgsSbExe lk', 843.54);
INSERT INTO products ( name, price) VALUES ( 'LkXbM', 297.54);
INSERT INTO products ( name, price) VALUES ( 'xmjGyIRmwmzlNe', 390.8);
INSERT INTO products ( name, price) VALUES ( 'kkzpGGK UreuNEHuT', 816.61);
INSERT INTO products ( name, price) VALUES ( ' FiXUpYRR', 371.93);
INSERT INTO products ( name, price) VALUES ( 'kosMkwqlIMxFGocwax ', 731.68);
INSERT INTO products ( name, price) VALUES ( 'QSyxMttQX siN', 381.09);
INSERT INTO products ( name, price) VALUES ( 'AQGlmivFulTOHH', 826.22);
INSERT INTO products ( name, price) VALUES ( 'HbfMUpGxxYW', 119.43);
INSERT INTO products ( name, price) VALUES ( 'vArTanQmFtRdsPgw', 306.31);
INSERT INTO products ( name, price) VALUES ( 'ASkyWBi', 372.31);
INSERT INTO products ( name, price) VALUES ( 'UsmnWnawCjcxdSgnXovL', 759.66);
INSERT INTO products ( name, price) VALUES ( 'Rscf JhR', 966.31);
INSERT INTO products ( name, price) VALUES ( 'qyqDszXf', 947.22);
INSERT INTO products ( name, price) VALUES ( 'rxzvMoCZvwrfXMLnINbw', 676.65);
INSERT INTO products ( name, price) VALUES ( 'jDhzjyweWOR', 607.66);
INSERT INTO products ( name, price) VALUES ( 'jpKZlbZAfahXxUrNWwHx', 505.22);
INSERT INTO products ( name, price) VALUES ( 'EmYvogwtwsNOngtR', 976.65);
INSERT INTO products ( name, price) VALUES ( 'KNvCCngwDVEq', 732.65);
INSERT INTO products ( name, price) VALUES ( 'kHiHBrQuofZsTlfYxmxS', 553.93);
INSERT INTO products ( name, price) VALUES ( 'mBE fSAfrcW', 334.63);
INSERT INTO products ( name, price) VALUES ( 'CJQGpwxZoVs', 492.16);
INSERT INTO products ( name, price) VALUES ( 'qmTQedzeDulQOlyJouGp', 839.42);
INSERT INTO products ( name, price) VALUES ( 'nqNZRhoZNZU ', 605.36);
INSERT INTO products ( name, price) VALUES ( 'GtXTbcdDDDbSCgaeB ', 49.64);
INSERT INTO products ( name, price) VALUES ( 'XgDGCaGZuqplNCWj', 784.43);
INSERT INTO products ( name, price) VALUES ( 'vPwGplTDgVAGwQAFwR', 969.73);
INSERT INTO products ( name, price) VALUES ( 'PYGHBeE', 746.5);
INSERT INTO products ( name, price) VALUES ( ' dNumMtVxOCBL', 936.68);
INSERT INTO products ( name, price) VALUES ( 'zkHGrdbswdlu', 650.1);
INSERT INTO products ( name, price) VALUES ( 'NigKLWrux', 824.87);
INSERT INTO products ( name, price) VALUES ( 'FwzRzw', 686.49);
INSERT INTO products ( name, price) VALUES ( 'UfQKdclPlhNmFe', 259.51);
INSERT INTO products ( name, price) VALUES ( 'e  IJwFXUvwTdvIPFn', 527.92);
INSERT INTO products ( name, price) VALUES ( 'LEXwGrFZJr', 372.72);
INSERT INTO products ( name, price) VALUES ( 'lduLyYokuKhNLPWy', 908.23);
INSERT INTO products ( name, price) VALUES ( 'wvYEywkt afnPbvIoklA', 707.2);
INSERT INTO products ( name, price) VALUES ( ' ikmLTHP jcnIa', 729.68);
INSERT INTO products ( name, price) VALUES ( 'PtqYewzOF', 64.47);
INSERT INTO products ( name, price) VALUES ( 'sOBryLFYpeMgvLCM Lbx', 943.31);
INSERT INTO products ( name, price) VALUES ( 'dhjJAssBybVVpnrGzV', 680.03);
INSERT INTO products ( name, price) VALUES ( 'vUfyHeJr', 290.56);
INSERT INTO products ( name, price) VALUES ( 'IeewnCaFxqBzfXQTqaqU', 620.87);
INSERT INTO products ( name, price) VALUES ( 'SrGDctbs', 790.75);
INSERT INTO products ( name, price) VALUES ( 'QFpknymKE', 9.73);
INSERT INTO products ( name, price) VALUES ( 'omBThwbc', 602.03);
INSERT INTO products ( name, price) VALUES ( 'jkqFkCgnrjSsCAi', 499.63);
INSERT INTO products ( name, price) VALUES ( 'CPhMiY oUMxLrUrSsnEV', 242.77);
INSERT INTO products ( name, price) VALUES ( 'rANcsJIkLnTpNgcwOTAG', 353.1);
INSERT INTO products ( name, price) VALUES ( 'IcGlSBIZUOaSyr', 876.2);
INSERT INTO products ( name, price) VALUES ( 'ToSArOpVcULEXQfQdV', 397.49);
INSERT INTO products ( name, price) VALUES ( 'cS I PCdkPa', 955.33);
INSERT INTO products ( name, price) VALUES ( 'qrqTmZcFYiairk', 154.1);
INSERT INTO products ( name, price) VALUES ( 'hmNFbgDVQHs nA', 317.72);
INSERT INTO products ( name, price) VALUES ( 'JZBFvXGfwdTuQOMV', 608.25);
INSERT INTO products ( name, price) VALUES ( 'kv kR N', 799.15);
INSERT INTO products ( name, price) VALUES ( 'zzJGeilFSE', 809.34);
INSERT INTO products ( name, price) VALUES ( 'oGMrL', 292.67);
INSERT INTO products ( name, price) VALUES ( 'UrsHdKgmywHkfn', 569.15);
INSERT INTO products ( name, price) VALUES ( 'pTQFdcsFKPs', 545.96);
INSERT INTO products ( name, price) VALUES ( 'oYCwFvresPGUoMBzpl X', 372.55);
INSERT INTO products ( name, price) VALUES ( 'OznOkwzw', 903.22);
INSERT INTO products ( name, price) VALUES ( 'XDaPBXN SBlA', 405.12);
INSERT INTO products ( name, price) VALUES ( 'AWaHZwKhuOgafOLLffLT', 337.49);
INSERT INTO products ( name, price) VALUES ( 'AfOSofreyKFEGKXgjx', 746.61);
INSERT INTO products ( name, price) VALUES ( 'QujZjPNlSWh', 453.68);
INSERT INTO products ( name, price) VALUES ( 'oaBJzqrShDVAQTy', 924.97);
INSERT INTO products ( name, price) VALUES ( 'zROhNjpsVg', 26.72);
INSERT INTO products ( name, price) VALUES ( 'CnuCXJ', 38.62);
INSERT INTO products ( name, price) VALUES ( 'iiZtaKxy', 808.31);
INSERT INTO products ( name, price) VALUES ( 'qdR XjbEXU', 53.5);
INSERT INTO products ( name, price) VALUES ( 'lmwIGTGgYIaNBGGpebPF', 795.28);
INSERT INTO products ( name, price) VALUES ( 'jjFftxnfruj', 574.46);
INSERT INTO products ( name, price) VALUES ( 'VnmJReQHVfoFjilkfdD', 426.87);
INSERT INTO products ( name, price) VALUES ( 'j at rzZuoxhzlCMRRF', 717.18);
INSERT INTO products ( name, price) VALUES ( ' AHQTFqKPaAKWWc', 825.76);
INSERT INTO products ( name, price) VALUES ( 'lJmHNlpTfvHGokBJWY', 548.95);
INSERT INTO products ( name, price) VALUES ( 'IQfaP', 692.67);
INSERT INTO products ( name, price) VALUES ( 'EUSMIrmR', 511.91);
INSERT INTO products ( name, price) VALUES ( 'UaSyZw', 611.25);
INSERT INTO products ( name, price) VALUES ( 'ZajtAg', 889.42);
INSERT INTO products ( name, price) VALUES ( 'AfeHRZMfrMKLnOL', 317.25);
INSERT INTO products ( name, price) VALUES ( 'fJfbYfIQzm', 595.49);
INSERT INTO products ( name, price) VALUES ( 'MK yKZsdRHMg', 821.32);
INSERT INTO products ( name, price) VALUES ( 'luJECMsPrOB', 745.78);
INSERT INTO products ( name, price) VALUES ( 'OhejcAhmCufzyDOYMDD', 239.98);
INSERT INTO products ( name, price) VALUES ( 'cuussEfPdrEmiCIVGs', 452.58);
INSERT INTO products ( name, price) VALUES ( 'JzMsmbhHIiT', 32.2);
INSERT INTO products ( name, price) VALUES ( 'iqkMcSWEHNfmlAkb', 509.24);
INSERT INTO products ( name, price) VALUES ( ' aIuXf CGJjX', 158.14);
INSERT INTO products ( name, price) VALUES ( 'zZdAaP', 613.22);
INSERT INTO products ( name, price) VALUES ( 'kfKVI p', 320.5);
INSERT INTO products ( name, price) VALUES ( 'GkWZRaDzM', 754.66);
INSERT INTO products ( name, price) VALUES ( 'RQggVssmfYZixtglEb', 561.5);
INSERT INTO products ( name, price) VALUES ( 'mfXuEewU HlxURVkwdIG', 938.22);
INSERT INTO products ( name, price) VALUES ( 'IrOmvEuGBFrqpK EOdye', 66.61);
INSERT INTO products ( name, price) VALUES ( 'oQQepY', 248.49);
INSERT INTO products ( name, price) VALUES ( 'vUVgOAiEjJHGK', 646.93);
INSERT INTO products ( name, price) VALUES ( 'NIQHqPn', 763.19);
INSERT INTO products ( name, price) VALUES ( 'HWkgFtoRlPPSvBSJSYol', 437.17);
INSERT INTO products ( name, price) VALUES ( 'XeOXXmFeajhrY Q', 723.74);
INSERT INTO products ( name, price) VALUES ( 'zkgKsJN', 559.82);
INSERT INTO products ( name, price) VALUES ( 'iUokOA', 420.51);
INSERT INTO products ( name, price) VALUES ( 'm uHqThZdQGxWowsVHK', 603.09);
INSERT INTO products ( name, price) VALUES ( 'KZZteiuqYRsIfHIZN', 524.24);
INSERT INTO products ( name, price) VALUES ( 'VaQzbRLslS', 818.01);
INSERT INTO products ( name, price) VALUES ( 'LqsWCWzSWIf', 255.56);
INSERT INTO products ( name, price) VALUES ( 'SculdCCUVHyCC', 179.41);
INSERT INTO products ( name, price) VALUES ( 'rXEVzGmdZQBFMo', 308.49);
INSERT INTO products ( name, price) VALUES ( 'SIhvqYlReAHQwXqGCf', 274.99);
INSERT INTO products ( name, price) VALUES ( 'eJaGKReBFnGKNBCZLKeY', 250.67);
INSERT INTO products ( name, price) VALUES ( 'NizClr', 365.94);
INSERT INTO products ( name, price) VALUES ( 'xLgJefjBRfgebBivcpy', 624.06);
INSERT INTO products ( name, price) VALUES ( 'ZEzaJFPZUi  ArMTffd', 623.3);
INSERT INTO products ( name, price) VALUES ( 'oulUHjIDFhPGs', 966.7);
INSERT INTO products ( name, price) VALUES ( 'PTSVTnvyOhosZetLHHgh', 541.31);
INSERT INTO products ( name, price) VALUES ( 'Az fsOJak', 407.92);
INSERT INTO products ( name, price) VALUES ( 'LhncGTZLsDJJrI', 608.35);
INSERT INTO products ( name, price) VALUES ( 'nGePcxdK kr', 455.92);
INSERT INTO products ( name, price) VALUES ( 'kbLtyrqoPAOQTJpIo', 769.31);
INSERT INTO products ( name, price) VALUES ( 'JtdjsfDMt', 941.77);
INSERT INTO products ( name, price) VALUES ( 'yauEYPXsiyYQDb', 908.37);
INSERT INTO products ( name, price) VALUES ( 'nHabXlTvc tnjRVslpe', 282.21);
INSERT INTO products ( name, price) VALUES ( ' EWayfkqzVHjn', 143.41);
INSERT INTO products ( name, price) VALUES ( 'TIZBdjzrAMXgYAk', 623.04);
INSERT INTO products ( name, price) VALUES ( 'MgFsl dEXTEwyVDw', 175.77);
INSERT INTO products ( name, price) VALUES ( 'k PJVbvZ', 896.62);
INSERT INTO products ( name, price) VALUES ( 'mmbSIvUpFjNvFVwVj', 43.56);
INSERT INTO products ( name, price) VALUES ( 'DELZfJAvzVfZt', 809.75);
INSERT INTO products ( name, price) VALUES ( 'XPNLPKKdVQzfVgFuGijI', 980.29);
INSERT INTO products ( name, price) VALUES ( 'YYeXZZOdQqHAzjl', 463.85);
INSERT INTO products ( name, price) VALUES ( 'OQiZqROmRmi', 399.85);
INSERT INTO products ( name, price) VALUES ( 'HajgymcZCbQFucpnd', 871.06);
INSERT INTO products ( name, price) VALUES ( 'yopIzIeAr', 504.84);
INSERT INTO products ( name, price) VALUES ( 'LzcLjVjeicXubYws', 915.61);
INSERT INTO products ( name, price) VALUES ( 'TVhpYGj', 145.69);
INSERT INTO products ( name, price) VALUES ( 'lyKinITLkF', 852.03);
INSERT INTO products ( name, price) VALUES ( 'exOkIdQsnQNJjOBO', 341);
INSERT INTO products ( name, price) VALUES ( 'tiQkxDCOIfZ', 860.45);
INSERT INTO products ( name, price) VALUES ( 'tyynVwCUzmL', 344.46);
INSERT INTO products ( name, price) VALUES ( 'zXoNQTGAyJ', 961.75);
INSERT INTO products ( name, price) VALUES ( 'vOBldlBriB', 393.13);
INSERT INTO products ( name, price) VALUES ( 'MyzryxbClJv', 611.05);
INSERT INTO products ( name, price) VALUES ( 'gQdkQnoOn', 8.85);
INSERT INTO products ( name, price) VALUES ( 'SqRaLbfEDtNjKW', 406.04);
INSERT INTO products ( name, price) VALUES ( 'GLxeyDpai', 734.38);
INSERT INTO products ( name, price) VALUES ( 'HXOFLV', 751.27);
INSERT INTO products ( name, price) VALUES ( 'pwlBfdHSgmdTuxHjPjzD', 895.56);
INSERT INTO products ( name, price) VALUES ( 'FKFmCEaIMNFlRl', 246.31);
INSERT INTO products ( name, price) VALUES ( 'XLo QdxYlLJbxnU', 106.88);
INSERT INTO products ( name, price) VALUES ( 'sd TlC UilEDFMOSg', 39.43);
INSERT INTO products ( name, price) VALUES ( 'uXSnGsGjHSafPpC U', 88.6);
INSERT INTO products ( name, price) VALUES ( 'sumHZYlRHfEHBckDCsJ', 303.74);
INSERT INTO products ( name, price) VALUES ( 'RaMHsN', 532.91);
INSERT INTO products ( name, price) VALUES ( 'LRrFfKYhLd', 745.35);
INSERT INTO products ( name, price) VALUES ( 'uMrxto', 942.82);
INSERT INTO products ( name, price) VALUES ( 'xWeEzk', 994.61);
INSERT INTO products ( name, price) VALUES ( 'mX jHy zWYDCC', 407.45);
INSERT INTO products ( name, price) VALUES ( 'GoEwoW', 853.39);
INSERT INTO products ( name, price) VALUES ( 'fq zMO', 142.72);
INSERT INTO products ( name, price) VALUES ( 'RRUOhpvn', 761.53);
INSERT INTO products ( name, price) VALUES ( 'wHcZxLXMJf', 61.05);
INSERT INTO products ( name, price) VALUES ( 'HjenDjYtCD', 781.67);
INSERT INTO products ( name, price) VALUES ( 'BDvzXQcYPYWi', 736.46);
INSERT INTO products ( name, price) VALUES ( 'RrCB vLn', 769.87);
INSERT INTO products ( name, price) VALUES ( 'uNdpZmBY', 845.66);
INSERT INTO products ( name, price) VALUES ( 'MctwcCOKTl', 633.81);
INSERT INTO products ( name, price) VALUES ( 'cwXrXHfRiofnekqkN', 777.42);
INSERT INTO products ( name, price) VALUES ( 'fLsKZgXwk', 562.53);
INSERT INTO products ( name, price) VALUES ( 'ieiEBGVUPuoUTtpHxYCo', 220.68);
INSERT INTO products ( name, price) VALUES ( 'DXMoOAe', 279.94);
INSERT INTO products ( name, price) VALUES ( 'BrFhkHOMOyOoBbyfO', 424.3);
INSERT INTO products ( name, price) VALUES ( 'IMihrkoisirzmdSWf', 73.12);
INSERT INTO products ( name, price) VALUES ( 'pCGkMXdvxOoF', 115.35);
INSERT INTO products ( name, price) VALUES ( 'XzKBDog', 11.36);
INSERT INTO products ( name, price) VALUES ( 'xrtS UuveMseKJIVQ', 34.74);
INSERT INTO products ( name, price) VALUES ( 'vniTFMcEIeWX', 231.41);
INSERT INTO products ( name, price) VALUES ( 'JIDUJaHzCiO', 964.96);
INSERT INTO products ( name, price) VALUES ( 'GpThQm', 427.17);
INSERT INTO products ( name, price) VALUES ( 'nvjXDNjDMlCWk', 489.3);
INSERT INTO products ( name, price) VALUES ( 'GQKezSodrtAISym', 89.87);
INSERT INTO products ( name, price) VALUES ( 'YSTzSbwFdsiHZU', 592.72);
INSERT INTO products ( name, price) VALUES ( 'WBOOIQSjGyDFOr', 422.19);
INSERT INTO products ( name, price) VALUES ( 'uTEiUmdOASj', 963.34);
INSERT INTO products ( name, price) VALUES ( 'GevsFAjYDzSeC', 770.78);
INSERT INTO products ( name, price) VALUES ( 'e ZlpVkuYkahSTBSOZ', 740.2);
INSERT INTO products ( name, price) VALUES ( 'RmpUkOHe', 271.14);
INSERT INTO products ( name, price) VALUES ( 'IEXLFItnyTBl', 104.93);
INSERT INTO products ( name, price) VALUES ( 'RTHamno', 730.01);
INSERT INTO products ( name, price) VALUES ( 'KvMxXlcSDW', 422.24);
INSERT INTO products ( name, price) VALUES ( 'NBlkWBOaHALVDWI', 258.21);
INSERT INTO products ( name, price) VALUES ( 'bKuyNR', 816.46);
INSERT INTO products ( name, price) VALUES ( 'uAcaoCbRY', 878.67);
INSERT INTO products ( name, price) VALUES ( 'PBLiy', 349.67);
INSERT INTO products ( name, price) VALUES ( 'XGiYZMbxvI WWzoBlao', 170.51);
INSERT INTO products ( name, price) VALUES ( 'xqHqeW zsWzU', 288.38);
INSERT INTO products ( name, price) VALUES ( 'HEaKgoElHBVsR', 394.87);
INSERT INTO products ( name, price) VALUES ( 'repnBqfVbg', 423.01);
INSERT INTO products ( name, price) VALUES ( 'jFvAlgKYIQTkKfvXqj', 613.31);
INSERT INTO products ( name, price) VALUES ( 'RGSBYgCNCZGtoglaQ', 759.41);
INSERT INTO products ( name, price) VALUES ( 'qwwIJfdvEFmK', 655.68);
INSERT INTO products ( name, price) VALUES ( 'MHOapFacyZz', 702.53);
INSERT INTO products ( name, price) VALUES ( 'MAfTYJhiyAF e', 11.56);
INSERT INTO products ( name, price) VALUES ( 'qzlBroXqR', 511.42);
INSERT INTO products ( name, price) VALUES ( 'wOcQpaMahQFQbGmeBeD', 907.07);
INSERT INTO products ( name, price) VALUES ( 'nLrOpCg', 543.07);
INSERT INTO products ( name, price) VALUES ( 'PWYChEWtiUQTUqJsGxpx', 817.17);
INSERT INTO products ( name, price) VALUES ( 'SpvYJKbiJKSa qvh', 177.33);
INSERT INTO products ( name, price) VALUES ( 'glZsuhp', 117.45);
INSERT INTO products ( name, price) VALUES ( ' rEzY VKKPX qthlJ', 781.72);
INSERT INTO products ( name, price) VALUES ( 'WCLuTVbNbnItmcoswJmH', 121.08);
INSERT INTO products ( name, price) VALUES ( 'TRzATV', 133.02);
INSERT INTO products ( name, price) VALUES ( 'XBBnSLNFowuqv', 280.61);
INSERT INTO products ( name, price) VALUES ( 'GAMPJrbofWUsSTLj', 989.47);
INSERT INTO products ( name, price) VALUES ( 'QUtabxdTXxbcWkWW', 843.55);
INSERT INTO products ( name, price) VALUES ( 'ikusckGuZt', 914.29);
INSERT INTO products ( name, price) VALUES ( 'mmVrTMj', 755.25);
INSERT INTO products ( name, price) VALUES ( 'RopaG', 31.77);
INSERT INTO products ( name, price) VALUES ( 'tbEEav', 116.28);
INSERT INTO products ( name, price) VALUES ( 'MFywxmCPROXFaDskYlm', 264.22);
INSERT INTO products ( name, price) VALUES ( 'vVuJdtPzlqURQgIsgcfv', 400.24);
INSERT INTO products ( name, price) VALUES ( 'qADHF', 845.67);
INSERT INTO products ( name, price) VALUES ( 'hVMSHIoxKyKEnZ', 118.28);
INSERT INTO products ( name, price) VALUES ( 'AcsGg', 651.48);
INSERT INTO products ( name, price) VALUES ( 'zUfjmFXO', 601.77);
INSERT INTO products ( name, price) VALUES ( 'souW raQVCCZGJ', 703.32);
INSERT INTO products ( name, price) VALUES ( 'unznKlc xJzIfdpqAWI', 151.24);
INSERT INTO products ( name, price) VALUES ( 'dkPREQGxfg', 981.63);
INSERT INTO products ( name, price) VALUES ( 'Oyxup', 529.32);
INSERT INTO products ( name, price) VALUES ( 'IzvfhBLm', 812.83);
INSERT INTO products ( name, price) VALUES ( 'TLaUYApuphqtjoQhsOk', 11.46);
INSERT INTO products ( name, price) VALUES ( 'uAOtsUi', 575.25);
INSERT INTO products ( name, price) VALUES ( 'LrYHcGAuVTHjqPITaC g', 627.05);
INSERT INTO products ( name, price) VALUES ( 'ZCJQe', 608.93);
INSERT INTO products ( name, price) VALUES ( 'lrldDzka', 712.62);
INSERT INTO products ( name, price) VALUES ( 'EDHOkW', 307.37);
INSERT INTO products ( name, price) VALUES ( 'TTwWIICfaUAczXtjppzD', 762.22);
INSERT INTO products ( name, price) VALUES ( 'paJkE mr', 117.6);
INSERT INTO products ( name, price) VALUES ( 'AVGNVTMdbPIBYC ', 297.03);
INSERT INTO products ( name, price) VALUES ( 'kbwktmLXEhKAVqbbgBOx', 395.35);
INSERT INTO products ( name, price) VALUES ( 'FPQetILG b', 541.28);
INSERT INTO products ( name, price) VALUES ( 'bFTaiXxBD', 753.05);
INSERT INTO products ( name, price) VALUES ( 'dhiqMZdJOK', 573.6);
INSERT INTO products ( name, price) VALUES ( 'CpslsSndneHzNoy', 499.26);
INSERT INTO products ( name, price) VALUES ( 'zrNjchzXNazt', 747.65);
INSERT INTO products ( name, price) VALUES ( 'LJGpltDobSsDuPDD', 645.88);
INSERT INTO products ( name, price) VALUES ( 'NYQRJADqjvjusA', 826.62);
INSERT INTO products ( name, price) VALUES ( 'UqwgslYaeFiwQgDWQBZ', 544.43);
INSERT INTO products ( name, price) VALUES ( 'EPUmAkrvguJHKenT', 821.19);
INSERT INTO products ( name, price) VALUES ( 'hAiOIbnqG', 618.31);
INSERT INTO products ( name, price) VALUES ( 'ZxbBFLasWAe', 204.38);
INSERT INTO products ( name, price) VALUES ( 'KN QvNfxslCLOGy', 643.99);
INSERT INTO products ( name, price) VALUES ( 'ccKdNBxoSVYAOKvDxfTU', 917.34);
INSERT INTO products ( name, price) VALUES ( 'rYJKKzICdmWnBByOy', 141.54);
INSERT INTO products ( name, price) VALUES ( 'OFuIIbmLtCphvQvmgtZ ', 890.21);
INSERT INTO products ( name, price) VALUES ( 'WFvKukOgqzhdaDtp', 963.79);
INSERT INTO products ( name, price) VALUES ( 'tZsjdJMnhdC', 936.17);
INSERT INTO products ( name, price) VALUES ( 'rybVrFbKgcHBIzC LV ', 537.69);
INSERT INTO products ( name, price) VALUES ( ' fawhaAchIJExP', 371.51);
INSERT INTO products ( name, price) VALUES ( 'qkcaeeqXKqi', 139.76);
INSERT INTO products ( name, price) VALUES ( 'FqpuOrrm jeraTlEY', 735.72);
INSERT INTO products ( name, price) VALUES ( 'IICfBvxdznpVX', 961.9);
INSERT INTO products ( name, price) VALUES ( 'bWJB jmsYanJewckRTM', 316.94);
INSERT INTO products ( name, price) VALUES ( 'AApcAGGtESarbqMkklP', 562.75);
INSERT INTO products ( name, price) VALUES ( 'kqmnVuz zR', 146.67);
INSERT INTO products ( name, price) VALUES ( 'DeeisfdUxAa', 794.21);
INSERT INTO products ( name, price) VALUES ( 'UZCaekeGtSENHH', 289.51);
INSERT INTO products ( name, price) VALUES ( 'krhXL Nw', 413.35);
INSERT INTO products ( name, price) VALUES ( 'PZpHRnpfwCpqUvWr', 110.17);
INSERT INTO products ( name, price) VALUES ( 'GhJLHhmvNCEpqGcuLYgw', 346.48);
INSERT INTO products ( name, price) VALUES ( 'IAxwOfaNQqIA', 681.49);
INSERT INTO products ( name, price) VALUES ( 'gnwBYiWLWdEj', 769.24);
INSERT INTO products ( name, price) VALUES ( 'IBjoA', 724.51);
INSERT INTO products ( name, price) VALUES ( 'FXYMtxBSxDEVF e', 790.84);
INSERT INTO products ( name, price) VALUES ( 'mDMBy', 734.29);
INSERT INTO products ( name, price) VALUES ( 'SwOEnHsx', 237.95);
INSERT INTO products ( name, price) VALUES ( 'Nlmf ndNmttnjbuztlA', 101.41);
INSERT INTO products ( name, price) VALUES ( 'YXCcKAFigXIO LbRCp', 481.29);
INSERT INTO products ( name, price) VALUES ( 'mzfwzUr hfNTXH Us', 611.38);
INSERT INTO products ( name, price) VALUES ( 'JfivZuitqekKZ', 432.13);
INSERT INTO products ( name, price) VALUES ( 'ZhTeVgRt', 916.68);
INSERT INTO products ( name, price) VALUES ( 'QFNoRbOt', 579.61);
INSERT INTO products ( name, price) VALUES ( 'zLxzwMbo ANPqRfN', 845.25);
INSERT INTO products ( name, price) VALUES ( 'BXyhlsuAyyhuNO', 638.19);
INSERT INTO products ( name, price) VALUES ( 'vRfoacGwuCR', 429.46);
INSERT INTO products ( name, price) VALUES ( 'VbfCxl', 461.27);
INSERT INTO products ( name, price) VALUES ( 'zTePjEmUbzPQPdduKuwN', 938.21);
INSERT INTO products ( name, price) VALUES ( 'Rsfj ONrwASehJaxwKd', 486.34);
INSERT INTO products ( name, price) VALUES ( 'FzGnKohZk', 767.3);
INSERT INTO products ( name, price) VALUES ( 'WoEBXaOQ', 814.35);
INSERT INTO products ( name, price) VALUES ( 'xWZPBLQX', 74.08);
INSERT INTO products ( name, price) VALUES ( 'ItPjcJojKNVH', 148.73);
INSERT INTO products ( name, price) VALUES ( 'vNslpRLFK', 415.63);
INSERT INTO products ( name, price) VALUES ( 'BwKDFxlzCIr ', 562.57);
INSERT INTO products ( name, price) VALUES ( 'pHIyQImyXdpjToZuu', 381.95);
INSERT INTO products ( name, price) VALUES ( 'EdjMCe', 498.21);
INSERT INTO products ( name, price) VALUES ( 'cJSBJyzzTmJuvuXLLYY', 722.54);
INSERT INTO products ( name, price) VALUES ( 'dCCjqx', 907.16);
INSERT INTO products ( name, price) VALUES ( 'MGbYISGiNHhH', 39.19);
INSERT INTO products ( name, price) VALUES ( 'nIgVpdALJDYvakCGkG', 292.89);
INSERT INTO products ( name, price) VALUES ( 'ERyZdxCP', 893.95);
INSERT INTO products ( name, price) VALUES ( 'vjuOXjSZ', 680.03);
INSERT INTO products ( name, price) VALUES ( 'qGaiszCjiIoTIYjWKWi ', 889.21);
INSERT INTO products ( name, price) VALUES ( 'ShxiztJuUoCvWQ', 552.52);
INSERT INTO products ( name, price) VALUES ( 'AclPKuUVwfAQdejMhTj', 86.6);
INSERT INTO products ( name, price) VALUES ( 'ouWrWsRAEqFt', 431.87);
INSERT INTO products ( name, price) VALUES ( 'RCICNgoZgrGeJUtUrQ', 336.49);
INSERT INTO products ( name, price) VALUES ( 'SwhcssYgJyIkmRuKVr', 314.42);
INSERT INTO products ( name, price) VALUES ( 'eIFDusWjLFHWyxnTZncl', 373.35);
INSERT INTO products ( name, price) VALUES ( 'stkCxBUAdDFYzege uW', 502.92);
INSERT INTO products ( name, price) VALUES ( 'ZtInTGdDQXbDgHulm', 16.43);
INSERT INTO products ( name, price) VALUES ( 'urQzvxLPZXpaAbdaJH', 338.28);
INSERT INTO products ( name, price) VALUES ( 'jCddzGoC', 283.37);
INSERT INTO products ( name, price) VALUES ( 'xgJVTLgfqCHe', 355.62);
INSERT INTO products ( name, price) VALUES ( 'djZLDlxYRtbCDp', 749.24);
INSERT INTO products ( name, price) VALUES ( 'sMpxLfITWWui', 839.11);
INSERT INTO products ( name, price) VALUES ( 'DldsH t', 550.81);
INSERT INTO products ( name, price) VALUES ( 'bzCDbpLVJBipKtL', 61.36);
INSERT INTO products ( name, price) VALUES ( 'lD SSAppvnnFdLvm', 114.27);
INSERT INTO products ( name, price) VALUES ( 'fhztBkrNFRKxED', 71.11);
INSERT INTO products ( name, price) VALUES ( 'hJCmdqY', 25.78);
INSERT INTO products ( name, price) VALUES ( 'trGNTrWnBo', 113.07);
INSERT INTO products ( name, price) VALUES ( 'bVByS', 974.88);
INSERT INTO products ( name, price) VALUES ( 'ZIrQoTxRwmyxO', 529.77);
INSERT INTO products ( name, price) VALUES ( 'lAUxAXusXu', 560.11);
INSERT INTO products ( name, price) VALUES ( 'kuCnmgmQM fRCEe', 761.73);
INSERT INTO products ( name, price) VALUES ( 'XdcqSAPzDWP', 209.92);
INSERT INTO products ( name, price) VALUES ( 'GsXga', 887.67);
INSERT INTO products ( name, price) VALUES ( 'tJeWy TEwuPTkA', 328.07);
INSERT INTO products ( name, price) VALUES ( 'SGAqbbtZSvhzfqTVSPR', 437.62);
INSERT INTO products ( name, price) VALUES ( 'IXdoqrOfqlZPtjxc', 830.96);
INSERT INTO products ( name, price) VALUES ( 'hAlcPA Ce cGbRRyug', 65.53);
INSERT INTO products ( name, price) VALUES ( 'HhbDRFBqOtIhXeN', 616.69);
INSERT INTO products ( name, price) VALUES ( 'KSlSGwDbIq', 214.3);
INSERT INTO products ( name, price) VALUES ( 'dhoyDKPZLQCmFZyCxllm', 945.05);
INSERT INTO products ( name, price) VALUES ( 'uQlgQXbIjqykDA', 824.24);
INSERT INTO products ( name, price) VALUES ( 'f tcTC XaEpJCIW', 220.32);
INSERT INTO products ( name, price) VALUES ( 'qBArdnqfg', 498.2);
INSERT INTO products ( name, price) VALUES ( 'aSncoaxV', 985.18);
INSERT INTO products ( name, price) VALUES ( 'xQuppTYV', 497.2);
INSERT INTO products ( name, price) VALUES ( 'bASSjZRpm', 330.42);
INSERT INTO products ( name, price) VALUES ( 'gKFZsDZGRmjqBHG', 216.96);
INSERT INTO products ( name, price) VALUES ( 'qGGWMShldeRB', 916.5);
INSERT INTO products ( name, price) VALUES ( 'HqWVC', 321.5);
INSERT INTO products ( name, price) VALUES ( 'ZvkwSqmTUOypGSMUbHLi', 118.54);
INSERT INTO products ( name, price) VALUES ( 'JTXuoZRomGK zkKl', 144.47);
INSERT INTO products ( name, price) VALUES ( 'fVFcXQCNPEWXIvkf Tjd', 915.54);
INSERT INTO products ( name, price) VALUES ( 'plfwwFOkfIdTv', 210.18);
INSERT INTO products ( name, price) VALUES ( 'BtsOWRa yr', 310.72);
INSERT INTO products ( name, price) VALUES ( 'HSsI CZ', 758.02);
INSERT INTO products ( name, price) VALUES ( 'dINhIXZwvAjMwI', 511.31);
INSERT INTO products ( name, price) VALUES ( 'plA muipth', 487.43);
INSERT INTO products ( name, price) VALUES ( 'cSLLDwCyQfH', 425.93);
INSERT INTO products ( name, price) VALUES ( 'raPnSKJWesfnuYTvoxA', 590.43);
INSERT INTO products ( name, price) VALUES ( 'CjCBZG XZgPhFNg', 146.69);
INSERT INTO products ( name, price) VALUES ( 'CJIxgYxVrRiFD', 122.15);
INSERT INTO products ( name, price) VALUES ( 'LEXhIKyxXJr k', 560.46);
INSERT INTO products ( name, price) VALUES ( 'rfLyngsEyUiE', 555.05);
INSERT INTO products ( name, price) VALUES ( 'OkKjpYHjjjyilphO a', 997.1);
INSERT INTO products ( name, price) VALUES ( 'RSBUWWVY FBzlrzh j', 113.91);
INSERT INTO products ( name, price) VALUES ( 'IcYqcvyEHQIW', 595.23);
INSERT INTO products ( name, price) VALUES ( ' UAHRqWSVIeMrCbgBTm', 774.71);
INSERT INTO products ( name, price) VALUES ( 'VtSSTDGKFPj', 788.09);
INSERT INTO products ( name, price) VALUES ( 'rTNNAptxqrlxxX', 873.89);
INSERT INTO products ( name, price) VALUES ( 'uOsiWkKnMVuzUmxfT', 349.08);
INSERT INTO products ( name, price) VALUES ( 'HVygAXhktTzRyLPYJcLs', 911.78);
INSERT INTO products ( name, price) VALUES ( 'siEbbLSfJKiJjLeDwz', 921.46);
INSERT INTO products ( name, price) VALUES ( 'pAsWhdyFi', 180.13);
INSERT INTO products ( name, price) VALUES ( 'pCpenGYcTuv Ionn', 105.15);
INSERT INTO products ( name, price) VALUES ( 'GTPsYBtnYkZnUkl', 955.75);
INSERT INTO products ( name, price) VALUES ( 'nOcpXDnYzSVpLPzaed', 162.53);
INSERT INTO products ( name, price) VALUES ( 'xRlkRFVpdiE NJGSYh ', 697.08);
INSERT INTO products ( name, price) VALUES ( 'HmcYyYKWvDeIGQFAFtD', 723.61);
INSERT INTO products ( name, price) VALUES ( 'hGddeGDqftbTGkyszH', 932.55);
INSERT INTO products ( name, price) VALUES ( 'PdHvozQzfxZ', 487.35);
INSERT INTO products ( name, price) VALUES ( 'dzCklfZK', 85.83);
INSERT INTO products ( name, price) VALUES ( 'mMTSzmpiF', 106.75);
INSERT INTO products ( name, price) VALUES ( 'pSuCtEwImogc', 21.8);
INSERT INTO products ( name, price) VALUES ( 'rDqkmbIxaw', 734.52);
INSERT INTO products ( name, price) VALUES ( 'bavhdkULQASZKxJJyAO', 428.45);
INSERT INTO products ( name, price) VALUES ( 'ZTDNeYpzTk zLz', 117.32);
INSERT INTO products ( name, price) VALUES ( 'EfvQrSfroPpsqrDoCjLc', 525.57);
INSERT INTO products ( name, price) VALUES ( 'eukII', 322.69);
INSERT INTO products ( name, price) VALUES ( 'gCRUIqWqNavrX', 752.94);
INSERT INTO products ( name, price) VALUES ( 'CltPTCxozkEux', 682.54);
INSERT INTO products ( name, price) VALUES ( ' kgMpl', 870.39);
INSERT INTO products ( name, price) VALUES ( 'sXFDdyPmKZdtfQvkmBl', 458.29);
INSERT INTO products ( name, price) VALUES ( 'BSCNYNZoBSkYFYkrbLR', 409.43);
INSERT INTO products ( name, price) VALUES ( 'MKgYHHjoP', 6.48);
INSERT INTO products ( name, price) VALUES ( 'sjySdv', 627.04);
INSERT INTO products ( name, price) VALUES ( 'fbOss', 131.24);
INSERT INTO products ( name, price) VALUES ( 'MNQFZbPHwlai', 690.68);
INSERT INTO products ( name, price) VALUES ( 'QLEMfvKzzqJLurHv', 738.15);
INSERT INTO products ( name, price) VALUES ( 'neOPlw', 769.26);
INSERT INTO products ( name, price) VALUES ( 'GhkVmP', 631.18);
INSERT INTO products ( name, price) VALUES ( 'skgovJKCur', 739.1);
INSERT INTO products ( name, price) VALUES ( 'tEQMpUopFgMyLCOXbaOs', 203.89);
INSERT INTO products ( name, price) VALUES ( 'a XdHwUylXqJWy', 781.38);
INSERT INTO products ( name, price) VALUES ( 'PnGxKtQ', 47.94);
INSERT INTO products ( name, price) VALUES ( 'BAGvj', 839.5);
INSERT INTO products ( name, price) VALUES ( 'zPCwSlIwGl LK', 804.88);
INSERT INTO products ( name, price) VALUES ( 'hdtUZ', 767.73);
INSERT INTO products ( name, price) VALUES ( 'RwIWengLfFL', 892.66);
INSERT INTO products ( name, price) VALUES ( 'PXgIoImeajtYywAn zvM', 587.08);
INSERT INTO products ( name, price) VALUES ( 'GTrGWhPzlBYl', 945.98);
INSERT INTO products ( name, price) VALUES ( 'tIRLhjSfFUzPkFbLhhd', 496.92);
INSERT INTO products ( name, price) VALUES ( 'PUfZSaxzBDtPvrI wgyq', 460.65);
INSERT INTO products ( name, price) VALUES ( 'OTspqFVJyokqMzoQMpC', 785.26);
INSERT INTO products ( name, price) VALUES ( 'YuEFL Gcbdr', 511.2);
INSERT INTO products ( name, price) VALUES ( 'kqtlAWXKKwgJdIBYNnQb', 330.8);
INSERT INTO products ( name, price) VALUES ( 'noKwNUYVrbdOelWTl', 867.37);
INSERT INTO products ( name, price) VALUES ( 'uVSYtypQLoJte', 941.59);
INSERT INTO products ( name, price) VALUES ( 'yuJdKPMszMXwlfsJCmMs', 961.13);
INSERT INTO products ( name, price) VALUES ( 'XtgygbjSLfyjUqAaqK', 28.2);
INSERT INTO products ( name, price) VALUES ( 'YVvcRFe', 933.13);
INSERT INTO products ( name, price) VALUES ( 'wgrFYOcFxbNNR', 635.08);
INSERT INTO products ( name, price) VALUES ( 'enZPhkqKKmlkcza', 34.89);
INSERT INTO products ( name, price) VALUES ( 'ZAyzyVMxMFWuWwZtCW', 949.06);
INSERT INTO products ( name, price) VALUES ( 'BJJKhhmRQgZxSZqDTJ', 614.99);
INSERT INTO products ( name, price) VALUES ( 'FaHKi', 215.26);
INSERT INTO products ( name, price) VALUES ( 'FxtXXpEICjuDhvyRTNF', 874.4);
INSERT INTO products ( name, price) VALUES ( 'EPRvpGGfyh', 190.41);
INSERT INTO products ( name, price) VALUES ( 'ESYaQtjI', 750.27);
INSERT INTO products ( name, price) VALUES ( 'pXM JZYuiGcPYU', 50.9);
INSERT INTO products ( name, price) VALUES ( 'CDYtCQGqy iDHAuLeIp', 694.54);
INSERT INTO products ( name, price) VALUES ( 'NLmMHwCObSGkgMzhBo', 782.57);
INSERT INTO products ( name, price) VALUES ( 'CeAduIczqlPFl', 403.23);
INSERT INTO products ( name, price) VALUES ( 'nOnhHIFYrdBgXHlEge', 724.66);
INSERT INTO products ( name, price) VALUES ( 'AeogTQh', 847.07);
INSERT INTO products ( name, price) VALUES ( 'U AVZ', 463.13);
INSERT INTO products ( name, price) VALUES ( 'uiDUWJJuaAiI', 30.33);
INSERT INTO products ( name, price) VALUES ( 'JgUzCM', 772.28);
INSERT INTO products ( name, price) VALUES ( 'SWEZcsM', 573.81);
INSERT INTO products ( name, price) VALUES ( 'rZXFlVkgTjAlOhtq', 71.43);
INSERT INTO products ( name, price) VALUES ( 'meryUf sBa LQghQHyzD', 833.43);
INSERT INTO products ( name, price) VALUES ( 'mwpfzMUwJgPEMkZCiy', 307.26);
INSERT INTO products ( name, price) VALUES ( 'MiIpFf', 264.05);
INSERT INTO products ( name, price) VALUES ( 'qHgOYxvwOCeMEHAW', 398.4);
INSERT INTO products ( name, price) VALUES ( 'COKDFYDu', 695.9);
INSERT INTO products ( name, price) VALUES ( 'XzHbMiLjSqoBHHxygL', 65.41);
INSERT INTO products ( name, price) VALUES ( 'fhPXZvQu rYiU Xw', 782.18);
INSERT INTO products ( name, price) VALUES ( 'OslUbEhjO', 836.08);
INSERT INTO products ( name, price) VALUES ( 'vvTjP g', 987.76);
INSERT INTO products ( name, price) VALUES ( 'cR VMfWsM', 986.25);
INSERT INTO products ( name, price) VALUES ( 'xMLdNbCNmY', 413.21);
INSERT INTO products ( name, price) VALUES ( 'EmaZs', 404.54);
INSERT INTO products ( name, price) VALUES ( 'PKYaR', 437.24);
INSERT INTO products ( name, price) VALUES ( 'iMtjnjarEZjc', 788.93);
INSERT INTO products ( name, price) VALUES ( 'hSGEiOZymaaF', 500.76);
INSERT INTO products ( name, price) VALUES ( 'UZGhfbjOWRCR ', 9);
INSERT INTO products ( name, price) VALUES ( 'PYRPtadmKLYtnA', 589.13);
INSERT INTO products ( name, price) VALUES ( 'IqzQtgu', 953.91);
INSERT INTO products ( name, price) VALUES ( 'TcGOowaPVu', 643.58);
INSERT INTO products ( name, price) VALUES ( 'LqCviMdtuTwN', 144.37);
INSERT INTO products ( name, price) VALUES ( 'jqvvroeUsY m', 896.55);
INSERT INTO products ( name, price) VALUES ( 'oWWep', 614.15);
INSERT INTO products ( name, price) VALUES ( 'MIM NdSASbK', 754.26);
INSERT INTO products ( name, price) VALUES ( 'bglu reDaQUIhq', 570.04);
INSERT INTO products ( name, price) VALUES ( 'iHswjokfyvfyIW', 929.61);
INSERT INTO products ( name, price) VALUES ( 'KYlpL', 730.48);
INSERT INTO products ( name, price) VALUES ( 'rBXNxD', 348.78);
INSERT INTO products ( name, price) VALUES ( 'EEATZrcRKhVgpfjIe', 805.45);
INSERT INTO products ( name, price) VALUES ( 'Xp xsaLslHlhm', 493.03);
INSERT INTO products ( name, price) VALUES ( 'AZbHex', 196.28);
INSERT INTO products ( name, price) VALUES ( 'dKaSaLZSH', 746.39);
INSERT INTO products ( name, price) VALUES ( 'dhGIvMO', 995.14);
INSERT INTO products ( name, price) VALUES ( 'OmAygVTaXveAhZBQgyH', 915.96);
INSERT INTO products ( name, price) VALUES ( 'SSdKu', 419.2);
INSERT INTO products ( name, price) VALUES ( 'RHHGl', 971.44);
INSERT INTO products ( name, price) VALUES ( 'rtrhcFIsBD', 769.51);
INSERT INTO products ( name, price) VALUES ( 'MaqypdSTGkDXneqW', 162.4);
INSERT INTO products ( name, price) VALUES ( 'tiCutIxlzbClCEfHr', 783.49);
INSERT INTO products ( name, price) VALUES ( 'NxlPjAcVOhsRwLCiL', 727.22);
INSERT INTO products ( name, price) VALUES ( 'YwlkkHgbzYpUDDrutzX', 73.39);
INSERT INTO products ( name, price) VALUES ( 'GZqQVrzarNNSLdqJMSo', 847.33);
INSERT INTO products ( name, price) VALUES ( 'ClVymAljseDZDY', 80.28);
INSERT INTO products ( name, price) VALUES ( 'iXOlWpeWwGxITNloEq', 808.79);
INSERT INTO products ( name, price) VALUES ( 'VaebgxTimFdhphacRP', 991.89);
INSERT INTO products ( name, price) VALUES ( 'drDrGDeYkWmEkmcpkJ', 298.7);
INSERT INTO products ( name, price) VALUES ( 'chmYjG', 340.98);
INSERT INTO products ( name, price) VALUES ( 'nJjwevrrMZIYTJOgsCP', 758.56);
INSERT INTO products ( name, price) VALUES ( 'PQpKnwzQBwQAQpiAGHm', 121.64);
INSERT INTO products ( name, price) VALUES ( 'cIXxtC', 125.49);
INSERT INTO products ( name, price) VALUES ( 'PWDZGxLxmTDxZpwYoySL', 625.49);
INSERT INTO products ( name, price) VALUES ( 'pWXBFblxYkBpbTfvEjy', 714.98);
INSERT INTO products ( name, price) VALUES ( 'vklFmMN', 860.58);
INSERT INTO products ( name, price) VALUES ( 'xuurE  Ybig', 189.61);
INSERT INTO products ( name, price) VALUES ( 'iBNIlD', 738.17);
INSERT INTO products ( name, price) VALUES ( 'ynbQS', 921.02);
INSERT INTO products ( name, price) VALUES ( 'WfuhIKezjOPM', 544.89);
INSERT INTO products ( name, price) VALUES ( 'ykiFjwRbAEOFJ', 520.69);
INSERT INTO products ( name, price) VALUES ( 'ialGcNQGQVvl', 466.01);
INSERT INTO products ( name, price) VALUES ( 'RwAsY', 513.77);
INSERT INTO products ( name, price) VALUES ( 'AGheGXdzPipdS', 734.37);
INSERT INTO products ( name, price) VALUES ( 'IDW  WIXOjlMRM NZa', 751.77);
INSERT INTO products ( name, price) VALUES ( 'evPoiIZc', 425.25);
INSERT INTO products ( name, price) VALUES ( 'BEEeruZhTq Tjf', 337.36);
INSERT INTO products ( name, price) VALUES ( 'uTKXJzUJZekQs', 190.82);
INSERT INTO products ( name, price) VALUES ( 'xgJPrrHAMzr', 284.86);
INSERT INTO products ( name, price) VALUES ( 'ElxgmBAokZOFesvLEa', 578.76);
INSERT INTO products ( name, price) VALUES ( 'JJHReAACAcJRCAGyMu', 536.96);
INSERT INTO products ( name, price) VALUES ( 'wDlDMYAvGQWKDcLgvD', 892.32);
INSERT INTO products ( name, price) VALUES ( 'JEWQfluUjNdPPA', 37.31);
INSERT INTO products ( name, price) VALUES ( 'XkmBGrMGmdY', 431.65);
INSERT INTO products ( name, price) VALUES ( 'UiYhdRsmMZARAZDQeT', 763.28);
INSERT INTO products ( name, price) VALUES ( 'SPqrpdOxOH', 552.4);
INSERT INTO products ( name, price) VALUES ( 'WPHTRxVDnI', 424.6);
INSERT INTO products ( name, price) VALUES ( 'LNjaBcloNbbLtn', 580.9);
INSERT INTO products ( name, price) VALUES ( 'egKJsMqIj M', 822.45);
INSERT INTO products ( name, price) VALUES ( 'lPgZP', 317.58);
INSERT INTO products ( name, price) VALUES ( 'ryuJNmFnCZEfhw', 989.15);
INSERT INTO products ( name, price) VALUES ( 'CkEm OdTU', 320.9);
INSERT INTO products ( name, price) VALUES ( 'eQQFhBWmqAaxMmOYlM', 185.56);
INSERT INTO products ( name, price) VALUES ( 'rZSIajp', 884.88);
INSERT INTO products ( name, price) VALUES ( 'ePEPIOHDIuVyI', 238.64);
INSERT INTO products ( name, price) VALUES ( 'aKPrFptBdRPZm', 634.54);
INSERT INTO products ( name, price) VALUES ( 'sSOyGVTSYKYSRLcy', 55.85);
INSERT INTO products ( name, price) VALUES ( 'ILgzUIWcUbUprpwBJi', 987.03);
INSERT INTO products ( name, price) VALUES ( 'XgPpJSpjOpW Rnz', 711.94);
INSERT INTO products ( name, price) VALUES ( 'MZrfPEXwk', 434.59);
INSERT INTO products ( name, price) VALUES ( 'EJdzLBhdooHYrAha dfD', 586.92);
INSERT INTO products ( name, price) VALUES ( 'wGdcLJDaHL NWiHrPT', 974.31);
INSERT INTO products ( name, price) VALUES ( 'fYTUNAAjsy', 257.52);
INSERT INTO products ( name, price) VALUES ( 'mRmKdYt  MPhVpWBjv', 524.22);
INSERT INTO products ( name, price) VALUES ( 'YHQBRSLFTwTtUcqHAEp', 881.91);
INSERT INTO products ( name, price) VALUES ( 'mmXUxwkmUydsdWqSdr', 18.58);
INSERT INTO products ( name, price) VALUES ( 'AQIAijQAoak', 29.92);
INSERT INTO products ( name, price) VALUES ( 'FdRvsWhWDCOSjCmhITf', 42.26);
INSERT INTO products ( name, price) VALUES ( 'JBIQXKzTs', 315.95);
INSERT INTO products ( name, price) VALUES ( 'genReevSWXFCjovbOjwh', 282.25);
INSERT INTO products ( name, price) VALUES ( 'nunHEaoLomkmRPBTP', 708.9);
INSERT INTO products ( name, price) VALUES ( 'SikeeTz', 239.47);
INSERT INTO products ( name, price) VALUES ( 'G QbmAlmlrXhGBSFu', 980.19);
INSERT INTO products ( name, price) VALUES ( 'jwyLuTBX', 531.53);
INSERT INTO products ( name, price) VALUES ( 'kNGGGhsn', 826.57);
INSERT INTO products ( name, price) VALUES ( 'WoWVUAt', 448.03);
INSERT INTO products ( name, price) VALUES ( 'pHsriwwu', 488.9);
INSERT INTO products ( name, price) VALUES ( 'bwTxamCtKADKXtdGFGEd', 45.9);
INSERT INTO products ( name, price) VALUES ( 'QYqZWXzJavpmXI', 478.07);
INSERT INTO products ( name, price) VALUES ( 'due dK', 879.99);
INSERT INTO products ( name, price) VALUES ( 'EYEPQpGyttbJUWdICPZ', 679.55);
INSERT INTO products ( name, price) VALUES ( 'vyhzlTAJrkuQf', 290.04);
INSERT INTO products ( name, price) VALUES ( 'nDsBRptjsOMFGCF', 848.09);
INSERT INTO products ( name, price) VALUES ( 'MxlrFuhXKbjF', 31.3);
INSERT INTO products ( name, price) VALUES ( 'iUASaDPMxAyFg', 146.55);
INSERT INTO products ( name, price) VALUES ( 'KocUbxJFkzfaWsv', 735.75);
INSERT INTO products ( name, price) VALUES ( 'eMeqN', 899.14);
INSERT INTO products ( name, price) VALUES ( 'snTFjqbgFnVOSnXJ', 657.93);
INSERT INTO products ( name, price) VALUES ( 'TVhn JOq', 110.89);
INSERT INTO products ( name, price) VALUES ( 'brr pyOec', 977.99);
INSERT INTO products ( name, price) VALUES ( 'yXFWYNkU', 66.44);
INSERT INTO products ( name, price) VALUES ( 'lyFXYvtLnkvakYCjVWkG', 752.53);
INSERT INTO products ( name, price) VALUES ( 'UrsbemBWAuwdArPDxB', 787.24);
INSERT INTO products ( name, price) VALUES ( 'pSVRFBDShOQJdmO', 635.35);
INSERT INTO products ( name, price) VALUES ( 'qbGeODj', 695.25);
INSERT INTO products ( name, price) VALUES ( 'zIDVzK tzOvc', 192.81);
INSERT INTO products ( name, price) VALUES ( 'MsUreO tvHrQDZf', 790.07);
INSERT INTO products ( name, price) VALUES ( 'JLhTQvcfTMXikqVn', 482.6);
INSERT INTO products ( name, price) VALUES ( 'tVZWI', 781.77);
INSERT INTO products ( name, price) VALUES ( 'dAozBaEWTvF', 108.39);
INSERT INTO products ( name, price) VALUES ( ' ZAsAzOqzXbDRyP ZIz', 465.36);
INSERT INTO products ( name, price) VALUES ( 'AXfidWVQWyGUDNBE', 962.64);
INSERT INTO products ( name, price) VALUES ( 'yCLwlM', 167.39);
INSERT INTO products ( name, price) VALUES ( 'uFsMbbUyTcwAhNz', 107.4);
INSERT INTO products ( name, price) VALUES ( 'ydXYtggBAdsGnzLl', 570.41);
INSERT INTO products ( name, price) VALUES ( 'pfoSZpztlDnqWtdh', 982.88);
INSERT INTO products ( name, price) VALUES ( 'lRrNZoqVDerLXwGJdkN', 806.23);
INSERT INTO products ( name, price) VALUES ( 'QWVyPNROEFdzg', 818.35);
INSERT INTO products ( name, price) VALUES ( 'KdbEaJkZVGSWvxzva', 140.26);
INSERT INTO products ( name, price) VALUES ( 'jmFLKKAZhbL', 697.19);
INSERT INTO products ( name, price) VALUES ( 'PCYskXtifsVXneRFS', 85.03);
INSERT INTO products ( name, price) VALUES ( 'wUNlQeOLnvmsUp lNw', 784.98);
INSERT INTO products ( name, price) VALUES ( 'LjTer', 462.04);
INSERT INTO products ( name, price) VALUES ( 'PBhrABmvH', 165.65);
INSERT INTO products ( name, price) VALUES ( 'SQgdiHJBzVnkk', 193.57);
INSERT INTO products ( name, price) VALUES ( 'QvADcJINDZfbcIzZf', 262.69);
INSERT INTO products ( name, price) VALUES ( 'fFuxLqDLUcZFAJ', 299.11);
INSERT INTO products ( name, price) VALUES ( 'PUTZJPppSMA', 82.55);
INSERT INTO products ( name, price) VALUES ( 'BBIrdbqSWIibxHDsXSfV', 826.07);
INSERT INTO products ( name, price) VALUES ( 'PVufAiYOxYh Si', 428.77);
INSERT INTO products ( name, price) VALUES ( 'bAeiKpGPw', 978.29);
INSERT INTO products ( name, price) VALUES ( 'HaSTuctjw', 521.91);
INSERT INTO products ( name, price) VALUES ( 'zKHrtcSwCXMNFhnrN', 986.43);
INSERT INTO products ( name, price) VALUES ( 'XlZ KZTVsgtcOzLqq', 728.98);
INSERT INTO products ( name, price) VALUES ( 'dhdeZivYkISwyN w', 292.7);
INSERT INTO products ( name, price) VALUES ( 'pneLNrVDg', 285.44);
INSERT INTO products ( name, price) VALUES ( 'BlVvBhCXKI', 771.28);
INSERT INTO products ( name, price) VALUES ( 'upezjjW', 240.95);
INSERT INTO products ( name, price) VALUES ( 'GEPEAtjEFV', 779.55);
INSERT INTO products ( name, price) VALUES ( 'yLtSfnhziDgk', 309.56);
INSERT INTO products ( name, price) VALUES ( 'XbRjxH', 263.95);
INSERT INTO products ( name, price) VALUES ( 'AqGnbHPPgNwck', 111.13);
INSERT INTO products ( name, price) VALUES ( 'QmVOdu okTP', 823.82);
INSERT INTO products ( name, price) VALUES ( ' lKXJSsKHMQlPgiA', 547.57);
INSERT INTO products ( name, price) VALUES ( 'fvqIqeRuJmZ', 691.13);
INSERT INTO products ( name, price) VALUES ( 'IiqBgTKZ', 618.79);
INSERT INTO products ( name, price) VALUES ( '  zGNLp JR', 963.47);
INSERT INTO products ( name, price) VALUES ( 'wBCDhLffpqhIg', 700.51);
INSERT INTO products ( name, price) VALUES ( 'ejQbjZQJveWQGscU', 40.39);
INSERT INTO products ( name, price) VALUES ( 'XwqxL', 965.15);
INSERT INTO products ( name, price) VALUES ( 'DopAsNXvFrFdfBFWK', 853.52);
INSERT INTO products ( name, price) VALUES ( 'wfPqZQrvP', 508.09);
INSERT INTO products ( name, price) VALUES ( 'HuxJfSEgPjcbTpLeA', 145.94);
INSERT INTO products ( name, price) VALUES ( 'yAjnvUQAPN Yd', 865.92);
INSERT INTO products ( name, price) VALUES ( 'BrfPBUcWG cyGr', 152.02);
INSERT INTO products ( name, price) VALUES ( 'jtlKOQTsMRiJ', 52.07);
INSERT INTO products ( name, price) VALUES ( 'wVBja GXBejunFXS', 917.71);
INSERT INTO products ( name, price) VALUES ( 'VzSnLYFWEtjEsjwTwJf', 997.78);
INSERT INTO products ( name, price) VALUES ( 'epDcmdFNLMHCyphvw', 150.72);
INSERT INTO products ( name, price) VALUES ( 'drOWVKT Ga', 57.94);
INSERT INTO products ( name, price) VALUES ( 'EQdZIuGgvwzeZVHEj', 413.4);
INSERT INTO products ( name, price) VALUES ( 'OmAqFMlMA', 292.08);
INSERT INTO products ( name, price) VALUES ( 'TrFBegiwHm', 951.6);
INSERT INTO products ( name, price) VALUES ( 'ztPnJBZi', 893.58);
INSERT INTO products ( name, price) VALUES ( 'qkHyaSGCLrWZ', 932.47);
INSERT INTO products ( name, price) VALUES ( 'JaBcsrrnaIIlRyNtFZ', 276.95);
INSERT INTO products ( name, price) VALUES ( 'udWIzgPQEZowcRz', 887.47);
INSERT INTO products ( name, price) VALUES ( 'KcqA cyReXBwakCyIt ', 94.7);
INSERT INTO products ( name, price) VALUES ( 'DuGAXSOqsM', 449.91);
INSERT INTO products ( name, price) VALUES ( 'vtFIDpW', 770.71);
INSERT INTO products ( name, price) VALUES ( 'JkphCYjJYkQrvGQOQ', 111.61);
INSERT INTO products ( name, price) VALUES ( 'yklbH', 566.9);
INSERT INTO products ( name, price) VALUES ( 'ljshNEtiXsAxnP hrSY', 366.89);
INSERT INTO products ( name, price) VALUES ( 'noVoiqGRyJu', 968.79);
INSERT INTO products ( name, price) VALUES ( 'uNAJEQSti', 549.04);
INSERT INTO products ( name, price) VALUES ( 'VjETao', 150.97);
INSERT INTO products ( name, price) VALUES ( 'ihXkwVY', 668.46);
INSERT INTO products ( name, price) VALUES ( 'MfxhUx', 51.63);
INSERT INTO products ( name, price) VALUES ( 'tOwGb eHsulKb', 122.44);
INSERT INTO products ( name, price) VALUES ( 'ODdVt', 257.63);
INSERT INTO products ( name, price) VALUES ( 'OyQckS', 899.61);
INSERT INTO products ( name, price) VALUES ( 'BXSxSeWU', 381.87);
INSERT INTO products ( name, price) VALUES ( 'yBnKBIovvQrVDv', 510.34);
INSERT INTO products ( name, price) VALUES ( 'gUWhoISdqQl', 791.26);
INSERT INTO products ( name, price) VALUES ( 'VR FJwTZKU', 758.46);
INSERT INTO products ( name, price) VALUES ( 'CQrXSSvDKycwHyWlf', 755.51);
INSERT INTO products ( name, price) VALUES ( 'XTRnYxDDYlkDDdI', 810.3);
INSERT INTO products ( name, price) VALUES ( 'hHEXR', 286);
INSERT INTO products ( name, price) VALUES ( 'Ojiqsa', 824.25);
INSERT INTO products ( name, price) VALUES ( 'XuaRZTaTVamCragbIf', 414.64);
INSERT INTO products ( name, price) VALUES ( 'JmGQ ', 283.21);
INSERT INTO products ( name, price) VALUES ( 'azJkMzSGoHFHZVSTAob', 423.11);
INSERT INTO products ( name, price) VALUES ( 'bTZBxEYBVRy', 157.41);
INSERT INTO products ( name, price) VALUES ( 'tzuJnL', 396.85);
INSERT INTO products ( name, price) VALUES ( 'VzxXWrmxTiotGH', 930.71);
INSERT INTO products ( name, price) VALUES ( 'QysTGmHCvzu qUwFyxo', 509.65);
INSERT INTO products ( name, price) VALUES ( 'MzU tTYr', 497.46);
INSERT INTO products ( name, price) VALUES ( 'VKDzrHOWIVE', 227.47);
INSERT INTO products ( name, price) VALUES ( 'iZBoEdINhnBe TiZJUI', 925.21);
INSERT INTO products ( name, price) VALUES ( 'mfyjLdScWvWpncb', 597.5);
INSERT INTO products ( name, price) VALUES ( 'AmjZVxf atB', 177.46);
INSERT INTO products ( name, price) VALUES ( 'hlV fPXylxDBpjJyyGO', 485.42);
INSERT INTO products ( name, price) VALUES ( 'kiXIPnSVFNws', 820.05);
INSERT INTO products ( name, price) VALUES ( 'ONkhIBuNcCXeDw', 902.74);
INSERT INTO products ( name, price) VALUES ( 'etxzrOrM', 723.34);
INSERT INTO products ( name, price) VALUES ( 'meqbDjZfy', 801.96);
INSERT INTO products ( name, price) VALUES ( 'urPpJAd PpuIV', 376.96);
INSERT INTO products ( name, price) VALUES ( 'FzLkJoXvbNOwHstN', 318.76);
INSERT INTO products ( name, price) VALUES ( 'VuZjfEXd LBD', 952.79);
INSERT INTO products ( name, price) VALUES ( 'UjPaVXllxQmuKtip', 805.93);
INSERT INTO products ( name, price) VALUES ( 'BFNqIvGUS hc', 449.51);
INSERT INTO products ( name, price) VALUES ( 'LiBWcGEpwrKTH', 479.83);
INSERT INTO products ( name, price) VALUES ( 'DCynoORyETVV dprbYsG', 895.13);
INSERT INTO products ( name, price) VALUES ( 'cLfGeY', 299.77);
INSERT INTO products ( name, price) VALUES ( 'jPxYkXuBEfqAPLIeglya', 89.89);
INSERT INTO products ( name, price) VALUES ( 'hbnGw', 24.38);
INSERT INTO products ( name, price) VALUES ( 'TVln  ktjZ', 355.41);
INSERT INTO products ( name, price) VALUES ( 'yimfWLvoJLexmwRKH', 804.82);
INSERT INTO products ( name, price) VALUES ( 'uVsbIl', 58.07);
INSERT INTO products ( name, price) VALUES ( 'XRguA', 142.51);
INSERT INTO products ( name, price) VALUES ( 'DEJGDETu XnxkJ', 379.16);
INSERT INTO products ( name, price) VALUES ( 'zJNGzUuRxQpJjiPTsAI', 149.03);
INSERT INTO products ( name, price) VALUES ( 'tokKyFXC', 314.32);
INSERT INTO products ( name, price) VALUES ( 'TOYGpYTTZGoOBcAoEri', 478.7);
INSERT INTO products ( name, price) VALUES ( 'EYFLremzFNsxSiICuPV', 112.7);
INSERT INTO products ( name, price) VALUES ( 'HYpXJZKQPStOp', 107.29);
INSERT INTO products ( name, price) VALUES ( 'jfpwgDJTfhMWcuVzwWP', 856.05);
INSERT INTO products ( name, price) VALUES ( 'FCKuFOavBNkKlzAbHUQa', 116.98);
INSERT INTO products ( name, price) VALUES ( 'GhmScrATFM', 938.09);
INSERT INTO products ( name, price) VALUES ( 'mznSdgzBzvezdrXPRWF', 928.35);
INSERT INTO products ( name, price) VALUES ( 'UOQlhUpTnGELuJZ', 911.6);
INSERT INTO products ( name, price) VALUES ( 'gYX qmNBrxK', 915.26);
INSERT INTO products ( name, price) VALUES ( 'irHqvtMRxCJRhTOvsf', 625.36);
INSERT INTO products ( name, price) VALUES ( 'oWtSALihiPtprV', 617.81);
INSERT INTO products ( name, price) VALUES ( 'qeJSkgkjUwJfcLCl', 816.95);
INSERT INTO products ( name, price) VALUES ( 'GEjtvnDPogHyY', 40.56);
INSERT INTO products ( name, price) VALUES ( 'dkKVGVbXYg', 364.39);
INSERT INTO products ( name, price) VALUES ( 'eAHxjtZcFKyBfR', 55.19);
INSERT INTO products ( name, price) VALUES ( 'KmfGcdOiAa', 125.44);
INSERT INTO products ( name, price) VALUES ( 'WWYMNZyR', 133.96);
INSERT INTO products ( name, price) VALUES ( 'ahArjUPcrj', 772.99);
INSERT INTO products ( name, price) VALUES ( 'SosrAuNucdnaHH', 237.99);
INSERT INTO products ( name, price) VALUES ( 'JyGajof', 818.87);
INSERT INTO products ( name, price) VALUES ( 'uwbCdbqXIKoBgLXsHb', 981.77);
INSERT INTO products ( name, price) VALUES ( 'PzqEIOYDuubTjPTNE', 919.08);
INSERT INTO products ( name, price) VALUES ( 'csUfkRQkyGAvzRgTKWXd', 747.7);
INSERT INTO products ( name, price) VALUES ( 'URVuTUJnLdZxkh ', 485.02);
INSERT INTO products ( name, price) VALUES ( 'eiXLsypagUfsH', 94.99);
INSERT INTO products ( name, price) VALUES ( 'tGJWdKE', 15.03);
INSERT INTO products ( name, price) VALUES ( 'psoBDRpHI', 775.72);
INSERT INTO products ( name, price) VALUES ( 'ASnqGHkSL', 535.82);
INSERT INTO products ( name, price) VALUES ( 'GEImTCpoIQSKWigjTAI', 861.56);
INSERT INTO products ( name, price) VALUES ( 'oASRlRQrXwaRj', 422.83);
INSERT INTO products ( name, price) VALUES ( 'Z acmKO', 904.95);
INSERT INTO products ( name, price) VALUES ( 'QkXxGLhudgzJDuSw ZC', 902.16);
INSERT INTO products ( name, price) VALUES ( 'UfYDMdHuOB', 214.51);
INSERT INTO products ( name, price) VALUES ( 'qKnrhlhNciYWJzaUt', 38.73);
INSERT INTO products ( name, price) VALUES ( 'wNHbDN', 356.58);
INSERT INTO products ( name, price) VALUES ( 'SXFWZuUPAruRH', 285.02);
INSERT INTO products ( name, price) VALUES ( 'vPidAvtVhzGqOquHviC', 898.68);
INSERT INTO products ( name, price) VALUES ( 'ZiJhTbbL', 982.36);
INSERT INTO products ( name, price) VALUES ( 'peEPlZX', 963.16);
INSERT INTO products ( name, price) VALUES ( 'vHZz o', 915.94);
INSERT INTO products ( name, price) VALUES ( 'uMjUBbD', 723.73);
INSERT INTO products ( name, price) VALUES ( 'eGIkafSedSVJoim', 850.77);
INSERT INTO products ( name, price) VALUES ( 'VnOvZnZmDHShGyRw', 168.71);
INSERT INTO products ( name, price) VALUES ( 'PmrQuMZiUAH', 810.1);
INSERT INTO products ( name, price) VALUES ( 'onMOFonFJCJZtTYmu', 451.7);
INSERT INTO products ( name, price) VALUES ( 'gWhhlVfrFd', 251.68);
INSERT INTO products ( name, price) VALUES ( 'ubz qG', 905.98);
INSERT INTO products ( name, price) VALUES ( 'PrvL bw', 464.1);
INSERT INTO products ( name, price) VALUES ( 'DGUJBSJrI', 961.57);
INSERT INTO products ( name, price) VALUES ( 'epquLuqylbsbJ', 762.46);
INSERT INTO products ( name, price) VALUES ( 'fGueFzNO', 498.83);
INSERT INTO products ( name, price) VALUES ( 'LbjMQ', 466.48);
INSERT INTO products ( name, price) VALUES ( 'EWmKKJ', 51.69);
INSERT INTO products ( name, price) VALUES ( 'cZgnJD yeXlfdljW', 567.6);
INSERT INTO products ( name, price) VALUES ( 'XIkf qpxXNwgiSfyKP', 653.66);
INSERT INTO products ( name, price) VALUES ( 'msSQWczYvAbCfO', 722.93);
INSERT INTO products ( name, price) VALUES ( 'viGyNWWlCIyFGYBUmIe', 716.89);
INSERT INTO products ( name, price) VALUES ( 'qVxpbGz', 146.66);
INSERT INTO products ( name, price) VALUES ( 'qITLmSwJRYQwuep', 18.11);
INSERT INTO products ( name, price) VALUES ( 'vkxvrxoiRtaauvDynkG', 340.33);
INSERT INTO products ( name, price) VALUES ( 'JxwCQn', 263.03);
INSERT INTO products ( name, price) VALUES ( 'JRaxjeKZtvLfE', 892.86);
INSERT INTO products ( name, price) VALUES ( 'nDsGAAWv', 563.67);
INSERT INTO products ( name, price) VALUES ( 'xRuxJptfUfmUQ', 234.2);
INSERT INTO products ( name, price) VALUES ( 'EYmDJINhsd JCzqDQKD', 908.26);
INSERT INTO products ( name, price) VALUES ( 'lVCSoBtfebFYZozFtDlV', 837.76);
INSERT INTO products ( name, price) VALUES ( 'GmsPrNIamloQihXI', 74.97);
INSERT INTO products ( name, price) VALUES ( 'NGCDqo', 604.01);
INSERT INTO products ( name, price) VALUES ( 'dxKvWIBXOROcy', 317.72);
INSERT INTO products ( name, price) VALUES ( 'jGBVqUfpWGCBOVy', 776.98);
INSERT INTO products ( name, price) VALUES ( 'FHKFHdCJmMxDTf', 671.65);
INSERT INTO products ( name, price) VALUES ( 'CcfSRg', 347.27);
INSERT INTO products ( name, price) VALUES ( 'AtDdXxeC OWeMjzQ', 307.89);
INSERT INTO products ( name, price) VALUES ( 'kWoLZgnhGjPWFHpTg', 592.6);
INSERT INTO products ( name, price) VALUES ( 'nKwjmaOgcdjoM', 565.89);
INSERT INTO products ( name, price) VALUES ( 'IKpuZAvYUBk', 590.16);
INSERT INTO products ( name, price) VALUES ( 'ZQhF XxzfvEfmFdQNI', 6.25);
INSERT INTO products ( name, price) VALUES ( 'lGWqsVqz', 20.55);
INSERT INTO products ( name, price) VALUES ( 'zkSme', 368.46);
INSERT INTO products ( name, price) VALUES ( 'pxsnZWFtESMMgXRnvF', 992.99);
INSERT INTO products ( name, price) VALUES ( 'KMYsVmLPXUN', 839.2);
INSERT INTO products ( name, price) VALUES ( 'AlaGW', 986.67);
INSERT INTO products ( name, price) VALUES ( 'IWqpZynfXPL', 619.71);
INSERT INTO products ( name, price) VALUES ( 'ucIfmrcqDhJ', 618.52);
INSERT INTO products ( name, price) VALUES ( 'tTuHsRcjLVhG', 707.68);
INSERT INTO products ( name, price) VALUES ( 'OfRtebk rsmwvqjT', 935.01);
INSERT INTO products ( name, price) VALUES ( 'GHtbr ', 922.64);
INSERT INTO products ( name, price) VALUES ( 'ChrjWjSCZ', 532.45);
INSERT INTO products ( name, price) VALUES ( 'QIF ZXrzMWuvxbnr', 299.56);
INSERT INTO products ( name, price) VALUES ( 'HheGgajuiAuOw WEGszN', 525.57);
INSERT INTO products ( name, price) VALUES ( 'p lPks', 819.06);
INSERT INTO products ( name, price) VALUES ( 'aHTkZBprxYTCrXKNok', 792.66);
INSERT INTO products ( name, price) VALUES ( 'AxbCroDToyBHN ynXKq', 315.59);
INSERT INTO products ( name, price) VALUES ( 'NYGNWBsArYiGwAqlW', 95.36);
INSERT INTO products ( name, price) VALUES ( 'vuSKdPubGmw', 737.02);
INSERT INTO products ( name, price) VALUES ( 'ZRGOgQaCndcmfZvODc', 557.74);
INSERT INTO products ( name, price) VALUES ( 'kFPvWPFpvdOwrie', 871.27);
INSERT INTO products ( name, price) VALUES ( 'aSzNI', 707.66);
INSERT INTO products ( name, price) VALUES ( 'dZncnm', 91.52);
INSERT INTO products ( name, price) VALUES ( 'SqwbSaxSOiBIaokPAgq', 474.76);
INSERT INTO products ( name, price) VALUES ( 'qTKvIhPMeDWYcDbhSsP', 214.71);
INSERT INTO products ( name, price) VALUES ( 'vlkKVBA', 976.36);
INSERT INTO products ( name, price) VALUES ( 'ama kSjLaUTeTOT', 221.41);
INSERT INTO products ( name, price) VALUES ( 'vlzEfBpbRHX', 115.1);
INSERT INTO products ( name, price) VALUES ( 'zfwAug', 109.96);
INSERT INTO products ( name, price) VALUES ( 'GirwpFtmfTZxbTfW', 616.28);
INSERT INTO products ( name, price) VALUES ( 'sBpiKW', 93.65);
INSERT INTO products ( name, price) VALUES ( 'rnwQeWhyX', 557.63);
INSERT INTO products ( name, price) VALUES ( 'FRXlaewFSY', 336.34);
INSERT INTO products ( name, price) VALUES ( 'K TlIM', 501.82);
INSERT INTO products ( name, price) VALUES ( 'RkUzyrkyz', 528.91);
INSERT INTO products ( name, price) VALUES ( 'Nxjctvf', 51.87);
INSERT INTO products ( name, price) VALUES ( 'oDrPc', 809.44);
INSERT INTO products ( name, price) VALUES ( 'aACrQqsfUpKSbG', 554.53);
INSERT INTO products ( name, price) VALUES ( 'FfLjidQ', 979.59);
INSERT INTO products ( name, price) VALUES ( 'zFgEZDNSFIiLTR', 773.02);
INSERT INTO products ( name, price) VALUES ( 'lQEdTbxgQlt', 596.78);
INSERT INTO products ( name, price) VALUES ( 'LBkmiFMCHGPBis', 891.91);
INSERT INTO products ( name, price) VALUES ( 'iiAGCxm', 417.58);
INSERT INTO products ( name, price) VALUES ( 'LYiXhDKUkb', 135.89);
INSERT INTO products ( name, price) VALUES ( 'ChiMfdNccR', 443.57);
INSERT INTO products ( name, price) VALUES ( 'qhCHGA', 932.33);
INSERT INTO products ( name, price) VALUES ( 'AgDxAYT', 158.82);
INSERT INTO products ( name, price) VALUES ( 'pmKJFnT', 81.03);
INSERT INTO products ( name, price) VALUES ( 'UdekhcAOp', 124.48);
INSERT INTO products ( name, price) VALUES ( 'ydBEisTUm', 979.76);
INSERT INTO products ( name, price) VALUES ( 'cazmqcrYAX', 277.38);
INSERT INTO products ( name, price) VALUES ( 'kLL xJSqzqCjCUfrssQl', 762.75);
INSERT INTO products ( name, price) VALUES ( 'CSBkb TldnDQkRy TzQ', 806.83);
INSERT INTO products ( name, price) VALUES ( 'Jok hsggDGZOUuX', 80.8);
INSERT INTO products ( name, price) VALUES ( 'xoPBBhtlrGFut', 335.87);
INSERT INTO products ( name, price) VALUES ( 'ZqmHsbTHzZBvJOG', 399.03);
INSERT INTO products ( name, price) VALUES ( 'OgHJvwrFWkJugiHtLt', 841.12);
INSERT INTO products ( name, price) VALUES ( 'iSzBD  QYxlpN', 172.92);
INSERT INTO products ( name, price) VALUES ( 'uxvBOfxVcqAitLzDLIV', 14.81);
INSERT INTO products ( name, price) VALUES ( 'DHSkzRTwesYhLg', 588.61);
INSERT INTO products ( name, price) VALUES ( 'ievsAYqsjkrMrSEwyY A', 478.34);
INSERT INTO products ( name, price) VALUES ( 'OzbnUfmjr', 427.66);
INSERT INTO products ( name, price) VALUES ( 'wHKcTd', 656.53);
INSERT INTO products ( name, price) VALUES ( 'akHVvCjeXf cHkjGfEP', 401.05);
INSERT INTO products ( name, price) VALUES ( 'YwjwySqJnbvVCFkkqJm', 144.38);
INSERT INTO products ( name, price) VALUES ( 'odcWBBdH t j', 233.01);
INSERT INTO products ( name, price) VALUES ( 'QgViyOhjmRy', 396.24);
